import { diag, draw, iff, stab } from "../ops";
import type { CardDef } from "../../core/types";

export const DIAGNOSTIC_CARDS = [
  {
    id: "physical_exam",
    nameKo: "신체 진찰",
    nameEn: "Physical examination",
    kind: "diagnostic",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [diag(2), stab(4)],
    upgrade: { effects: [diag(2), stab(7)] },
    flavor: "시진, 촉진, 타진, 청진.",
  },
  {
    id: "blood_test",
    nameKo: "혈액 검사",
    nameEn: "Blood tests",
    kind: "diagnostic",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [diag(2), draw(1)],
    upgrade: { effects: [diag(3), draw(1)] },
    flavor: "CBC, 화학, 염증 수치.",
  },
  {
    id: "urinalysis",
    nameKo: "소변 검사",
    nameEn: "Urinalysis",
    kind: "diagnostic",
    rarity: "common",
    cost: 0,
    target: "enemy",
    tags: [],
    effects: [diag(1), iff({ any: [{ targetTrait: ["renal"] }, { targetCategory: ["metabolic"] }] }, [diag(2)])],
    upgrade: { effects: [diag(2), iff({ any: [{ targetTrait: ["renal"] }, { targetCategory: ["metabolic"] }] }, [diag(2)])] },
    flavor: "백혈구, 아질산염, 케톤.",
  },
  {
    id: "chest_xray",
    nameKo: "흉부 X선",
    nameEn: "Chest X-ray",
    kind: "diagnostic",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [diag(2), stab(3), iff({ targetTrait: ["chest"] }, [diag(2)])],
    upgrade: { effects: [diag(2), stab(6), iff({ targetTrait: ["chest"] }, [diag(2)])] },
    flavor: "PA, 흡기 충분.",
  },
  {
    id: "ecg",
    nameKo: "심전도",
    nameEn: "Electrocardiogram",
    kind: "diagnostic",
    rarity: "common",
    cost: 0,
    target: "enemy",
    tags: [],
    effects: [diag(1), iff({ targetTrait: ["cardiac"] }, [diag(2), { op: "reveal_intent", target: "target" }])],
    upgrade: { effects: [diag(2), iff({ targetTrait: ["cardiac"] }, [diag(2), { op: "reveal_intent", target: "target" }])] },
    flavor: "12유도, 10초.",
  },
  {
    id: "abga",
    nameKo: "동맥혈 가스 분석",
    nameEn: "Arterial blood gas",
    kind: "diagnostic",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [diag(2), iff({ targetCategory: ["metabolic", "respiratory"] }, [draw(2)])],
    upgrade: { effects: [diag(3), iff({ targetCategory: ["metabolic", "respiratory"] }, [draw(2)])] },
    flavor: "pH, PaCO₂, HCO₃⁻. 검사는 산증을 고치지 않는다.",
  },
  {
    id: "culture",
    nameKo: "배양 검사",
    nameEn: "Culture",
    kind: "diagnostic",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [diag(1), { op: "delay", turns: 2, effects: [diag(4)] }],
    upgrade: { cost: 0 },
    flavor: "항생제보다 먼저. 결과는 이틀 뒤에.",
  },
  {
    id: "pocus",
    nameKo: "현장 초음파",
    nameEn: "Point-of-care ultrasound",
    kind: "diagnostic",
    rarity: "uncommon",
    cost: 0,
    target: "enemy",
    tags: [],
    keywords: ["exhaust"],
    effects: [diag(2), iff({ targetTrait: ["us_visible"] }, [diag(3)])],
    upgrade: { effects: [diag(3), iff({ targetTrait: ["us_visible"] }, [diag(3)])] },
    flavor: "침대 옆에서 3분.",
  },
  {
    id: "ct_scan",
    nameKo: "CT",
    nameEn: "Computed tomography",
    kind: "diagnostic",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    effects: [diag(3, "all_enemies")],
    upgrade: { effects: [diag(4, "all_enemies")] },
    flavor: "조영제 알레르기 확인하셨죠?",
  },
  {
    id: "attending_rounds",
    nameKo: "교수 회진",
    nameEn: "Attending rounds",
    kind: "diagnostic",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    tags: [],
    keywords: ["exhaust"],
    effects: [{ op: "confirm", target: "target" }, { op: "targeted_bonus", pct: 50, target: "target" }],
    upgrade: { cost: 0 },
    flavor: "\"이거 교과서에 나오는 전형적인 증례잖아.\"",
  },
] satisfies CardDef[];
