import { choose, dmg, draw, opt, purge, spectrum, stab } from "../ops";
import type { CardDef, EffectOp } from "../../core/types";

// 원인균 순서: 폐렴알균 비정형 대장균 ESBL MSSA MRSA 복강내 C.diff 녹농균 그람음성 바이러스 지역사회
const CRO = spectrum("W I W I N I R I I N I N");
const TZP = spectrum("N I N R N I W I W W I N");
const MEM = spectrum("N I N W N I W I W W I N");
const VAN = spectrum("N I I I N W I W I I I N");
const GEN = spectrum("I I W N I I R I N W I N");
const LVX = spectrum("W W N R R I R I N N I N");
const CLR = spectrum("R W I I R I I I I I I N");
const MTZ = spectrum("I I I I I I R W I I I N");

const clearInflammation: EffectOp = { op: "remove_status", status: "inflammation", target: "target", stacks: "all" };
const toHand = (card: string): EffectOp => ({ op: "add_card", cardId: card, count: 1, dest: "hand" });

/** 수액: 속도가 곧 결정이다. 빠를수록 안정화는 크지만 체액 과다 위험 */
function fluidChoice(bonus: number): EffectOp {
  return choose("얼마나 빨리 줄까", [
    opt("cautious", "신중한 투여", `안정화 ${3 + bonus}, 질병 부담 4`, [stab(3 + bonus), dmg(4)], { risk: "효과가 작다" }),
    opt("standard", "표준 볼루스", `안정화 ${5 + bonus}, 질병 부담 7`, [stab(5 + bonus), dmg(7)]),
    opt("aggressive", "적극적 소생", `안정화 ${10 + bonus}, 질병 부담 12`, [stab(10 + bonus), dmg(12), toHand("fluid_overload")], {
      cost: 1,
      risk: "오더 +1 · 손에 체액 과다 · 심부전·ARDS면 크게 악화",
    }),
  ]);
}

/** 인슐린: 집중 주입은 빠르지만 저혈당·저칼륨을 부른다 */
function insulinChoice(bonus: number): EffectOp {
  return choose("얼마나 세게 줄까", [
    opt("standard", "표준 주입", `질병 부담 ${14 + bonus}, 고칼륨혈증 정리`, [dmg(14 + bonus), purge(["hyperkalemia"])]),
    opt("intensive", "집중 주입", `질병 부담 ${22 + bonus}, 고칼륨혈증 정리`, [dmg(22 + bonus), purge(["hyperkalemia"]), toHand("hypoglycemia")], {
      cost: 1,
      risk: "오더 +1 · 손에 저혈당",
    }),
  ]);
}

/** 에피네프린: 근육주사가 1차, 정맥 지속은 강하지만 부정맥 */
function epiChoice(bonus: number): EffectOp {
  return choose("어떤 경로로 줄까", [
    opt("im", "근육주사", `질병 부담 ${14 + bonus}, 안정화 4`, [dmg(14 + bonus), stab(4)]),
    opt("iv", "정맥 지속 주입", `질병 부담 ${20 + bonus}, 안정화 8`, [dmg(20 + bonus), stab(8), toHand("arrhythmia")], {
      cost: 1,
      risk: "오더 +1 · 손에 부정맥",
    }),
  ]);
}

/** 승압제: 증량하면 혈압은 오르지만 부정맥 위험 */
function pressorChoice(bonus: number): EffectOp {
  return choose("얼마나 올릴까", [
    opt("low", "저용량 시작", `안정화 ${6 + bonus}, 질병 부담 8`, [stab(6 + bonus), dmg(8)]),
    opt("titrate", "빠르게 증량", `안정화 ${12 + bonus}, 질병 부담 12`, [stab(12 + bonus), dmg(12), { op: "add_card", cardId: "arrhythmia", count: 1, dest: "draw_random" }], {
      cost: 1,
      risk: "오더 +1 · 대기 처방에 부정맥",
    }),
  ]);
}

export const DRUG_CARDS = [
  // ── 항생제 ──
  {
    id: "ceftriaxone",
    nameKo: "세프트리악손",
    nameEn: "ceftriaxone",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["abx", "beta_lactam", "cdi_risk"],
    effects: [dmg(11)],
    drug: { halfLife: 2, sideEffects: [{ card: "rash", count: 1, dest: "discard" }], spectrum: CRO },
    upgrade: { effects: [dmg(15)] },
    medical: { fidelity: "simplified", note: "3세대 세팔로스포린. 폐렴알균·대장균에 1차. 녹농균·혐기균·비정형균·MRSA는 덮지 못한다. 발진은 베타락탐 과민반응" },
  },
  {
    id: "pip_tazo",
    nameKo: "피페라실린-타조박탐",
    nameEn: "piperacillin-tazobactam",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["abx", "beta_lactam", "broad_spectrum", "cdi_risk"],
    effects: [dmg(16)],
    drug: { halfLife: 2, sideEffects: [{ card: "dysbiosis", count: 1, dest: "draw_random" }], spectrum: TZP },
    upgrade: { effects: [dmg(21)] },
    medical: { fidelity: "simplified", note: "항녹농균·혐기균 포함 광범위 베타락탐. ESBL 중증 감염에는 카바페넴이 낫다(MERINO)" },
  },
  {
    id: "meropenem",
    nameKo: "메로페넴",
    nameEn: "meropenem",
    kind: "drug",
    zone: "formulary",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    tags: ["abx", "carbapenem", "broad_spectrum", "cdi_risk"],
    effects: [dmg(20)],
    drug: { halfLife: 2, sideEffects: [{ card: "dysbiosis", count: 1, dest: "hand" }], spectrum: MEM },
    upgrade: { effects: [dmg(26)] },
    medical: { fidelity: "simplified", note: "카바페넴. ESBL에 1차. 남용하면 카바페넴 내성균을 부른다" },
  },
  {
    id: "vancomycin",
    nameKo: "반코마이신",
    nameEn: "vancomycin",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["abx", "glycopeptide", "nephrotoxic"],
    effects: [dmg(16)],
    drug: { halfLife: 3, sideEffects: [{ card: "nephrotoxicity", count: 1, dest: "draw_random" }], spectrum: VAN },
    upgrade: { effects: [dmg(21)] },
    medical: { fidelity: "simplified", note: "그람 양성, MRSA에 1차. 정맥 투여는 신독성, C. diff 치료는 경구 투여(카드는 경로 구분 생략). MSSA에는 베타락탐보다 못하다" },
  },
  {
    id: "gentamicin",
    nameKo: "겐타마이신",
    nameEn: "gentamicin",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["abx", "aminoglycoside", "nephrotoxic"],
    effects: [dmg(14)],
    drug: { halfLife: 2, sideEffects: [{ card: "nephrotoxicity", count: 1, dest: "discard" }], spectrum: GEN },
    upgrade: { effects: [dmg(18)] },
    medical: { fidelity: "simplified", note: "그람 음성 전용. 폐 조직 침투가 낮아 폐렴알균 폐렴에는 쓰지 않는다. 신독성·이독성" },
  },
  {
    id: "levofloxacin",
    nameKo: "레보플록사신",
    nameEn: "levofloxacin",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["abx", "fluoroquinolone", "qt_prolong", "cdi_risk"],
    effects: [dmg(12)],
    drug: { halfLife: 2, sideEffects: [{ card: "nausea", count: 1, dest: "discard" }], spectrum: LVX },
    upgrade: { effects: [dmg(16)] },
    medical: { fidelity: "simplified", note: "호흡기 퀴놀론. 비정형균 포함. QT 연장, 위장관 부작용, C. diff 위험" },
  },
  {
    id: "clarithromycin",
    nameKo: "클래리스로마이신",
    nameEn: "clarithromycin",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["abx", "macrolide", "qt_prolong", "cyp3a4_inhibitor"],
    effects: [dmg(12)],
    drug: { halfLife: 2, sideEffects: [{ card: "nausea", count: 1, dest: "discard" }], spectrum: CLR },
    upgrade: { effects: [dmg(16)] },
    medical: { fidelity: "simplified", note: "비정형균에 1차. 국내 폐렴알균의 마크롤라이드 내성률이 높다. 강한 CYP3A4 억제제, QT 연장" },
  },
  {
    id: "metronidazole",
    nameKo: "메트로니다졸",
    nameEn: "metronidazole",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["abx", "nitroimidazole"],
    effects: [dmg(12)],
    drug: { halfLife: 2, sideEffects: [{ card: "nausea", count: 1, dest: "discard" }], spectrum: MTZ },
    upgrade: { effects: [dmg(16)] },
    medical: { fidelity: "simplified", note: "혐기균과 C. diff. 복강 내 감염에는 그람 음성 약과 병용. 현재 C. diff 1차 약은 아니다" },
  },
  // ── 심혈관·혈액 ──
  {
    id: "heparin",
    nameKo: "헤파린",
    nameEn: "heparin",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["anticoagulant"],
    effects: [dmg(14)],
    drug: { halfLife: 2, sideEffects: [{ card: "bleeding", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(18)] },
    medical: { fidelity: "accurate", note: "정맥혈전·폐색전증·급성 관상동맥 증후군의 항응고. 출혈 위험" },
  },
  {
    id: "aspirin",
    nameKo: "아스피린",
    nameEn: "aspirin",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "enemy",
    tags: ["antiplatelet"],
    effects: [dmg(8)],
    drug: { halfLife: 3, sideEffects: [{ card: "bleeding", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(11)] },
    medical: { fidelity: "accurate", note: "동맥 혈전(급성 관상동맥 증후군, 뇌경색)에 쓴다. 정맥혈전 치료에는 쓰지 않는다" },
  },
  {
    id: "alteplase",
    nameKo: "알테플라제",
    nameEn: "alteplase (tPA)",
    kind: "drug",
    zone: "formulary",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    tags: ["thrombolytic"],
    effects: [dmg(28)],
    drug: { halfLife: 1, sideEffects: [{ card: "bleeding", count: 1, dest: "hand" }] },
    upgrade: { effects: [dmg(36)] },
    medical: { fidelity: "accurate", note: "뇌경색은 발병 4.5시간 이내, 고위험 폐색전증, PCI가 불가능한 STEMI. 출혈 질환에는 금기" },
  },
  {
    id: "metoprolol",
    nameKo: "메토프롤롤",
    nameEn: "metoprolol",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["beta_blocker"],
    effects: [dmg(10), stab(3)],
    drug: { halfLife: 3, sideEffects: [{ card: "bradycardia", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(13), stab(4)] },
    medical: { fidelity: "accurate", note: "심방세동 박동수 조절, 급성 관상동맥 증후군. 천식·아나필락시스·급성 심부전·쇼크·심장 눌림증에는 해롭다" },
  },
  {
    id: "amiodarone",
    nameKo: "아미오다론",
    nameEn: "amiodarone",
    kind: "drug",
    zone: "formulary",
    rarity: "rare",
    cost: 1,
    target: "enemy",
    tags: ["antiarrhythmic", "qt_prolong", "cyp3a4_inhibitor"],
    effects: [dmg(18), purge(["arrhythmia"])],
    drug: { halfLife: 4, sideEffects: [{ card: "lung_toxicity", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(24), purge(["arrhythmia"])] },
    medical: { fidelity: "simplified", note: "충격 불응성 심실세동, 심방세동 리듬 조절. 반감기가 매우 길어 폐·갑상선 독성이 오래 남는다" },
  },
  {
    id: "norepinephrine",
    nameKo: "노르에피네프린",
    nameEn: "norepinephrine",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["vasopressor"],
    effects: [pressorChoice(0)],
    drug: {
      halfLife: 2,
      sideEffects: [{ card: "arrhythmia", count: 1, dest: "draw_random" }],
      whileActive: [{ on: "turn_start", effects: [stab(3)] }],
    },
    upgrade: { effects: [pressorChoice(3)] },
    upgradeText: "모든 용량에서 안정화 +3",
    medical: { fidelity: "unverified", note: "v2.0에서 킥커 선택지·대가 카드가 붙음(v1.1 표시: accurate). 패혈성 쇼크의 1차 승압제. 빈맥성 부정맥" },
  },
  {
    id: "epinephrine",
    nameKo: "에피네프린",
    nameEn: "epinephrine",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["vasopressor", "anaphylaxis_tx"],
    effects: [epiChoice(0)],
    drug: { halfLife: 1, sideEffects: [{ card: "arrhythmia", count: 1, dest: "draw_random" }] },
    upgrade: { effects: [epiChoice(4)] },
    upgradeText: "모든 경로에서 질병 부담 감소 +4",
    medical: { fidelity: "unverified", note: "v2.0에서 킥커 선택지·대가 카드가 붙음(v1.1 표시: accurate). 아나필락시스 1차(근육주사), 심정지 소생. β차단제 복용자는 반응이 약하다" },
  },
  // ── 대사·신장 ──
  {
    id: "furosemide",
    nameKo: "푸로세미드",
    nameEn: "furosemide",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["loop_diuretic", "k_lowering"],
    effects: [dmg(12), purge(["hyperkalemia"], 1), purge(["fluid_overload"])],
    drug: { halfLife: 2, sideEffects: [{ card: "hypokalemia", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(16), purge(["hyperkalemia"], 1), purge(["fluid_overload"])] },
    medical: { fidelity: "unverified", note: "v2.0에서 킥커 선택지·대가 카드가 붙음(v1.1 표시: accurate). 체액 과다(심부전, ARDS의 보수적 수액 전략). 칼륨을 낮춘다. 급성 신손상의 회복을 돕지 않는다" },
  },
  {
    id: "insulin",
    nameKo: "인슐린",
    nameEn: "insulin (regular)",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["insulin", "k_lowering"],
    effects: [insulinChoice(0)],
    drug: { halfLife: 2, sideEffects: [{ card: "hypoglycemia", count: 1, dest: "draw_random" }] },
    upgrade: { effects: [insulinChoice(5)] },
    upgradeText: "모든 속도에서 질병 부담 감소 +5",
    medical: { fidelity: "unverified", note: "v2.0에서 킥커 선택지·대가 카드가 붙음(v1.1 표시: accurate). DKA의 핵심 치료. 칼륨을 세포 안으로 옮겨 혈청 칼륨을 낮춘다(고칼륨혈증 치료에도 쓴다)" },
  },
  {
    id: "kcl",
    nameKo: "염화칼륨",
    nameEn: "potassium chloride",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: ["k_raising", "electrolyte"],
    effects: [purge(["hypokalemia"]), stab(4)],
    drug: { halfLife: 2, sideEffects: [{ card: "hyperkalemia", count: 1, dest: "discard" }] },
    upgrade: { effects: [purge(["hypokalemia"]), stab(6)] },
    medical: { fidelity: "accurate", note: "저칼륨혈증 교정. 과하면 고칼륨혈증. 급성 신손상에는 금기에 가깝다" },
  },
  {
    id: "saline",
    nameKo: "생리식염수",
    nameEn: "normal saline",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["fluid"],
    effects: [fluidChoice(0)],
    drug: { halfLife: 2, sideEffects: [], whileActive: [{ on: "turn_start", effects: [stab(2)] }] },
    upgrade: { effects: [fluidChoice(3)] },
    upgradeText: "모든 속도에서 안정화 +3",
    medical: { fidelity: "unverified", note: "v2.0에서 킥커 선택지·대가 카드가 붙음(v1.1 표시: simplified). 순환 혈액량 부족에 쓴다. 심부전·ARDS에는 체액 과다를 악화시킨다" },
  },
  {
    id: "dextrose",
    nameKo: "포도당",
    nameEn: "dextrose",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: ["glucose"],
    effects: [purge(["hypoglycemia"]), stab(3)],
    drug: { halfLife: 2, sideEffects: [] },
    upgrade: { effects: [purge(["hypoglycemia"]), stab(5)] },
    medical: { fidelity: "accurate", note: "저혈당 교정. DKA에서 혈당이 떨어지면 인슐린을 계속 쓰기 위해 함께 준다" },
  },
  {
    id: "lactulose",
    nameKo: "락툴로오스",
    nameEn: "lactulose",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["ammonia_lowering"],
    effects: [dmg(14), purgeHandConfusion()],
    drug: { halfLife: 2, sideEffects: [{ card: "nausea", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(18), purgeHandConfusion()] },
    medical: { fidelity: "simplified", note: "간성뇌증 1차. 대표 부작용은 설사·복부 팽만이나 게임에서는 오심 카드로 대신한다" },
  },
  // ── 신경·진정 ──
  {
    id: "morphine",
    nameKo: "모르핀",
    nameEn: "morphine",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: ["opioid", "cns_depressant"],
    keywords: ["exhaust"],
    effects: [stab(10), { op: "heal", amount: 5, target: "patient" }],
    drug: { halfLife: 2, sideEffects: [{ card: "resp_depression", count: 1, dest: "draw_random" }] },
    upgrade: { effects: [stab(13), { op: "heal", amount: 7, target: "patient" }] },
    medical: { fidelity: "stylized", note: "통증 조절을 안정화와 활력 회복으로 표현했다. 호흡억제. 간성뇌증에는 해롭다" },
  },
  {
    id: "midazolam",
    nameKo: "미다졸람",
    nameEn: "midazolam",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: ["benzodiazepine", "cns_depressant", "cyp3a4_substrate"],
    effects: [{ op: "cost_modifier", filter: { kind: ["procedure"] }, delta: -1, uses: 1, scope: "turn" }, stab(3)],
    drug: { halfLife: 2, sideEffects: [{ card: "oversedation", count: 1, dest: "discard" }] },
    upgrade: { effects: [{ op: "cost_modifier", filter: { kind: ["procedure"] }, delta: -1, uses: 1, scope: "turn" }, stab(3), draw(1)] },
    medical: { fidelity: "simplified", note: "시술 진정. 섬망과 간성뇌증을 악화시킨다. CYP3A4 억제제와 함께 쓰면 진정이 길어진다" },
  },
  {
    id: "haloperidol",
    nameKo: "할로페리돌",
    nameEn: "haloperidol",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["antipsychotic", "qt_prolong"],
    effects: [dmg(14), purgeHandConfusion()],
    drug: { halfLife: 3, sideEffects: [{ card: "oversedation", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(18), purgeHandConfusion()] },
    medical: { fidelity: "simplified", note: "섬망의 초조 조절. 섬망 기간을 줄인다는 근거는 약하다. QT 연장" },
  },
  {
    id: "naloxone",
    nameKo: "날록손",
    nameEn: "naloxone",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: ["opioid_antagonist"],
    effects: [purge(["resp_depression"]), draw(1)],
    drug: { halfLife: 1, sideEffects: [] },
    upgrade: { effects: [purge(["resp_depression"]), draw(2)] },
    medical: { fidelity: "accurate", note: "오피오이드 호흡억제를 역전한다. 벤조디아제핀·항정신병제의 진정은 역전하지 않는다" },
  },
  {
    id: "ondansetron",
    nameKo: "온단세트론",
    nameEn: "ondansetron",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: ["antiemetic", "qt_prolong"],
    effects: [purge(["nausea"]), stab(3)],
    drug: { halfLife: 2, sideEffects: [] },
    upgrade: { effects: [purge(["nausea"]), stab(5)] },
    medical: { fidelity: "accurate", note: "5-HT3 길항 진토제. QT 연장" },
  },
  // ── 호흡·알레르기·위장관 ──
  {
    id: "methylprednisolone",
    nameKo: "메틸프레드니솔론",
    nameEn: "methylprednisolone",
    kind: "drug",
    zone: "formulary",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["corticosteroid", "immunosuppressive"],
    effects: [dmg(14), clearInflammation],
    drug: { halfLife: 3, sideEffects: [{ card: "immunosuppression", count: 1, dest: "draw_random" }] },
    upgrade: { effects: [dmg(18), clearInflammation] },
    medical: { fidelity: "simplified", note: "천식 악화의 1차 치료 중 하나, 불응성 패혈성 쇼크. 고혈당으로 DKA를 악화시킨다" },
  },
  {
    id: "salbutamol",
    nameKo: "살부타몰",
    nameEn: "salbutamol",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 0,
    target: "enemy",
    tags: ["beta2_agonist", "k_lowering"],
    effects: [dmg(6), purge(["hyperkalemia"], 1)],
    drug: { halfLife: 1, sideEffects: [{ card: "hypokalemia", count: 1, dest: "discard" }] },
    upgrade: { effects: [dmg(9), purge(["hyperkalemia"], 1)] },
    medical: { fidelity: "accurate", note: "기관지 확장제. 칼륨을 세포 안으로 옮긴다(고칼륨혈증 응급 치료에도 쓴다)" },
  },
  {
    id: "pantoprazole",
    nameKo: "판토프라졸",
    nameEn: "pantoprazole",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["ppi", "cdi_risk"],
    effects: [dmg(10), stab(4)],
    drug: { halfLife: 3, sideEffects: [] },
    upgrade: { effects: [dmg(13), stab(5)] },
    medical: { fidelity: "accurate", note: "소화성 궤양 출혈의 내시경 전후 치료. 장기 사용은 C. diff 위험을 높인다" },
  },
  {
    id: "acetaminophen",
    nameKo: "아세트아미노펜",
    nameEn: "acetaminophen",
    kind: "drug",
    zone: "formulary",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["analgesic"],
    effects: [stab(5), { op: "apply_status", status: "weak", stacks: 1, target: "target" }],
    drug: { halfLife: 2, sideEffects: [] },
    upgrade: { effects: [stab(7), { op: "apply_status", status: "weak", stacks: 2, target: "target" }] },
    medical: { fidelity: "simplified", note: "해열진통제는 증상을 누그러뜨릴 뿐 원인을 치료하지 않는다. 위축은 발열·통증 부담의 감소를 뜻한다" },
  },
] satisfies CardDef[];

function purgeHandConfusion(): EffectOp {
  return { op: "exhaust_cards", from: ["hand", "draw", "discard"], filter: { ids: ["confusion"] }, amount: 1 };
}

