import { clear, diag, dmg, draw, heal, iff, orders, purge, purgeHand, stab } from "../ops";
import type { CardDef } from "../../core/types";

export const PROCEDURE_CARDS = [
  // ── 일반 ──
  {
    id: "supportive_care",
    nameKo: "보존적 치료",
    nameEn: "Supportive care",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [dmg(8)],
    upgrade: { effects: [dmg(11)] },
    flavor: "환자가 스스로 회복할 시간을 번다.",
  },
  {
    id: "early_mobilization",
    nameKo: "조기 거동",
    nameEn: "Early mobilization",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [dmg(5), stab(4)],
    upgrade: { effects: [dmg(7), stab(6)] },
    flavor: "침대에 오래 누워 있을수록 잃는 것이 많다.",
  },
  {
    id: "reassessment",
    nameKo: "재평가",
    nameEn: "Reassessment",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [iff({ knowledgeAtLeast: { target: "target", level: 1 } }, [dmg(10)], [dmg(6)])],
    upgrade: { effects: [iff({ knowledgeAtLeast: { target: "target", level: 1 } }, [dmg(13)], [dmg(8)])] },
    flavor: "처음 인상이 틀렸을 수도 있다.",
  },
  {
    id: "oxygen",
    nameKo: "산소 투여",
    nameEn: "Oxygen therapy",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [stab(6), clear("hypoxia")],
    upgrade: { effects: [stab(9), clear("hypoxia")] },
    flavor: "비강 캐뉼라 4L.",
  },
  {
    id: "source_control",
    nameKo: "감염원 제거",
    nameEn: "Source control",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: ["source_control"],
    keywords: ["targeted"],
    effects: [dmg(11)],
    upgrade: { effects: [dmg(15)] },
    flavor: "고름은 빼고, 오염된 관은 뽑는다.",
  },
  {
    id: "direct_pressure",
    nameKo: "압박 지혈",
    nameEn: "Direct pressure",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [stab(6), clear("bleeding_tendency"), purgeHand(["bleeding"], 1)],
    upgrade: { effects: [stab(9), clear("bleeding_tendency"), purgeHand(["bleeding"], 1)] },
    flavor: "거즈와 손바닥, 그리고 10분.",
  },
  {
    id: "iv_access",
    nameKo: "정맥로 확보",
    nameEn: "IV access",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [{ op: "cost_modifier", filter: { kind: ["drug"] }, delta: -1, uses: 1, scope: "turn" }],
    upgrade: { effects: [{ op: "cost_modifier", filter: { kind: ["drug"] }, delta: -1, uses: 1, scope: "turn" }, draw(1)] },
    flavor: "18G 두 개.",
  },
  {
    id: "chart_review",
    nameKo: "차트 정리",
    nameEn: "Chart review",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [draw(2), { op: "select_cards", from: ["hand"], min: 1, max: 1, then: [{ op: "discard_selected" }], prompt: "버릴 카드 1장" }],
    upgrade: { effects: [draw(3), { op: "select_cards", from: ["hand"], min: 1, max: 1, then: [{ op: "discard_selected" }], prompt: "버릴 카드 1장" }] },
    flavor: "빠진 오더가 없는지.",
  },
  {
    id: "symptomatic",
    nameKo: "대증 치료",
    nameEn: "Symptomatic care",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [{ op: "select_cards", from: ["hand"], filter: { sideEffect: true }, min: 0, max: 1, then: [{ op: "exhaust_selected" }], prompt: "소진할 부작용 카드" }, draw(1)],
    upgrade: { effects: [{ op: "select_cards", from: ["hand"], filter: { sideEffect: true }, min: 0, max: 2, then: [{ op: "exhaust_selected" }], prompt: "소진할 부작용 카드" }, draw(1)] },
    flavor: "원인을 못 찾았어도 환자는 편해야 한다.",
  },
  {
    id: "monitoring",
    nameKo: "집중 모니터링",
    nameEn: "Close monitoring",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [stab(5), diag(1), { op: "reveal_intent", target: "target" }],
    upgrade: { effects: [stab(8), diag(1), { op: "reveal_intent", target: "target" }] },
    flavor: "활력 징후 1시간마다.",
  },
  {
    id: "med_reconciliation",
    nameKo: "처방 감사",
    nameEn: "Medication reconciliation",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [{ op: "end_drug", filter: { all: true } }, { op: "draw", amount: { min: [{ ref: "drugs_ended_now" }, 3] } }],
    upgrade: { cost: 0 },
    flavor: "이 약, 왜 들어가고 있지?",
  },
  // ── 고급 ──
  {
    id: "intensive_care",
    nameKo: "집중 치료",
    nameEn: "Intensive care",
    kind: "procedure",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    tags: [],
    effects: [dmg(18)],
    upgrade: { effects: [dmg(24)] },
    flavor: "간호사 한 명이 환자 두 명을 본다.",
  },
  {
    id: "defibrillation",
    nameKo: "제세동",
    nameEn: "Defibrillation",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["defib"],
    keywords: ["exhaust"],
    effects: [dmg(20)],
    upgrade: { effects: [dmg(26)] },
    flavor: "\"모두 물러나세요.\" 맥박이 있는 리듬에는 쓰지 않는다.",
  },
  {
    id: "central_line",
    nameKo: "중심정맥관 삽입",
    nameEn: "Central line",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    keywords: ["power"],
    effects: [{ op: "combat_flag", flag: "drugHalfLifeBonus", delta: 1 }, stab(4)],
    upgrade: { cost: 0 },
    flavor: "지속 주입이 가능해진다. 감염 위험도 함께.",
  },
  {
    id: "intubation",
    nameKo: "기관 삽관",
    nameEn: "Endotracheal intubation",
    kind: "procedure",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    tags: ["airway"],
    effects: [stab(12), clear("hypoxia"), dmg(10)],
    upgrade: { effects: [stab(16), clear("hypoxia"), dmg(14)] },
    flavor: "폐 보호 환기. 긴장성 기흉과 심장 눌림증에서는 양압이 독이 된다.",
  },
  {
    id: "chest_tube",
    nameKo: "흉관 삽입",
    nameEn: "Chest tube",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["chest_tube"],
    effects: [dmg(14), stab(4)],
    upgrade: { effects: [dmg(20), stab(4)] },
    flavor: "제5늑간, 중액와선.",
  },
  {
    id: "transfusion",
    nameKo: "수혈",
    nameEn: "Transfusion",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["transfusion"],
    keywords: ["exhaust"],
    effects: [dmg(12), heal(5)],
    upgrade: { effects: [dmg(12), heal(8)] },
    flavor: "혈액형과 교차 시험을 두 번 확인한다.",
  },
  {
    id: "consult",
    nameKo: "협진 의뢰",
    nameEn: "Consultation",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    keywords: ["exhaust"],
    effects: [{ op: "add_random_card", rarity: "uncommon", dest: "hand", costZeroThisTurn: true }],
    upgrade: { cost: 0 },
    flavor: "회신은 생각보다 빨리 왔다.",
  },
  {
    id: "handoff",
    nameKo: "인계",
    nameEn: "Handoff",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    effects: [{ op: "combat_flag", flag: "retainAll", delta: 1 }, draw(1)],
    upgrade: { cost: 0 },
    flavor: "다음 사람이 이어받을 수 있게.",
  },
  {
    id: "pericardiocentesis",
    nameKo: "심낭 천자",
    nameEn: "Pericardiocentesis",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: ["pericardiocentesis"],
    effects: [dmg(16), diag(2)],
    upgrade: { effects: [dmg(22), diag(2)] },
    flavor: "검상돌기 아래, 왼쪽 어깨를 향해.",
  },
  {
    id: "endoscopy",
    nameKo: "내시경 지혈술",
    nameEn: "Endoscopic hemostasis",
    kind: "procedure",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    tags: ["endoscopy"],
    effects: [dmg(18), purge(["bleeding"]), stab(6)],
    upgrade: { effects: [dmg(24), purge(["bleeding"]), stab(6)] },
    flavor: "클립 두 개, 에피네프린 국소 주사.",
  },
  // ── 희귀 ──
  {
    id: "dialysis",
    nameKo: "투석",
    nameEn: "Dialysis",
    kind: "procedure",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    tags: ["dialysis"],
    effects: [purge(["nephrotoxicity", "hyperkalemia"]), { op: "end_drug", filter: { all: true } }, stab(10), dmg(20)],
    upgrade: { cost: 1 },
    flavor: "고칼륨, 산증, 체액 과다, 요독. 투석 가능한 약은 함께 빠진다.",
  },
  {
    id: "rapid_response",
    nameKo: "신속대응팀 호출",
    nameEn: "Rapid response team",
    kind: "procedure",
    rarity: "rare",
    cost: 0,
    target: "none",
    tags: [],
    keywords: ["exhaust"],
    effects: [orders(1), draw(3)],
    upgrade: { effects: [orders(2), draw(3)] },
    flavor: "3분 안에 도착한다.",
  },
  {
    id: "order_set",
    nameKo: "오더 세트",
    nameEn: "Order set",
    kind: "procedure",
    rarity: "rare",
    cost: 1,
    target: "none",
    tags: [],
    effects: [{ op: "combat_flag", flag: "orderSetArmed", delta: 1 }],
    upgrade: { cost: 0 },
    flavor: "검증된 조합을 한 번에.",
  },
  {
    id: "revascularization",
    nameKo: "혈관 재개통술",
    nameEn: "Revascularization",
    kind: "procedure",
    rarity: "rare",
    cost: 2,
    target: "enemy",
    tags: ["revascularization"],
    effects: [dmg(24), stab(8)],
    upgrade: { effects: [dmg(32), stab(8)] },
    flavor: "관상동맥 중재술, 뇌혈관 혈전 제거술. 시간이 곧 조직이다.",
  },
] satisfies CardDef[];
