// 처치 카드. 앞부분은 처방 목록(행동 덱)의 행동, 뒷부분은 시술 목록(처방집)의 결정적 시술이다.
// 결정적 시술은 쓰면 "즉시 시행 / 확인 후 시행(+1) / 보류" 결정을 연다(core/choice.ts).
import { choose, clear, dmg, draw, heal, opt, orders, purge, purgeHand, stab } from "../ops";
import type { CardDef } from "../../core/types";

export const PROCEDURE_CARDS = [
  // ── 행동: 일반 ──
  {
    id: "oxygen",
    nameKo: "산소 투여",
    nameEn: "Oxygen therapy",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [stab(5), clear("hypoxia")],
    upgrade: { effects: [stab(8), clear("hypoxia")] },
    flavor: "비강 캐뉼라 4L.",
  },
  {
    id: "monitoring",
    nameKo: "집중 모니터링",
    nameEn: "Close monitoring",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [stab(5), { op: "reveal_intent", target: "target" }],
    upgrade: { effects: [stab(8), { op: "reveal_intent", target: "target" }] },
    flavor: "활력 징후 1시간마다. 무너지기 전에 알아챈다.",
  },
  {
    id: "direct_pressure",
    nameKo: "압박 지혈",
    nameEn: "Direct pressure",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [stab(6), clear("bleeding_tendency"), purgeHand(["bleeding"], 1)],
    upgrade: { effects: [stab(9), clear("bleeding_tendency"), purgeHand(["bleeding"], 1)] },
    flavor: "거즈와 손바닥, 그리고 10분.",
  },
  {
    id: "iv_access",
    nameKo: "정맥로 확보",
    nameEn: "IV access",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [{ op: "cost_modifier", filter: { kind: ["drug"] }, delta: -1, uses: 1, scope: "turn" }],
    upgrade: { effects: [{ op: "cost_modifier", filter: { kind: ["drug"] }, delta: -1, uses: 1, scope: "turn" }, draw(1)] },
    flavor: "18G 두 개.",
  },
  {
    id: "chart_review",
    nameKo: "차트 정리",
    nameEn: "Chart review",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [draw(2), { op: "select_cards", from: ["hand"], min: 1, max: 1, then: [{ op: "discard_selected" }], prompt: "버릴 카드 1장" }],
    upgrade: { effects: [draw(3), { op: "select_cards", from: ["hand"], min: 1, max: 1, then: [{ op: "discard_selected" }], prompt: "버릴 카드 1장" }] },
    flavor: "빠진 오더가 없는지.",
  },
  {
    id: "symptomatic",
    nameKo: "대증 치료",
    nameEn: "Symptomatic care",
    kind: "procedure",
    rarity: "common",
    cost: 0,
    target: "none",
    tags: [],
    effects: [{ op: "select_cards", from: ["hand"], filter: { sideEffect: true }, min: 0, max: 1, then: [{ op: "exhaust_selected" }], prompt: "소진할 부작용 카드" }, draw(1)],
    upgrade: { effects: [{ op: "select_cards", from: ["hand"], filter: { sideEffect: true }, min: 0, max: 2, then: [{ op: "exhaust_selected" }], prompt: "소진할 부작용 카드" }, draw(1)] },
    flavor: "원인을 못 찾았어도 환자는 편해야 한다.",
  },
  {
    id: "med_review",
    nameKo: "투약 검토",
    nameEn: "Medication review",
    kind: "procedure",
    rarity: "common",
    cost: 1,
    target: "none",
    tags: [],
    effects: [
      choose("투여 중인 약을 어떻게 정리할까", [
        opt("all", "전부 중단", "투여 중인 약을 모두 끊고, 끊은 수만큼 카드 (최대 3)", [{ op: "end_drug", filter: { all: true } }, { op: "draw", amount: { min: [{ ref: "drugs_ended_now" }, 3] } }], {
          requires: { activeDrugAny: true },
          requiresText: "투여 중인 약이 없다",
        }),
        opt("one", "하나만 중단", "상호작용·부작용의 원인 하나를 골라 끊는다. 카드 1장", [{ op: "stop_drug_choice" }], { requires: { activeDrugAny: true }, requiresText: "투여 중인 약이 없다" }),
        opt("deescalate", "범위 축소", "광범위 항생제 중단. 원인균을 알면 장내세균 교란 정리와 카드 1장", [{ op: "deescalate" }], {
          requires: { activeDrugBroad: true },
          requiresText: "광범위 항생제를 쓰고 있지 않다",
        }),
      ]),
    ],
    upgrade: { cost: 0 },
    upgradeText: "비용 0",
    flavor: "이 약, 왜 들어가고 있지?",
  },
  // ── 행동: 고급 ──
  {
    id: "consult",
    nameKo: "협진 의뢰",
    nameEn: "Consultation",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: [],
    keywords: ["exhaust"],
    effects: [{ op: "consult", count: 3 }],
    upgrade: { cost: 0 },
    upgradeText: "비용 0",
    flavor: "어느 과에 물을지 정하는 것부터가 판단이다.",
  },
  {
    id: "procedure_order",
    nameKo: "시술 의뢰",
    nameEn: "Procedure order",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [{ op: "discover", pool: "procedure", count: 3 }],
    upgrade: { cost: 0 },
    upgradeText: "비용 0",
    flavor: "시술실은 비어 있다. 근거는 충분한가?",
  },
  {
    id: "intensive_care",
    nameKo: "집중 치료",
    nameEn: "Intensive care",
    kind: "procedure",
    rarity: "uncommon",
    cost: 2,
    target: "enemy",
    tags: [],
    effects: [dmg(9), stab(9)],
    upgrade: { effects: [dmg(12), stab(12)] },
    flavor: "간호사 한 명이 환자 두 명을 본다.",
  },
  {
    id: "central_line",
    nameKo: "중심정맥관 삽입",
    nameEn: "Central line",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    keywords: ["power"],
    effects: [{ op: "combat_flag", flag: "drugHalfLifeBonus", delta: 1 }, stab(4)],
    upgrade: { cost: 0 },
    flavor: "지속 주입이 가능해진다. 감염 위험도 함께.",
  },
  {
    id: "handoff",
    nameKo: "인계",
    nameEn: "Handoff",
    kind: "procedure",
    rarity: "uncommon",
    cost: 1,
    target: "none",
    tags: [],
    effects: [{ op: "combat_flag", flag: "retainAll", delta: 1 }, draw(1)],
    upgrade: { cost: 0 },
    flavor: "다음 사람이 이어받을 수 있게.",
  },
  // ── 행동: 희귀 ──
  {
    id: "rapid_response",
    nameKo: "신속대응팀 호출",
    nameEn: "Rapid response team",
    kind: "procedure",
    rarity: "rare",
    cost: 0,
    target: "none",
    tags: [],
    keywords: ["exhaust"],
    effects: [orders(1), draw(3)],
    upgrade: { effects: [orders(2), draw(3)] },
    flavor: "3분 안에 도착한다.",
  },
  {
    id: "order_set",
    nameKo: "오더 세트",
    nameEn: "Order set",
    kind: "procedure",
    rarity: "rare",
    cost: 1,
    target: "none",
    tags: [],
    effects: [{ op: "combat_flag", flag: "orderSetArmed", delta: 1 }],
    upgrade: { cost: 0 },
    flavor: "검증된 조합을 한 번에.",
  },
  // ── 시술 목록 (처방집) ──
  {
    id: "source_control",
    nameKo: "감염원 제거",
    nameEn: "Source control",
    kind: "procedure",
    rarity: "common",
    zone: "formulary",
    procedure: { confirm: "ct" },
    cost: 1,
    target: "enemy",
    tags: ["source_control"],
    effects: [dmg(12)],
    upgrade: { effects: [dmg(16)] },
    flavor: "고름은 빼고, 오염된 관은 뽑고, 염증난 충수는 뗀다.",
  },
  {
    id: "defibrillation",
    nameKo: "제세동",
    nameEn: "Defibrillation / cardioversion",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "ecg" },
    cost: 1,
    target: "enemy",
    tags: ["defib"],
    keywords: ["exhaust"],
    effects: [dmg(20)],
    upgrade: { effects: [dmg(26)] },
    flavor: "\"모두 물러나세요.\" 맥박이 있는 리듬에는 쓰지 않는다.",
  },
  {
    id: "intubation",
    nameKo: "기관 삽관",
    nameEn: "Endotracheal intubation",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "abga" },
    cost: 2,
    target: "enemy",
    tags: ["airway"],
    effects: [stab(12), clear("hypoxia"), dmg(8)],
    upgrade: { effects: [stab(16), clear("hypoxia"), dmg(12)] },
    flavor: "폐 보호 환기. 긴장성 기흉과 심장 눌림증에서는 양압이 독이 된다.",
  },
  {
    id: "chest_tube",
    nameKo: "흉관 삽입",
    nameEn: "Chest tube",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "pocus" },
    cost: 1,
    target: "enemy",
    tags: ["chest_tube"],
    effects: [dmg(16), stab(4)],
    upgrade: { effects: [dmg(22), stab(4)] },
    flavor: "제5늑간, 중액와선. 긴장성 기흉은 영상을 기다리지 않는다.",
  },
  {
    id: "transfusion",
    nameKo: "수혈",
    nameEn: "Transfusion",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "lab_cbc" },
    cost: 1,
    target: "enemy",
    tags: ["transfusion"],
    keywords: ["exhaust"],
    effects: [dmg(12), heal(5)],
    upgrade: { effects: [dmg(12), heal(8)] },
    flavor: "혈액형과 교차 시험을 두 번 확인한다.",
  },
  {
    id: "pericardiocentesis",
    nameKo: "심낭 천자",
    nameEn: "Pericardiocentesis",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "pocus" },
    cost: 1,
    target: "enemy",
    tags: ["pericardiocentesis"],
    effects: [dmg(18)],
    upgrade: { effects: [dmg(24)] },
    flavor: "검상돌기 아래, 왼쪽 어깨를 향해. 초음파로 보고 찌른다.",
  },
  {
    id: "endoscopy",
    nameKo: "내시경 지혈술",
    nameEn: "Endoscopic hemostasis",
    kind: "procedure",
    rarity: "uncommon",
    zone: "formulary",
    procedure: { confirm: "lab_cbc" },
    cost: 2,
    target: "enemy",
    tags: ["endoscopy"],
    effects: [dmg(18), purge(["bleeding"]), stab(6)],
    upgrade: { effects: [dmg(24), purge(["bleeding"]), stab(6)] },
    flavor: "클립 두 개, 에피네프린 국소 주사.",
  },
  {
    id: "dialysis",
    nameKo: "투석",
    nameEn: "Dialysis",
    kind: "procedure",
    rarity: "rare",
    zone: "formulary",
    procedure: { confirm: "lab_chem" },
    cost: 2,
    target: "enemy",
    tags: ["dialysis"],
    effects: [purge(["nephrotoxicity", "hyperkalemia", "fluid_overload"]), { op: "end_drug", filter: { all: true } }, stab(10), dmg(20)],
    upgrade: { cost: 1 },
    upgradeText: "비용 1",
    flavor: "고칼륨, 산증, 체액 과다, 요독. 투석되는 약은 함께 빠진다.",
  },
  {
    id: "revascularization",
    nameKo: "혈관 재개통술",
    nameEn: "Revascularization",
    kind: "procedure",
    rarity: "rare",
    zone: "formulary",
    procedure: { confirm: "ecg" },
    cost: 2,
    target: "enemy",
    tags: ["revascularization"],
    effects: [dmg(24), stab(8)],
    upgrade: { effects: [dmg(32), stab(8)] },
    flavor: "관상동맥 중재술, 뇌혈관 혈전 제거술. 시간이 곧 조직이다.",
  },
] satisfies CardDef[];
