import type { CardDef } from "../../core/types";

const lose = (n: number) => ({ op: "lose_vitality" as const, amount: n });

export const SIDE_EFFECT_CARDS = [
  {
    id: "nausea",
    nameKo: "오심",
    nameEn: "Nausea",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 3, behavior: [], purgeCost: 1 },
    upgrade: {},
    medical: { fidelity: "accurate", note: "퀴놀론·마크롤라이드·메트로니다졸의 흔한 위장관 부작용" },
  },
  {
    id: "rash",
    nameKo: "발진",
    nameEn: "Rash",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    keywords: ["ethereal"],
    effects: [],
    sideEffect: { harm: 2, behavior: [] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "베타락탐 과민반응의 대표 형태" },
  },
  {
    id: "nephrotoxicity",
    nameKo: "신독성",
    nameEn: "Nephrotoxicity",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 5, behavior: [{ on: "turn_end", effects: [lose(2)] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "반코마이신·아미노글리코사이드. 병용하면 위험이 커진다" },
  },
  {
    id: "hypokalemia",
    nameKo: "저칼륨혈증",
    nameEn: "Hypokalemia",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: {
      harm: 4,
      behavior: [{ on: "drug_administered", condition: { eventDrugTag: "qt_prolong" }, effects: [{ op: "add_card", cardId: "arrhythmia", count: 1, dest: "hand" }] }],
    },
    upgrade: {},
    medical: { fidelity: "accurate", note: "고리 이뇨제·인슐린·β2 작용제. 저칼륨혈증은 QT 연장 약물의 부정맥 위험을 키운다" },
  },
  {
    id: "hyperkalemia",
    nameKo: "고칼륨혈증",
    nameEn: "Hyperkalemia",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 6, behavior: [{ on: "turn_end", effects: [lose(3)] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "칼륨 보충, 급성 신손상. 인슐린·β2 작용제·이뇨제·투석으로 낮춘다" },
  },
  {
    id: "hypoglycemia",
    nameKo: "저혈당",
    nameEn: "Hypoglycemia",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    keywords: ["ethereal"],
    effects: [],
    sideEffect: { harm: 6, behavior: [{ on: "card_drawn", effects: [lose(3)] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "인슐린 과다. 포도당으로 교정" },
  },
  {
    id: "resp_depression",
    nameKo: "호흡억제",
    nameEn: "Respiratory depression",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 8, behavior: [{ on: "card_drawn", effects: [{ op: "gain_orders", amount: -1 }] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "오피오이드, 특히 벤조디아제핀 병용. 날록손으로 역전" },
  },
  {
    id: "oversedation",
    nameKo: "과진정",
    nameEn: "Oversedation",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 5, behavior: [{ on: "turn_end", effects: [{ op: "custom", id: "draw_penalty", params: { n: 1 } }] }] },
    upgrade: {},
    medical: { fidelity: "simplified", note: "벤조디아제핀·항정신병제. 날록손으로 역전되지 않는다" },
  },
  {
    id: "arrhythmia",
    nameKo: "부정맥",
    nameEn: "Arrhythmia",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 8, behavior: [{ on: "turn_end", effects: [lose(4)] }], purgeCost: 2 },
    upgrade: {},
    medical: { fidelity: "accurate", note: "승압제의 빈맥성 부정맥, QT 연장 약물 병용의 다형성 심실빈맥" },
  },
  {
    id: "bleeding",
    nameKo: "출혈",
    nameEn: "Bleeding",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 5, behavior: [{ on: "turn_end", effects: [lose(2)] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "항응고제·항혈소판제·혈전용해제, DIC" },
  },
  {
    id: "confusion",
    nameKo: "착란",
    nameEn: "Confusion",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 4, behavior: [{ on: "card_drawn", effects: [{ op: "custom", id: "random_discard" }] }] },
    upgrade: {},
    medical: { fidelity: "simplified", note: "간성뇌증·섬망의 인지 저하" },
  },
  {
    id: "dysbiosis",
    nameKo: "장내세균 교란",
    nameEn: "Dysbiosis",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 4, behavior: [], passive: "abx_cost_up" },
    upgrade: {},
    medical: { fidelity: "stylized", note: "광범위 항생제가 정상 세균총을 무너뜨린다. 항생제 비용 증가는 게임적 표현" },
  },
  {
    id: "immunosuppression",
    nameKo: "면역억제",
    nameEn: "Immunosuppression",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 4, behavior: [], passive: "infection_attack_up" },
    upgrade: {},
    medical: { fidelity: "simplified", note: "스테로이드는 감염에 대한 방어를 약하게 한다" },
  },
  {
    id: "bradycardia",
    nameKo: "서맥",
    nameEn: "Bradycardia",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    keywords: ["ethereal"],
    effects: [],
    sideEffect: { harm: 4, behavior: [{ on: "turn_end", effects: [lose(2)] }] },
    upgrade: {},
    medical: { fidelity: "accurate", note: "β차단제의 대표 부작용" },
  },
  {
    id: "lung_toxicity",
    nameKo: "폐 독성",
    nameEn: "Pulmonary toxicity",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 3, persistent: true, behavior: [{ on: "turn_end", effects: [lose(1)] }], purgeCost: 1 },
    upgrade: {},
    medical: { fidelity: "simplified", note: "아미오다론의 장기 독성. 반감기가 몇 주에 이르러 오래 남는다" },
  },
  {
    id: "obsolete_card",
    nameKo: "폐기된 카드",
    nameEn: "Obsolete card",
    kind: "side_effect",
    rarity: "special",
    cost: "unplayable",
    target: "none",
    tags: [],
    effects: [],
    sideEffect: { harm: 0, behavior: [] },
    upgrade: {},
    medical: { fidelity: "stylized", note: "저장 파일의 카드가 사라졌을 때의 대체 카드" },
  },
] satisfies CardDef[];
