import { diag, dmg, draw, stab, status } from "../ops";
import type { CardDef } from "../../core/types";

export const STARTER_CARDS = [
  {
    id: "first_aid",
    nameKo: "응급 처치",
    nameEn: "First aid",
    kind: "procedure",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    tags: [],
    effects: [dmg(6)],
    upgrade: { effects: [dmg(9)] },
    flavor: "일단 할 수 있는 것부터.",
  },
  {
    id: "stabilize",
    nameKo: "안정화 조치",
    nameEn: "Stabilize",
    kind: "procedure",
    rarity: "starter",
    cost: 1,
    target: "none",
    tags: [],
    effects: [stab(5)],
    upgrade: { effects: [stab(8)] },
    flavor: "기도, 호흡, 순환.",
  },
  {
    id: "history",
    nameKo: "병력 청취",
    nameEn: "History taking",
    kind: "diagnostic",
    rarity: "starter",
    cost: 0,
    target: "enemy",
    tags: [],
    effects: [diag(1), draw(1)],
    upgrade: { effects: [diag(2), draw(1)] },
    flavor: "진단의 절반은 이야기에 있다.",
  },
  {
    id: "acetaminophen",
    nameKo: "아세트아미노펜",
    nameEn: "acetaminophen",
    kind: "drug",
    rarity: "starter",
    cost: 1,
    target: "enemy",
    tags: ["analgesic"],
    effects: [stab(5), status("weak", 1)],
    drug: { halfLife: 2, sideEffects: [] },
    upgrade: { effects: [stab(7), status("weak", 2)] },
    medical: { fidelity: "simplified", note: "해열진통제는 증상을 누그러뜨릴 뿐 원인을 치료하지 않는다. 위축은 발열·통증 부담의 감소를 뜻한다" },
  },
] satisfies CardDef[];
