// 검사 경로와 소견 목록. 소견은 여러 질병이 함께 쓴다. 같은 소견을 공유할수록 그 경로의 감별력은 떨어진다.
// weight: 0 정상 · 1 비특이 · 2 특징적 · 4 결정적 (core/evidence.ts의 채점 규칙 참고)
// v2.1: 병력(발병 양상·동반 증상·위험 인자)은 암시일 뿐이라 최대 1. 가중치 4는 비싸거나 시간이 걸리는 경로(CT, 배양 결과)에만 둔다. 활력·병력·진찰·혈액·현장 검사·X선·현장 초음파는 최대 2.
// 값싼 검사 하나가 다른 가설을 모두 배제하던 문제(반대 근거 4 = 배제)를 막는다. 배제에는 소견이 둘 이상 필요하다.
import type { ChannelDef, FindingDef } from "../core/types";

export const CHANNELS = [
  { id: "vitals", nameKo: "활력 징후", group: "vitals", normal: "vt_stable" },
  { id: "hx_onset", nameKo: "발병 양상과 경과", group: "history", normal: "on_nonspecific" },
  { id: "hx_assoc", nameKo: "동반 증상", group: "history", normal: "as_none" },
  { id: "hx_risk", nameKo: "병력·약물·위험 인자", group: "history", normal: "rk_none" },
  { id: "ex_cardio", nameKo: "심폐 진찰", group: "exam", normal: "cd_normal" },
  { id: "ex_abd", nameKo: "복부 진찰", group: "exam", normal: "ab_soft" },
  { id: "ex_neuro", nameKo: "신경학적 진찰", group: "exam", normal: "nr_normal" },
  { id: "ex_limb", nameKo: "피부·사지 진찰", group: "exam", normal: "lb_normal" },
  { id: "lab_cbc", nameKo: "혈구·염증 검사", group: "lab", normal: "cbc_normal" },
  { id: "lab_chem", nameKo: "화학·대사 검사", group: "lab", normal: "chem_normal" },
  { id: "lab_coag", nameKo: "응고 검사", group: "lab", normal: "coag_normal" },
  { id: "lab_ua", nameKo: "소변 검사", group: "bedside", normal: "ua_normal" },
  { id: "ecg", nameKo: "심전도", group: "bedside", normal: "ecg_sinus" },
  { id: "abga", nameKo: "동맥혈 가스", group: "bedside", normal: "abga_normal" },
  { id: "stool", nameKo: "대변 검사", group: "bedside", normal: "stool_normal" },
  { id: "xray", nameKo: "X선", group: "imaging", normal: "xr_normal" },
  { id: "pocus", nameKo: "현장 초음파", group: "imaging", normal: "us_normal" },
  { id: "ct", nameKo: "CT", group: "imaging", normal: "ct_normal" },
  { id: "cx_blood", nameKo: "혈액 배양", group: "micro", normal: "cx_neg" },
  { id: "cx_urine", nameKo: "소변 배양", group: "micro", normal: "cx_neg" },
  { id: "cx_sputum", nameKo: "객담 배양", group: "micro", normal: "cx_neg" },
  { id: "cx_wound", nameKo: "상처·삽입부 배양", group: "micro", normal: "cx_neg" },
  { id: "gs_blood", nameKo: "혈액 그람 염색", group: "micro", normal: "gs_none", gramOf: "cx_blood" },
  { id: "gs_urine", nameKo: "소변 그람 염색", group: "micro", normal: "gs_none", gramOf: "cx_urine" },
  { id: "gs_sputum", nameKo: "객담 그람 염색", group: "micro", normal: "gs_none", gramOf: "cx_sputum" },
  { id: "gs_wound", nameKo: "상처 그람 염색", group: "micro", normal: "gs_none", gramOf: "cx_wound" },
  // 경과 관찰: 검사로 고르는 경로가 아니다. 질병의 행동이 일어난 뒤에만 소견이 생긴다 (v2.1)
  { id: "course", nameKo: "경과 관찰", group: "course", normal: "crs_none" },
] satisfies ChannelDef[];

const f = (id: string, text: string, weight: 0 | 1 | 2 | 4, extra: Partial<FindingDef> = {}): FindingDef => ({ id, text, weight, ...extra });

export const FINDINGS: FindingDef[] = [
  // ── 활력 징후 ──
  f("vt_stable", "혈압·맥박 안정, 열 없음", 0),
  f("vt_fever_tachy", "38.3℃, 맥박 106", 1),
  f("vt_lowgrade", "37.6℃, 맥박 92", 1),
  f("vt_tachy_distress", "맥박 112, 식은땀, SpO₂ 93%", 1),
  f("vt_icu_fever", "38.9℃, 맥박 118", 1),
  f("vt_icu_hypox", "38.2℃, 고농도 산소에도 SpO₂ 86%", 1),
  f("vt_high_fever", "39.4℃, 오한, 맥박 116", 1),
  f("vt_dry_tachy", "열 없음, 맥박 112, 입술이 바짝 마름", 1),
  f("vt_fever_hypox", "38.7℃, 호흡수 26, SpO₂ 92%", 1),
  f("vt_tachypnea_hypox", "열 없음, 호흡수 28, SpO₂ 91%", 1),
  f("vt_shock", "혈압 82/50, 맥박 124, 얼굴이 붉음", 2),
  f("vt_diaphoretic", "식은땀, 혈압 104/70, 맥박 98", 1),
  f("vt_hypertensive", "혈압 178/96, 맥박 84", 1),
  f("vt_kussmaul", "깊고 빠른 호흡, 맥박 118, 입이 마름", 2),
  f("vt_hypertensive_hypox", "혈압 168/94, 호흡수 28, SpO₂ 89%", 1),
  f("vt_calm_confused", "활력 징후 안정, 대화가 자꾸 엇나감", 1),
  f("vt_irregular_tachy", "불규칙한 맥박 140, 혈압 108/70", 2),
  f("vt_tachy_hypox", "맥박 118, SpO₂ 88%, 열 없음", 1),
  f("vt_hematemesis", "혈압 86/54, 맥박 124, 선홍색 피를 토함", 2),
  f("vt_vent_fever", "38.9℃, 인공호흡기 산소 요구량 증가", 1),
  f("vt_oliguric", "혈압 138/82, 시간당 소변 7mL", 1),
  f("vt_severe_hypox", "고농도 산소에도 SpO₂ 85%", 2),
  f("vt_bleeding", "혈압 96/60, 맥박 112, 주사 자리에서 피가 샘", 2),
  f("vt_obstructive", "혈압 78/60, 맥박 132, 목정맥이 불룩함", 2),
  f("vt_septic", "39.6℃, 맥박 128, 혈압 88/52", 2),
  // v2.1: 감별 대상이 여럿인 내원 양상이 함께 쓰는 활력 징후 (채점하지 않는다)
  f("vt_dyspneic", "호흡수 28, SpO₂ 91%, 맥박 112", 1),
  f("vt_ward_hypox", "호흡수 26, 산소 2L에도 SpO₂ 89%, 맥박 110", 1),
  f("vt_vent_crash", "인공호흡기 고압 경보, SpO₂ 82%, 맥박 130", 1),
  // ── 발병 양상 ──
  f("on_nonspecific", "경과에 뚜렷한 특징이 없다", 0),
  f("on_migrating", "명치 통증이 몇 시간 뒤 오른쪽 아래로 옮겨 감", 1),
  f("on_acute", "몇 시간 사이에 시작해 빨리 심해짐", 1),
  f("on_days", "2~3일에 걸쳐 서서히 나빠짐", 1),
  f("on_minutes_exposure", "주사를 맞고 몇 분 만에 시작", 1),
  f("on_episodic", "감기 뒤 며칠째 반복되는 발작성 숨참", 1),
  f("on_sudden", "갑자기, 순간적으로 시작", 1),
  f("on_crushing", "30분 넘게 이어지는 쥐어짜는 가슴 통증", 1),
  f("on_polyuria", "며칠째 물을 많이 마시고 소변을 자주 봄", 1),
  f("on_nocturnal", "밤이 되면 심해지고 낮에는 나아짐", 1),
  f("on_somnolence", "며칠째 점점 졸리고 엉뚱해짐", 1),
  f("on_orthopnea", "며칠째 누우면 숨이 차 앉아서 잠", 1),
  f("on_oliguria", "하루 사이 소변량이 점점 줄어듦", 1),
  f("on_hours", "몇 시간 사이 혈압이 조금씩 떨어짐", 1),
  // ── 동반 증상 ──
  f("as_none", "특별한 동반 증상은 없다", 0),
  f("as_gi_upset", "식욕이 없고 속이 메스꺼움", 1),
  f("as_vomit_diarrhea", "잦은 구토와 물설사", 1),
  f("as_watery_cramp", "하루 여덟 번 물설사, 아랫배를 쥐어짜는 통증", 1),
  f("as_urinary", "배뇨통과 빈뇨, 옆구리 통증", 1),
  f("as_productive_cough", "누런 가래 기침, 숨쉴 때 찌르는 옆구리 통증", 1),
  f("as_dry_cough", "마른기침, 두통과 근육통", 1),
  f("as_wheeze_cough", "숨쉴 때 쌕쌕거림과 마른기침", 1),
  f("as_itch_throat", "온몸이 가렵고 목이 조이는 느낌", 1),
  f("as_radiating_sweat", "왼팔로 뻗치는 통증, 식은땀과 구역", 1),
  f("as_pleuritic", "숨 쉴 때 찌르는 가슴 통증, 피 섞인 가래", 1),
  f("as_speech", "말이 어눌하고 한쪽 얼굴이 처짐", 1),
  f("as_thirst_vomit", "심한 갈증, 구토와 배 아픔", 1),
  f("as_leg_ache", "종아리가 당기고 무겁다", 1),
  f("as_leg_hot", "다리가 화끈거리고 오한이 난다", 1),
  f("as_edema_weight", "다리가 붓고 며칠 새 체중이 늘었다", 1),
  f("as_palpitations", "심장이 불규칙하게 두근거림", 1),
  f("as_agitation", "수액줄을 뽑으려 하고 헛것을 봄", 1),
  f("as_constipation", "사흘째 변을 보지 못함", 1),
  f("as_bleeding_sites", "주사 자리와 잇몸에서 피가 멎지 않음", 1),
  f("as_melena", "짜장면 같은 검은 변", 1),
  f("as_vomit_back", "구토, 등으로 뻗치는 명치 통증", 1),
  f("as_sputum_purulent", "기관 튜브로 누런 가래가 늘어남", 1),
  f("as_chills_line", "라인으로 수액을 넣을 때마다 오한", 1),
  // ── 병력·위험 인자 ──
  f("rk_none", "특별한 위험 인자는 없다", 0),
  f("rk_sick_contacts", "함께 식사한 가족도 같은 증상", 1),
  f("rk_uti_history", "방광염을 자주 앓았다", 1),
  f("rk_recent_hosp_abx", "최근 입원했고 항생제를 오래 썼다", 1),
  f("rk_inhaler", "흡입기를 하루 여섯 번 씀, 천식으로 입원한 적 있음", 1),
  f("rk_drug_allergy", "예전에 약물 알레르기가 있었다", 1),
  f("rk_vascular", "당뇨 20년, 고혈압, 흡연", 1),
  f("rk_immobile_postop", "수술 후 며칠째 침상 안정 중", 1),
  f("rk_insulin_missed", "며칠째 인슐린을 거름", 1),
  f("rk_iv_site", "그쪽에 정맥주사를 맞은 자리가 있다", 1),
  f("rk_heart_failure", "심부전 병력, 어제 수액 2L를 맞음", 1),
  f("rk_cirrhosis", "간경변 병력", 1),
  f("rk_elderly_sedative", "82세, 입원 사흘째, 어젯밤 수면제를 먹음", 1),
  f("rk_abx_course", "항생제를 쓴 지 7일째", 1),
  f("rk_cardiac_surgery", "심장 수술 후 며칠째", 1),
  f("rk_alcohol", "어제 과음을 했다", 1),
  f("rk_nsaid", "한 달째 진통제(NSAID)를 먹음", 1),
  f("rk_icu_devices", "인공호흡기와 중심정맥관을 달고 있다", 1),
  f("rk_nephrotoxins", "반코마이신과 조영제에 노출됨", 1),
  f("rk_sepsis_source", "며칠 전부터 폐렴·패혈증 치료 중", 1),
  // ── 심폐 진찰 ──
  f("cd_normal", "호흡음과 심음 정상", 0),
  f("cd_crackles_focal", "한쪽 폐 아래에 수포음", 2),
  f("cd_crackles_scattered", "양쪽에 흩어진 가는 수포음", 1),
  f("cd_wheeze", "숨을 내쉴 때 양쪽 천명음", 2),
  f("cd_bibasal_jvd", "양쪽 폐 아래 수포음, 목정맥 팽창, 제3심음", 2),
  f("cd_diffuse_crackles", "양쪽 폐 전체 수포음, 목정맥은 정상", 2),
  f("cd_irregular", "불규칙하게 불규칙한 심음", 2),
  f("cd_muffled_jvd", "심음이 작게 들리고 목정맥이 불룩함", 2),
  f("cd_absent_breath", "한쪽 호흡음 소실, 기관이 반대쪽으로 밀림", 2),
  f("cd_tachy_clear", "빠른 심박, 폐는 깨끗하게 들림", 1),
  // ── 복부 진찰 ──
  f("ab_soft", "부드럽고 압통 없는 배", 0),
  f("ab_rlq_peritonism", "우하복부 압통과 반발통", 2),
  f("ab_diffuse_mild", "배 전체에 가벼운 압통, 반발통 없음", 1),
  f("ab_flank_cva", "옆구리(늑척추각) 두드림 통증", 2),
  f("ab_epigastric_guarding", "명치 압통과 근육 긴장", 2),
  f("ab_epigastric_mild", "명치에 가벼운 압통", 1),
  f("ab_lower_cramping", "아랫배 압통, 장음이 잦음", 1),
  f("ab_ascites", "복수로 불러 있는 배", 2),
  // ── 신경학적 진찰 ──
  f("nr_normal", "의식 명료, 국소 신경학적 결손 없음", 0),
  f("nr_hemiparesis", "왼쪽 팔다리 마비와 오른쪽 시선 편위", 2),
  f("nr_asterixis", "손을 펴면 퍼덕떨림(asterixis)", 2),
  f("nr_inattention", "주의력 저하, 의식 수준이 오락가락", 2),
  f("nr_drowsy", "졸려 하나 깨우면 대답함", 1),
  // ── 피부·사지 ──
  f("lb_normal", "피부와 사지 이상 없음", 0),
  f("lb_urticaria", "전신 두드러기, 입술과 혀가 부음", 2),
  f("lb_dry", "피부 탄력 저하, 모세혈관 재충전 지연", 1),
  f("lb_unilateral_calf", "한쪽 종아리만 붓고 둘레 3cm 차이, 열감 없음", 2),
  f("lb_spreading_erythema", "경계가 불분명하게 번지는 발적과 열감", 2),
  f("lb_bilateral_pitting", "양쪽 다리 함요부종", 1),
  f("lb_petechiae", "온몸의 점상출혈, 주사 자리 출혈", 2),
  f("lb_line_erythema", "중심정맥관 삽입부 발적과 고름", 2),
  f("lb_mottled", "얼룩덜룩한 피부, 모세혈관 재충전 지연", 2),
  f("lb_jaundice", "황달과 거미혈관종", 2),
  f("lb_cold_clammy", "차갑고 축축한 손발", 1),
  f("lb_subcut_emphysema", "가슴 피부 밑에서 눈 밟는 소리(피하 기종)", 2),
  // ── 혈구·염증 ──
  f("cbc_normal", "혈구·염증 수치 정상", 0),
  f("cbc_leukocytosis", "백혈구 증가, CRP 상승", 1),
  f("cbc_marked_leuko", "백혈구 18,000 이상, CRP 크게 상승", 2),
  f("cbc_anemia_acute", "혈색소 7.2로 급감", 2),
  f("cbc_thrombocytopenia", "혈소판 32,000", 2),
  f("cbc_low_platelet", "혈소판 약간 감소(간경변)", 1),
  f("cbc_sepsis", "백혈구 감소와 미성숙 호중구, 젖산 상승", 2),
  // ── 화학·대사 ──
  f("chem_normal", "혈당·전해질·신기능 정상", 0),
  f("chem_prerenal", "요소질소·크레아티닌 약간 상승(탈수)", 1),
  f("chem_dka", "혈당 486, 혈중 케톤 상승, 음이온차 증가", 2),
  f("chem_troponin_high", "트로포닌 크게 상승", 2),
  f("chem_troponin_mild", "트로포닌 약간 상승, BNP 상승", 1),
  f("chem_bnp_high", "BNP 크게 상승", 2),
  f("chem_lipase_high", "리파아제 정상 상한의 6배", 2),
  f("chem_ammonia_high", "암모니아 상승, 간 수치 이상", 2),
  f("chem_aki", "크레아티닌 0.9 → 2.8, 칼륨 5.9", 2),
  f("chem_bun_high", "요소질소만 크게 상승(위장관 출혈)", 1),
  f("chem_lactate_aki", "젖산 4.1, 크레아티닌 상승", 2),
  // ── 응고 ──
  f("coag_normal", "응고 검사 정상", 0),
  f("coag_ddimer_high", "D-dimer 크게 상승", 2),
  f("coag_dic", "PT 연장, 피브리노겐 저하, D-dimer 상승", 2),
  f("coag_prolonged_pt", "PT 연장(간 합성 기능 저하)", 1),
  // ── 소변 ──
  f("ua_normal", "소변 검사 정상", 0),
  f("ua_pyuria", "농뇨, 아질산염 양성", 2),
  f("ua_concentrated", "진한 소변(비중 상승)", 1),
  f("ua_glucose_ketones", "소변 포도당 4+, 케톤 3+", 2),
  f("ua_muddy_casts", "갈색 과립 원주(급성 세뇨관 괴사)", 2),
  // ── 심전도 ──
  f("ecg_sinus", "정상 동리듬", 0),
  f("ecg_sinus_tachy", "동빈맥", 1),
  f("ecg_st_elev", "II·III·aVF ST 분절 상승", 2),
  f("ecg_vf", "심실세동", 2),
  f("ecg_af_rvr", "불규칙한 빠른 심방세동", 2),
  f("ecg_s1q3t3", "동빈맥과 우심 부담(S1Q3T3)", 2),
  f("ecg_low_voltage", "저전압과 전기적 교대", 2),
  f("ecg_peaked_t", "뾰족한 T파(고칼륨)", 2),
  // ── 동맥혈 가스 ──
  f("abga_normal", "산염기 정상", 0),
  f("abga_hypoxemia", "저산소혈증, 이산화탄소 정상", 1),
  f("abga_resp_fatigue", "저산소혈증, 이산화탄소가 오르기 시작(호흡근 피로)", 2),
  f("abga_metabolic_acidosis", "심한 대사성 산증, 호흡으로 보상 중", 2),
  f("abga_lactic", "젖산 산증", 1),
  f("abga_severe_hypox", "고농도 산소에도 P/F 110", 2),
  // ── 대변 ──
  f("stool_normal", "대변 검사 이상 없음", 0),
  f("stool_viral", "노로바이러스 항원 양성", 2, { organism: "virus" }),
  f("stool_cdiff_toxin", "C. difficile 독소 양성", 2, { organism: "cdiff" }),
  // ── X선 ──
  f("xr_normal", "X선 이상 없음", 0),
  f("xr_lobar", "오른쪽 아래 폐엽의 경화", 2),
  f("xr_patchy", "양쪽 얼룩덜룩한 간질성 침윤", 2),
  f("xr_hyperinflation", "폐 과팽창, 침윤 없음", 1),
  f("xr_pulm_edema", "양쪽 폐부종, 심장 비대, 흉수", 2),
  f("xr_bilateral", "양쪽 미만성 침윤, 심장 크기 정상", 2),
  f("xr_new_infiltrate", "새로 생긴 한쪽 폐 침윤", 2),
  f("xr_ptx", "한쪽 폐 허탈, 종격동이 반대쪽으로 밀림", 2),
  f("xr_globular_heart", "물병 모양으로 커진 심장 그림자", 2),
  // ── 현장 초음파 ──
  f("us_normal", "초음파 이상 없음", 0),
  f("us_appendix", "눌리지 않고 부은 충수", 2),
  f("us_flat_ivc", "납작하게 꺼지는 하대정맥(혈액량 부족)", 1),
  f("us_hydro_mild", "신우가 약간 늘어남", 1),
  f("us_blines_focal", "한쪽 B선과 폐 경화", 1),
  f("us_blines_plump_ivc", "양쪽 B선, 늘어난 하대정맥, 심장 수축력 저하", 2),
  f("us_blines_normal_heart", "양쪽 B선, 심장 수축력 정상", 2),
  f("us_tamponade", "심낭 삼출과 우심실 허탈", 2),
  f("us_no_sliding", "폐 미끄러짐 소실(기흉)", 2),
  f("us_rv_dilation", "우심실이 늘어나고 좌심실을 누름", 2),
  f("us_dvt", "대퇴정맥이 눌리지 않음(혈전)", 2),
  f("us_cobblestone", "피하 조약돌 모양 부종, 정맥은 잘 눌림", 2),
  f("us_wall_motion", "하벽 운동 저하", 2),
  f("us_no_obstruction", "요로 폐쇄 없음, 신장 크기 정상", 1),
  // ── CT ──
  f("ct_normal", "CT 이상 없음", 0),
  f("ct_appendicitis", "충수 벽 비후와 주위 지방 침윤", 4),
  f("ct_enteritis", "소장 벽 비후와 액체 저류", 2),
  f("ct_pyelo", "신장 조영 결손(신우신염)", 4),
  f("ct_consolidation", "폐 경화", 2),
  f("ct_ggo", "양쪽 간유리 음영과 얼룩 경화", 2),
  f("ct_pe", "폐동맥 조영 결손(색전)", 4),
  f("ct_no_bleed_ischemia", "출혈 없음, 초기 허혈 변화", 2),
  f("ct_pancreatitis", "췌장 부종과 주위 침윤", 4),
  f("ct_colitis", "대장 벽이 두꺼워짐(대장염)", 2),
  f("ct_bilateral_consol", "양쪽 폐 의존 부위 경화", 2),
  f("ct_ptx", "기흉과 종격동 편위", 4),
  f("ct_pericardial", "다량의 심낭 삼출", 4),
  f("ct_cellulitis", "피하 지방 침윤, 고름집 없음", 2),
  f("ct_venous_clot", "정맥 안의 충만 결손(혈전)", 4),
  f("ct_pulm_edema", "간질 부종과 흉수", 2),
  // ── 미생물 ──
  f("cx_neg", "배양 음성(자라지 않음)", 0),
  f("cx_urine_ecoli", "대장균 — 세프트리악손 감수성", 4, { organism: "ecoli", gram: "gnr" }),
  f("cx_urine_esbl", "ESBL 생성 대장균 — 세팔로스포린 내성", 4, { organism: "esbl", gram: "gnr" }),
  f("cx_urine_community", "대장균(흔한 지역사회 균)", 4, { organism: "mixed_community", gram: "gnr" }),
  f("cx_urine_gnr", "그람 음성 막대균(클렙시엘라)", 4, { organism: "gram_neg", gram: "gnr" }),
  f("cx_sputum_pneumo", "폐렴알균", 4, { organism: "pneumococcus", gram: "gpc" }),
  f("cx_sputum_pseudo", "녹농균", 4, { organism: "pseudomonas", gram: "gnr" }),
  f("cx_sputum_mrsa", "MRSA", 4, { organism: "mrsa", gram: "gpc" }),
  f("cx_wound_mssa", "연쇄알균·MSSA", 4, { organism: "mssa_strep", gram: "gpc" }),
  f("cx_wound_mrsa", "MRSA", 4, { organism: "mrsa", gram: "gpc" }),
  f("cx_blood_mssa", "황색포도알균(MSSA)", 4, { organism: "mssa_strep", gram: "gpc" }),
  f("cx_blood_mrsa", "MRSA", 4, { organism: "mrsa", gram: "gpc" }),
  f("cx_blood_gnr", "그람 음성 막대균(대장균·클렙시엘라)", 4, { organism: "gram_neg", gram: "gnr" }),
  f("gs_none", "균이 보이지 않음", 0),
  f("gs_gpc", "그람 양성 알균", 2),
  f("gs_gnr", "그람 음성 막대균", 2),
  // ── 경과 관찰 (v2.1): 질병이 나빠지는 방식. 일어난 뒤에만 보인다 ──
  f("crs_none", "특별한 경과 변화 없음", 0),
  f("crs_rlq_localized", "통증이 오른쪽 아랫배로 모이고 반발통이 생김", 2),
  f("crs_lip_swelling", "입술과 혀가 눈에 띄게 부어오름", 2),
  f("crs_urticaria", "두드러기가 온몸으로 번짐", 2),
  f("crs_vf", "모니터에 심실세동이 나타남", 2),
  f("crs_pulsus", "맥압이 좁아지고 숨 들이쉴 때 맥이 약해짐(기이맥)", 2),
  f("crs_airway_pressure", "기도 압력이 치솟고 한쪽 가슴이 움직이지 않음", 2),
  // ── 치료 반응 (core가 치료를 쓸 때 기록한다) ──
  f("rx_good", "뚜렷한 호전", 2),
  f("rx_partial", "부분적인 반응", 1),
  f("rx_none", "기대한 반응 없음", 0),
  f("rx_worse", "오히려 악화", 4),
];
