// 상호작용 규칙 17개. design.md D5
import { addCard, stab } from "./ops";
import type { InteractionRule } from "../core/types";

export const INTERACTIONS = [
  {
    id: "H1",
    kind: "hazard",
    incoming: { any: ["qt_prolong"] },
    active: { any: ["qt_prolong"] },
    symmetric: true,
    priority: 10,
    effects: [addCard("arrhythmia", 1, "hand")],
    text: "QT 연장 약물 병용 — 손에 부정맥 1장",
    medical: { fidelity: "accurate", note: "QT 연장 효과가 더해져 다형성 심실빈맥 위험이 커진다" },
  },
  {
    id: "H2",
    kind: "hazard",
    incoming: { any: ["k_lowering"] },
    active: { any: ["qt_prolong"] },
    symmetric: true,
    priority: 11,
    effects: [addCard("arrhythmia", 1, "draw_random")],
    text: "칼륨 저하 + QT 연장 — 대기 처방에 부정맥 1장",
    medical: { fidelity: "accurate", note: "저칼륨혈증은 QT 연장 약물의 부정맥 위험을 키운다" },
  },
  {
    id: "H3",
    kind: "hazard",
    incoming: { any: ["k_lowering"] },
    active: { any: ["k_lowering"] },
    symmetric: true,
    priority: 12,
    effects: [addCard("hypokalemia", 1, "hand")],
    text: "칼륨 저하 약물 병용 — 손에 저칼륨혈증 1장",
    medical: { fidelity: "simplified", note: "이뇨제·인슐린·β2 작용제가 겹치면 저칼륨혈증" },
  },
  {
    id: "H4",
    kind: "hazard",
    incoming: { any: ["cyp3a4_substrate"] },
    active: { any: ["cyp3a4_inhibitor"] },
    symmetric: false,
    priority: 5,
    effects: [{ op: "modify_current", pct: 150 }, { op: "extra_side_effects", times: 1 }],
    text: "CYP3A4 억제 중 기질 투여 — 효과 ×1.5, 부작용 한 번 더",
    medical: { fidelity: "simplified", note: "억제제가 기질 약물의 농도를 높인다(클래리스로마이신 + 미다졸람 → 진정 연장)" },
  },
  {
    id: "H4b",
    kind: "hazard",
    incoming: { any: ["cyp3a4_inhibitor"] },
    active: { any: ["cyp3a4_substrate"] },
    symmetric: false,
    priority: 6,
    effects: [{ op: "extend_drug", filter: { tags: ["cyp3a4_substrate"] }, turns: 1 }, { op: "custom", id: "partner_side_effect" }],
    text: "기질 투여 중 CYP3A4 억제제 — 기질 약물 지속 +1, 그 부작용 1장",
    medical: { fidelity: "simplified", note: "기질 약물의 대사가 늦어져 효과와 부작용이 길어진다" },
  },
  {
    id: "H5",
    kind: "hazard",
    incoming: { any: ["cns_depressant"] },
    active: { any: ["cns_depressant"] },
    symmetric: true,
    priority: 10,
    effects: [addCard("resp_depression", 1, "hand")],
    text: "중추신경 억제제 병용 — 손에 호흡억제 1장",
    medical: { fidelity: "accurate", note: "오피오이드와 벤조디아제핀 병용의 호흡억제(미국 FDA 박스 경고)" },
  },
  {
    id: "H6",
    kind: "hazard",
    incoming: { any: ["nephrotoxic"] },
    active: { any: ["nephrotoxic"] },
    symmetric: true,
    priority: 10,
    effects: [addCard("nephrotoxicity", 2, "discard")],
    text: "신독성 약물 병용 — 완료 처방에 신독성 2장",
    medical: { fidelity: "accurate", note: "반코마이신 + 아미노글리코사이드" },
  },
  {
    id: "H7",
    kind: "hazard",
    incoming: { any: ["anticoagulant"] },
    active: { any: ["antiplatelet"] },
    symmetric: true,
    priority: 10,
    effects: [{ op: "apply_status", status: "bleeding_tendency", stacks: 1, target: "patient" }],
    text: "항응고제 + 항혈소판제 — 출혈 경향",
    medical: { fidelity: "accurate", note: "이중 항혈전 요법의 출혈 위험" },
  },
  {
    id: "H8",
    kind: "hazard",
    incoming: { any: ["insulin"] },
    symmetric: false,
    condition: { not: { activeDrugTag: "k_raising" } },
    priority: 9,
    effects: [addCard("hypokalemia", 1, "hand")],
    text: "칼륨 보충 없이 인슐린 — 손에 저칼륨혈증 1장",
    medical: { fidelity: "accurate", note: "인슐린은 칼륨을 세포 안으로 옮긴다. DKA에서는 칼륨을 먼저 확인하고 보충한다" },
  },
  {
    id: "H9",
    kind: "hazard",
    incoming: { any: ["thrombolytic"] },
    active: { any: ["anticoagulant", "antiplatelet"] },
    symmetric: true,
    priority: 8,
    effects: [addCard("bleeding", 1, "hand")],
    text: "혈전용해제 + 항혈전제 — 손에 출혈 1장",
    medical: { fidelity: "accurate", note: "혈전용해 후 24시간은 항혈전제를 보류한다" },
  },
  {
    id: "S1",
    kind: "synergy",
    incoming: { any: ["beta_lactam"] },
    active: { any: ["aminoglycoside"] },
    symmetric: true,
    priority: 1,
    effects: [{ op: "modify_current", pct: 150 }],
    text: "베타락탐 + 아미노글리코사이드 — 이번 카드 ×1.5",
    medical: { fidelity: "simplified", note: "세포벽 손상이 아미노글리코사이드 유입을 돕는다(균종 조건 생략)" },
  },
  {
    id: "S2",
    kind: "synergy",
    incoming: { any: ["vasopressor"] },
    active: { any: ["fluid"] },
    symmetric: false,
    priority: 2,
    effects: [stab(8)],
    text: "수액 투여 후 승압제 — 안정화 8",
    medical: { fidelity: "simplified", note: "수액으로 전부하를 채운 뒤 승압제" },
  },
  {
    id: "S3",
    kind: "synergy",
    incoming: { any: ["anticoagulant"] },
    active: { any: ["antiplatelet"] },
    symmetric: true,
    condition: { targetTrait: ["acs"] },
    priority: 1,
    effects: [{ op: "modify_current", pct: 150 }],
    text: "급성 관상동맥 증후군에 항응고 + 항혈소판 — 이번 카드 ×1.5",
    medical: { fidelity: "simplified", note: "ACS는 이중 항혈소판 + 항응고가 표준. 정맥혈전에는 해당하지 않는다" },
  },
  {
    id: "S4",
    kind: "synergy",
    incoming: { any: ["insulin"] },
    active: { any: ["glucose"] },
    symmetric: false,
    priority: 1,
    effects: [{ op: "suppress_side_effects" }],
    text: "포도당과 함께 인슐린 — 이번 카드의 부작용 없음",
    medical: { fidelity: "simplified", note: "DKA에서 혈당이 떨어지면 포도당을 추가해 인슐린을 이어 간다" },
  },
  {
    id: "S5",
    kind: "synergy",
    incoming: { any: ["nitroimidazole"] },
    active: { any: ["beta_lactam", "fluoroquinolone", "aminoglycoside"] },
    symmetric: true,
    condition: { targetCategory: ["abdominal"] },
    priority: 1,
    effects: [{ op: "modify_current", pct: 200 }],
    text: "복강 내 감염에 혐기균 약 병용 — 이번 카드 ×2",
    medical: { fidelity: "simplified", note: "세프트리악손 + 메트로니다졸처럼 그람 음성균과 혐기균을 함께 덮는다" },
  },
  {
    id: "A1",
    kind: "antagonism",
    incoming: { any: ["opioid_antagonist"] },
    active: { any: ["opioid"] },
    symmetric: false,
    priority: 3,
    effects: [{ op: "end_drug", filter: { tags: ["opioid"] } }],
    text: "날록손이 오피오이드를 역전 — 오피오이드 투여 종료",
    medical: { fidelity: "accurate", note: "통증 조절도 함께 사라진다" },
  },
  {
    id: "A2",
    kind: "antagonism",
    incoming: { any: ["anaphylaxis_tx"] },
    active: { any: ["beta_blocker"] },
    symmetric: false,
    priority: 3,
    effects: [{ op: "modify_current", pct: 50 }],
    text: "β차단제 투여 중 에피네프린 — 이번 카드 ×0.5",
    medical: { fidelity: "accurate", note: "β차단제 복용자의 아나필락시스는 에피네프린에 잘 반응하지 않는다(글루카곤 고려)" },
  },
] satisfies InteractionRule[];
