// 유물(가이드라인) 17개. design.md §5.8
import { addCard, draw, orders, stab } from "./ops";
import type { RelicDef } from "../core/types";

export const RELICS = [
  {
    id: "intern_notebook",
    nameKo: "인턴 수첩",
    nameEn: "Intern's notebook",
    badge: "수첩",
    tier: "starter",
    triggers: [{ on: "combat_start", effects: [{ op: "draw_filtered", filter: { kind: ["diagnostic"] }, amount: 1 }] }],
    description: "전투가 시작될 때 대기 처방에서 진단 카드 1장을 손으로 가져온다.",
    flavor: "모서리가 닳은 포켓 수첩. 선배가 적어 준 감별 목록이 있다.",
  },
  {
    id: "hand_hygiene",
    nameKo: "손 위생 지침",
    nameEn: "Hand hygiene",
    badge: "HH",
    tier: "common",
    triggers: [{ on: "combat_start", effects: [stab(6)] }],
    description: "전투가 시작될 때 안정화 6.",
    flavor: "환자 접촉 전, 무균 처치 전, 체액 노출 후, 환자 접촉 후, 환경 접촉 후.",
  },
  {
    id: "news",
    nameKo: "조기 경보 점수",
    nameEn: "National Early Warning Score",
    badge: "NEWS",
    tier: "common",
    triggers: [{ on: "countdown_started", effects: [stab(5)] }],
    description: "질병이 합병증을 예고하면 안정화 5.",
    flavor: "점수가 5를 넘으면 담당의에게 알린다.",
  },
  {
    id: "five_rights",
    nameKo: "투약 5R 원칙",
    nameEn: "Five rights of medication",
    badge: "5R",
    tier: "common",
    triggers: [],
    modifiers: [{ kind: "firstDrugNoSideEffects" }],
    description: "전투마다 처음 생기는 약물 부작용을 막는다.",
    flavor: "정확한 환자, 약, 용량, 경로, 시간.",
  },
  {
    id: "sbar",
    nameKo: "SBAR 인계",
    nameEn: "SBAR handoff",
    badge: "SBAR",
    tier: "common",
    triggers: [],
    modifiers: [{ kind: "retainOne" }],
    description: "턴을 마칠 때 손패 1장을 골라 다음 턴으로 넘길 수 있다.",
    flavor: "상황, 배경, 평가, 권고.",
  },
  {
    id: "guideline_summary",
    nameKo: "진료 지침 요약본",
    nameEn: "Guideline pocket card",
    badge: "GL",
    tier: "common",
    triggers: [{ on: "knowledge_up", effects: [draw(1)] }, { on: "diagnosis_committed", oncePerCombat: true, effects: [draw(1)] }],
    description: "전투에서 처음 작업 진단을 정할 때와 확진할 때 카드 1장 뽑기.",
    flavor: "코팅된 카드 한 장에 알고리즘이 빼곡하다.",
  },
  {
    id: "fluid_protocol",
    nameKo: "수액 프로토콜",
    nameEn: "Fluid protocol",
    badge: "IVF",
    tier: "common",
    triggers: [],
    description: "전투가 끝날 때, 이번 전투에서 수액을 투여했다면 활력 3 회복.",
    flavor: "무엇을, 얼마나, 언제까지.",
  },
  {
    id: "dur_system",
    nameKo: "DUR 시스템",
    nameEn: "Drug utilization review",
    badge: "DUR",
    tier: "uncommon",
    triggers: [],
    modifiers: [{ kind: "firstHazardBlocked" }],
    description: "전투마다 첫 번째 위험 상호작용을 막는다.",
    flavor: "\"병용 금기 약물입니다. 계속하시겠습니까?\"",
  },
  {
    id: "asp",
    nameKo: "항생제 관리 프로그램",
    nameEn: "Antimicrobial stewardship",
    badge: "ASP",
    tier: "uncommon",
    triggers: [],
    modifiers: [{ kind: "resistanceHalf" }, { kind: "abxBonusOrganism", value: 3 }],
    description: "획득 내성이 절반만 쌓인다. 원인균을 확인한 문제에 항생제 효과 +3.",
    flavor: "감염내과에서 전화가 왔다. \"배양 결과 보셨어요?\"",
  },
  {
    id: "sepsis_bundle",
    nameKo: "패혈증 1시간 번들",
    nameEn: "Hour-1 sepsis bundle",
    badge: "SEP-1",
    tier: "uncommon",
    triggers: [{ on: "combat_start", effects: [{ op: "cost_modifier", filter: { tags: ["abx"] }, delta: -9, uses: 1, scope: "turn" }, { op: "cost_modifier", filter: { ids: ["culture"] }, delta: -9, uses: 1, scope: "turn" }] }],
    description: "전투 첫 턴에 처음 쓰는 배양 검사와 항생제의 비용이 0.",
    flavor: "젖산, 혈액배양, 광범위 항생제, 수액, 승압제.",
  },
  {
    id: "acls",
    nameKo: "ACLS 알고리즘",
    nameEn: "Advanced cardiovascular life support",
    badge: "ACLS",
    tier: "uncommon",
    triggers: [{ on: "vitality_below", condition: { vitalityBelowPct: 25 }, oncePerCombat: true, effects: [stab(15), orders(1)] }],
    description: "전투 중 활력이 처음으로 25% 이하가 되면 안정화 15, 오더 +1.",
    flavor: "2분마다 리듬 확인.",
  },
  {
    id: "ddx_checklist",
    nameKo: "감별진단 체크리스트",
    nameEn: "Differential diagnosis checklist",
    badge: "DDx",
    tier: "uncommon",
    triggers: [],
    modifiers: [{ kind: "extraDiagnosticPick" }],
    description: "매 턴 처음 여는 진단 카드 선택지를 하나 더 고른다.",
    flavor: "흔한 것부터, 위험한 것은 꼭.",
  },
  {
    id: "icu_admission",
    nameKo: "중환자실 입실",
    nameEn: "ICU admission",
    badge: "ICU",
    tier: "boss",
    triggers: [],
    modifiers: [{ kind: "ordersPerTurn", delta: 1 }, { kind: "noRestHeal" }],
    description: "턴마다 오더 +1. 당직실에서 휴식할 수 없다.",
    flavor: "1:2 간호, 그리고 잠들지 않는 모니터.",
  },
  {
    id: "mdt",
    nameKo: "다학제 협진",
    nameEn: "Multidisciplinary team",
    badge: "MDT",
    tier: "boss",
    triggers: [],
    modifiers: [{ kind: "ordersPerTurn", delta: 1 }, { kind: "cardRewardChoices", value: 2 }],
    description: "턴마다 오더 +1. 카드 보상의 선택지가 2장으로 준다.",
    flavor: "의견은 많고 결론은 하나.",
  },
  {
    id: "broad_protocol",
    nameKo: "광범위 항생제 프로토콜",
    nameEn: "Broad-spectrum protocol",
    badge: "BSA",
    tier: "boss",
    triggers: [{ on: "combat_start", effects: [addCard("dysbiosis", 1, "draw_random")] }],
    modifiers: [{ kind: "abxPct", pct: 130 }],
    description: "항생제 피해 ×1.3. 전투가 시작될 때 대기 처방에 장내세균 교란 1장.",
    flavor: "일단 다 덮고 본다.",
  },
  {
    id: "thirty_six",
    nameKo: "36시간 연속 당직",
    nameEn: "36-hour shift",
    badge: "36H",
    tier: "boss",
    triggers: [],
    modifiers: [{ kind: "ordersPerTurn", delta: 1 }, { kind: "maxCardsPerTurn", value: 6 }],
    description: "턴마다 오더 +1. 한 턴에 카드를 6장까지만 쓸 수 있다.",
    flavor: "커피는 네 잔째.",
  },
  {
    id: "cpoe",
    nameKo: "처방 전산화",
    nameEn: "Computerized order entry",
    badge: "CPOE",
    tier: "boss",
    triggers: [{ on: "combat_start", effects: [addCard("nausea", 2, "draw_random")] }],
    modifiers: [{ kind: "ordersPerTurn", delta: 1 }],
    description: "턴마다 오더 +1. 전투가 시작될 때 대기 처방에 오심 2장.",
    flavor: "빠르다. 가끔 엉뚱한 오더도 같이 나간다.",
  },
  {
    id: "obsolete_relic",
    nameKo: "폐기된 유물",
    badge: "—",
    tier: "special",
    triggers: [],
    description: "저장 파일의 유물이 사라져 대신 들어왔다. 효과 없음.",
    flavor: "",
  },
] satisfies RelicDef[];
