// 태그·특성·원인균·분류. design.md §4.1, §5.3
import type { DiseaseCategory, OrganismDef, TagDef, TraitDef } from "../core/types";

export const TAGS = [
  // 치료 기전 (적응증 있음)
  { id: "fluid", nameKo: "수액", kind: "therapeutic", indications: { traits: ["hypovolemia"] } },
  { id: "vasopressor", nameKo: "승압제", kind: "therapeutic", indications: { traits: ["shock"] } },
  { id: "loop_diuretic", nameKo: "고리 이뇨제", kind: "therapeutic", indications: { traits: ["volume_overload"] } },
  { id: "insulin", nameKo: "인슐린", kind: "therapeutic", indications: { traits: ["hyperglycemia"] } },
  { id: "beta2_agonist", nameKo: "β2 작용제", kind: "therapeutic", indications: { traits: ["bronchospasm"] } },
  { id: "corticosteroid", nameKo: "스테로이드", kind: "therapeutic", indications: { traits: ["bronchospasm", "allergic"] } },
  { id: "anaphylaxis_tx", nameKo: "아나필락시스 치료", kind: "therapeutic", indications: { traits: ["allergic"] } },
  { id: "antiplatelet", nameKo: "항혈소판제", kind: "therapeutic", indications: { traits: ["arterial_thrombus"] } },
  { id: "anticoagulant", nameKo: "항응고제", kind: "therapeutic", indications: { traits: ["venous_thrombus", "arterial_thrombus"] } },
  { id: "thrombolytic", nameKo: "혈전용해제", kind: "therapeutic", indications: { traits: ["thrombolysable"] } },
  { id: "beta_blocker", nameKo: "β차단제", kind: "therapeutic", indications: { traits: ["arrhythmia", "acs"] } },
  { id: "antiarrhythmic", nameKo: "항부정맥제", kind: "therapeutic", indications: { traits: ["arrhythmia"] } },
  { id: "antipsychotic", nameKo: "항정신병제", kind: "therapeutic", indications: { traits: ["agitation"] } },
  { id: "ammonia_lowering", nameKo: "암모니아 저하제", kind: "therapeutic", indications: { traits: ["hyperammonemia"] } },
  { id: "ppi", nameKo: "양성자 펌프 억제제", kind: "therapeutic", indications: { traits: ["gi_bleed"] } },
  // 처치 적응증
  { id: "source_control", nameKo: "감염원 제거", kind: "therapeutic", indications: { traits: ["source"] } },
  { id: "defib", nameKo: "제세동", kind: "therapeutic", indications: { traits: ["shockable"] } },
  { id: "airway", nameKo: "기관 삽관", kind: "therapeutic", indications: { traits: ["resp_failure"] } },
  { id: "chest_tube", nameKo: "흉관", kind: "therapeutic", indications: { traits: ["pleural"] } },
  { id: "transfusion", nameKo: "수혈", kind: "therapeutic", indications: { traits: ["hemorrhage"] } },
  { id: "pericardiocentesis", nameKo: "심낭 천자", kind: "therapeutic", indications: { traits: ["pericardial"] } },
  { id: "endoscopy", nameKo: "내시경 지혈", kind: "therapeutic", indications: { traits: ["gi_bleed"] } },
  { id: "dialysis", nameKo: "투석", kind: "therapeutic", indications: { traits: ["renal_failure"] } },
  { id: "revascularization", nameKo: "혈관 재개통", kind: "therapeutic", indications: { traits: ["arterial_thrombus"] } },
  // 약물 계열
  { id: "abx", nameKo: "항생제", kind: "property" },
  { id: "beta_lactam", nameKo: "베타락탐", kind: "class" },
  { id: "carbapenem", nameKo: "카바페넴", kind: "class" },
  { id: "glycopeptide", nameKo: "글리코펩타이드", kind: "class" },
  { id: "aminoglycoside", nameKo: "아미노글리코사이드", kind: "class" },
  { id: "fluoroquinolone", nameKo: "플루오로퀴놀론", kind: "class" },
  { id: "macrolide", nameKo: "마크롤라이드", kind: "class" },
  { id: "nitroimidazole", nameKo: "니트로이미다졸", kind: "class" },
  { id: "opioid", nameKo: "오피오이드", kind: "class" },
  { id: "opioid_antagonist", nameKo: "오피오이드 길항제", kind: "class" },
  { id: "benzodiazepine", nameKo: "벤조디아제핀", kind: "class" },
  { id: "glucose", nameKo: "포도당", kind: "class" },
  // 성질
  { id: "broad_spectrum", nameKo: "광범위", kind: "property" },
  { id: "cdi_risk", nameKo: "C. diff 위험", kind: "property" },
  { id: "qt_prolong", nameKo: "QT 연장", kind: "property" },
  { id: "k_lowering", nameKo: "칼륨 저하", kind: "property" },
  { id: "k_raising", nameKo: "칼륨 상승", kind: "property" },
  { id: "electrolyte", nameKo: "전해질", kind: "property" },
  { id: "nephrotoxic", nameKo: "신독성", kind: "property" },
  { id: "cns_depressant", nameKo: "중추신경 억제", kind: "property" },
  { id: "cyp3a4_inhibitor", nameKo: "CYP3A4 억제", kind: "property" },
  { id: "cyp3a4_substrate", nameKo: "CYP3A4 기질", kind: "property" },
  { id: "immunosuppressive", nameKo: "면역억제", kind: "property" },
  { id: "analgesic", nameKo: "해열진통제", kind: "property" },
  { id: "antiemetic", nameKo: "진토제", kind: "property" },
] satisfies TagDef[];

export const TRAITS = [
  { id: "chest", nameKo: "흉부 질환" },
  { id: "cardiac", nameKo: "심장 질환" },
  { id: "renal", nameKo: "신장·요로 질환" },
  { id: "us_visible", nameKo: "초음파로 보이는 질환" },
  { id: "hypovolemia", nameKo: "순환 혈액량 부족" },
  { id: "shock", nameKo: "쇼크" },
  { id: "volume_overload", nameKo: "체액 과다" },
  { id: "hyperglycemia", nameKo: "고혈당 위기" },
  { id: "bronchospasm", nameKo: "기관지 연축" },
  { id: "allergic", nameKo: "알레르기 반응" },
  { id: "arterial_thrombus", nameKo: "동맥 혈전" },
  { id: "venous_thrombus", nameKo: "정맥 혈전" },
  { id: "thrombolysable", nameKo: "혈전용해 적응" },
  { id: "acs", nameKo: "급성 관상동맥 증후군" },
  { id: "arrhythmia", nameKo: "부정맥" },
  { id: "shockable", nameKo: "충격 가능 리듬" },
  { id: "agitation", nameKo: "초조" },
  { id: "hyperammonemia", nameKo: "고암모니아혈증" },
  { id: "gi_bleed", nameKo: "위장관 출혈" },
  { id: "hemorrhage", nameKo: "출혈성 질환" },
  { id: "source", nameKo: "감염원 제거 가능" },
  { id: "resp_failure", nameKo: "호흡 부전" },
  { id: "pleural", nameKo: "흉막강 질환" },
  { id: "pericardial", nameKo: "심낭 질환" },
  { id: "renal_failure", nameKo: "신부전" },
] satisfies TraitDef[];

export const ORGANISMS = [
  { id: "pneumococcus", nameKo: "폐렴알균", nameEn: "Streptococcus pneumoniae" },
  { id: "atypical", nameKo: "비정형균", nameEn: "Mycoplasma · Legionella" },
  { id: "ecoli", nameKo: "대장균", nameEn: "Escherichia coli" },
  { id: "esbl", nameKo: "ESBL 생성 대장균", nameEn: "ESBL-producing E. coli" },
  { id: "mssa_strep", nameKo: "연쇄알균·MSSA", nameEn: "Streptococcus · MSSA" },
  { id: "mrsa", nameKo: "MRSA", nameEn: "Methicillin-resistant S. aureus" },
  { id: "intra_abdominal", nameKo: "장내세균+혐기균", nameEn: "Enteric gram-negatives + anaerobes" },
  { id: "cdiff", nameKo: "C. difficile", nameEn: "Clostridioides difficile" },
  { id: "pseudomonas", nameKo: "녹농균", nameEn: "Pseudomonas aeruginosa" },
  { id: "gram_neg", nameKo: "그람 음성 막대균", nameEn: "Gram-negative bacilli" },
  { id: "virus", nameKo: "바이러스", nameEn: "Virus" },
  { id: "mixed_community", nameKo: "지역사회 세균", nameEn: "Community bacteria" },
] satisfies OrganismDef[];

export const CATEGORIES: Record<DiseaseCategory, string> = {
  infection: "감염",
  metabolic: "대사",
  cardiovascular: "심혈관",
  thrombotic: "혈전",
  respiratory: "호흡",
  neuro: "신경",
  bleeding: "출혈",
  abdominal: "복부",
  allergic: "알레르기",
  renal: "신장",
};
