// 1막 응급실. design.md §5.5
// findings: 경로별 소견 (없으면 그 경로의 정상 소견). 소견을 공유할수록 그 경로로는 구별되지 않는다.
// definitive: 이 태그의 치료가 잘 들으면 질병의 기전이 바뀐다 (합병증 취소 등).
import { atk, block, phase, raise, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef, EffectOp } from "../../core/types";

const fluidHalf = [{ if: { activeDrugTag: "fluid" }, pct: 50 }];
const cancel: EffectOp = { op: "cancel_countdowns", target: "target" };
const clearSelf = (status: string): EffectOp => ({ op: "remove_status", status, target: "target", stacks: "all" });

export const ACT1_DISEASES = [
  {
    id: "appendicitis",
    nameKo: "급성 충수염",
    nameEn: "Acute appendicitis",
    textbook: { keyFeatures: "명치에서 오른쪽 아래로 옮겨 가는 통증, 우하복부 반발통, 미열. 초음파·CT로 확인한다." },
    category: "abdominal",
    traits: ["source", "us_visible"],
    tier: "normal",
    act: 1,
    severity: [40, 44],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_migrating",
      hx_assoc: "as_gi_upset",
      ex_abd: "ab_rlq_peritonism",
      lab_cbc: "cbc_leukocytosis",
      pocus: "us_appendix",
      ct: "ct_appendicitis",
    },
    organism: "intra_abdominal",
    atypical: { hx_onset: "on_acute", ex_abd: "ab_diffuse_mild", lab_cbc: "cbc_normal" },
    effectiveness: { source_control: "weak" },
    definitive: [{ tags: ["source_control"], text: "감염원 제거: 천공 위험이 사라졌다", effects: [cancel, clearSelf("inflammation")] }],
    // v2.1: 천공 위험은 "통증(경미)"으로 보이고, 일어난 뒤 우하복부 국소화가 경과 소견으로 남는다
    moves: [
      { id: "perf_warning", nameKo: "천공 위험", pressure: "pain", effects: [warn("perforation", 3), atk(5)], course: "crs_rlq_localized" },
      { id: "perforation", nameKo: "천공", pressure: "worsening", effects: [raise(15), toSelf("aggravation", 3)] },
      { id: "rlq_pain", nameKo: "우하복부 통증", pressure: "pain", effects: [atk(5)] },
      { id: "ache", nameKo: "통증", pressure: "pain", effects: [atk(9)] },
      { id: "vomiting", nameKo: "구토", pressure: "hemodynamic", effects: [atk(7), toPatient("dehydration", 1)] },
      { id: "local_inflammation", nameKo: "국소 염증", pressure: "worsening", effects: [toSelf("inflammation", 2), atk(6)] },
    ],
    ai: { opening: ["perf_warning"], weights: { ache: 60, local_inflammation: 40 }, maxInARow: 2 },
    art: { region: "abdomen", lesion: [0.36, 0.64, 0.09] },
    passiveText: ["감염원 제거가 들으면 천공 예고가 사라진다."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 천공은 치료 지연의 대표 합병증. 단순 충수염은 항생제 단독 치료도 가능(CODA)" },
  },
  {
    id: "gastroenteritis",
    nameKo: "급성 위장관염",
    nameEn: "Acute gastroenteritis",
    textbook: { keyFeatures: "갑자기 시작한 구토·물설사, 같이 먹은 사람도 아픔, 국소 압통 없음. 탈수가 문제다." },
    category: "infection",
    traits: ["hypovolemia"],
    tier: "normal",
    act: 1,
    severity: [30, 34],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_acute",
      hx_assoc: "as_vomit_diarrhea",
      hx_risk: "rk_sick_contacts",
      ex_abd: "ab_diffuse_mild",
      ex_limb: "lb_dry",
      lab_chem: "chem_prerenal",
      lab_ua: "ua_concentrated",
      stool: "stool_viral",
      pocus: "us_flat_ivc",
      ct: "ct_enteritis",
    },
    organism: "virus",
    atypical: { hx_risk: "rk_none", hx_assoc: "as_gi_upset" },
    effectiveness: { fluid: "weak" },
    moves: [
      { id: "vomit", nameKo: "구토", pressure: "hemodynamic", effects: [atk(7), toPatient("dehydration", 1)] },
      { id: "diarrhea", nameKo: "설사", pressure: "hemodynamic", effects: [atk(4, 2)] },
      { id: "fluid_loss", nameKo: "수분 손실", pressure: "hemodynamic", effects: [atk(5), toPatient("dehydration", 1)] },
      { id: "cramps", nameKo: "복부 경련", pressure: "pain", effects: [atk(5)] },
      { id: "colic", nameKo: "쥐어짜는 복통", pressure: "pain", effects: [atk(8)] },
      { id: "dehydration", nameKo: "탈수 진행", pressure: "worsening", effects: [toPatient("dehydration", 2), toSelf("aggravation", 1), atk(3)] },
    ],
    ai: { weights: { vomit: 45, diarrhea: 35, dehydration: 20 }, noRepeat: ["dehydration"] },
    art: { region: "abdomen", lesion: [0.5, 0.58, 0.16] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 바이러스성은 항생제 무효. 수분 보충이 핵심" },
  },
  {
    id: "cap",
    nameKo: "폐렴",
    nameEn: "Pneumonia",
    textbook: { keyFeatures: "며칠에 걸친 발열·기침, 한쪽 폐의 수포음, X선 침윤. 원인균(폐렴알균·비정형균)에 따라 듣는 항생제가 다르다." },
    category: "infection",
    traits: ["chest", "resp_failure"],
    tier: "normal",
    act: 1,
    severity: [44, 48],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_days",
      hx_assoc: "as_productive_cough",
      ex_cardio: "cd_crackles_focal",
      lab_cbc: "cbc_leukocytosis",
      abga: "abga_hypoxemia",
      xray: "xr_lobar",
      pocus: "us_blines_focal",
      ct: "ct_consolidation",
      cx_sputum: "cx_sputum_pneumo",
    },
    atypical: { ex_cardio: "cd_wheeze", hx_assoc: "as_none", hx_onset: "on_acute" },
    effectiveness: {},
    variants: [
      { id: "pneumococcus", weight: 70, nameKo: "폐렴알균", organism: "pneumococcus" },
      {
        id: "atypical",
        weight: 30,
        nameKo: "비정형균(마이코플라스마)",
        organism: "atypical",
        findings: { hx_assoc: "as_dry_cough", ex_cardio: "cd_crackles_scattered", lab_cbc: "cbc_normal", xray: "xr_patchy", ct: "ct_ggo", cx_sputum: "cx_neg" },
      },
    ],
    acquiredResistance: { tags: ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"], gainPerHit: 1 },
    moves: [
      { id: "cough", nameKo: "기침", pressure: "respiratory", effects: [atk(8)] },
      { id: "tachypnea", nameKo: "빠른 호흡", pressure: "respiratory", effects: [atk(5), toPatient("hypoxia", 1)] },
      { id: "resp_failure", nameKo: "호흡 부전", pressure: "respiratory", effects: [atk(14)] },
      { id: "fever", nameKo: "발열", pressure: "infection", effects: [atk(6), toPatient("weak", 1)] },
      { id: "high_fever", nameKo: "고열", pressure: "infection", effects: [atk(10)] },
      { id: "inflame", nameKo: "염증 반응", pressure: "worsening", effects: [toSelf("inflammation", 2), atk(4)] },
    ],
    ai: { weights: { cough: 45, fever: 30, inflame: 25 }, noRepeat: ["inflame"] },
    art: { region: "chest", lesion: [0.34, 0.66, 0.12] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). 비정형균은 베타락탐 무효이고 일반 객담 배양에서 자라지 않는다. 국내 폐렴알균은 마크롤라이드 내성률이 높다" },
  },
  {
    id: "pyelo",
    nameKo: "급성 신우신염",
    nameEn: "Acute pyelonephritis",
    textbook: { keyFeatures: "고열·오한, 배뇨통, 옆구리(늑척추각) 두드림 통증, 농뇨. 최근 항생제·입원력이 있으면 내성균(ESBL)을 의심한다." },
    category: "infection",
    traits: ["renal"],
    tier: "normal",
    act: 1,
    severity: [38, 42],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_days",
      hx_assoc: "as_urinary",
      hx_risk: "rk_uti_history",
      ex_abd: "ab_flank_cva",
      lab_cbc: "cbc_leukocytosis",
      lab_ua: "ua_pyuria",
      pocus: "us_hydro_mild",
      ct: "ct_pyelo",
      cx_urine: "cx_urine_ecoli",
    },
    atypical: { hx_assoc: "as_gi_upset", ex_abd: "ab_diffuse_mild" },
    effectiveness: {},
    variants: [
      { id: "ecoli", weight: 85, nameKo: "대장균", organism: "ecoli" },
      { id: "esbl", weight: 15, nameKo: "ESBL 생성 대장균", organism: "esbl", findings: { hx_risk: "rk_recent_hosp_abx", cx_urine: "cx_urine_esbl" } },
    ],
    acquiredResistance: { tags: ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"], gainPerHit: 1 },
    moves: [
      { id: "rigor", nameKo: "오한", pressure: "infection", effects: [atk(3, 2)] },
      { id: "high_fever", nameKo: "고열", pressure: "infection", effects: [atk(11)] },
      { id: "flank_pain", nameKo: "옆구리 통증", pressure: "pain", effects: [atk(9)] },
      { id: "dysuria", nameKo: "배뇨통", pressure: "pain", effects: [atk(5)] },
      { id: "abscess", nameKo: "신장 농양 형성", pressure: "worsening", effects: [block(8), toSelf("aggravation", 1), atk(3)] },
    ],
    ai: { weights: { rigor: 40, high_fever: 40, abscess: 20 }, noRepeat: ["abscess"] },
    art: { region: "pelvis", lesion: [0.36, 0.38, 0.1] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). ESBL은 3세대 세팔로스포린 무효, 카바페넴이 1차" },
  },
  {
    id: "asthma",
    nameKo: "천식 급성 악화",
    nameEn: "Acute asthma exacerbation",
    textbook: { keyFeatures: "쌕쌕거림(천명), 흡입기 과다 사용, 열 없음. 기관지 확장제와 전신 스테로이드. β차단제는 금기." },
    category: "respiratory",
    traits: ["chest", "bronchospasm", "resp_failure"],
    tier: "normal",
    act: 1,
    severity: [32, 36],
    findings: {
      vitals: "vt_tachypnea_hypox",
      hx_onset: "on_episodic",
      hx_assoc: "as_wheeze_cough",
      hx_risk: "rk_inhaler",
      ex_cardio: "cd_wheeze",
      abga: "abga_resp_fatigue",
      xray: "xr_hyperinflation",
    },
    atypical: { hx_risk: "rk_none", abga: "abga_hypoxemia", hx_onset: "on_days" },
    effectiveness: { beta2_agonist: "weak", corticosteroid: "weak", anaphylaxis_tx: "resistant", beta_blocker: "harmful" },
    definitive: [{ tags: ["beta2_agonist", "corticosteroid"], text: "기관지 확장: 연축이 풀린다", effects: [clearSelf("aggravation")] }],
    moves: [
      { id: "bronchospasm", nameKo: "기관지 연축", pressure: "respiratory", effects: [atk(6, 2)] },
      { id: "mucus", nameKo: "점액 마개", pressure: "respiratory", effects: [atk(5), toPatient("hypoxia", 1)] },
      { id: "fatigue", nameKo: "호흡근 피로", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "status_asthmaticus", nameKo: "지속성 천식 발작", pressure: "respiratory", effects: [atk(14)] },
    ],
    ai: { weights: { bronchospasm: 45, mucus: 30, fatigue: 25 }, noRepeat: ["mucus", "fatigue"] },
    art: { region: "chest", lesion: [0.5, 0.45, 0.22] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). β차단제는 기관지 연축을 악화시킨다" },
  },
  {
    id: "anaphylaxis",
    nameKo: "아나필락시스",
    nameEn: "Anaphylaxis",
    textbook: { keyFeatures: "약물·조영제 노출 직후 두드러기·입술 부종, 쌕쌕거림, 저혈압. 에피네프린 근육주사가 1차." },
    category: "allergic",
    traits: ["allergic", "bronchospasm", "shock", "hypovolemia"],
    tier: "normal",
    act: 1,
    severity: [26, 30],
    findings: {
      vitals: "vt_shock",
      hx_onset: "on_minutes_exposure",
      hx_assoc: "as_itch_throat",
      hx_risk: "rk_drug_allergy",
      ex_cardio: "cd_wheeze",
      ex_limb: "lb_urticaria",
      abga: "abga_lactic",
      pocus: "us_flat_ivc",
    },
    atypical: { hx_onset: "on_acute", hx_risk: "rk_none", ex_limb: "lb_normal" },
    effectiveness: { anaphylaxis_tx: "key", corticosteroid: "resistant", beta_blocker: "harmful" },
    definitive: [{ tags: ["anaphylaxis_tx"], text: "에피네프린: 기도 부종과 혈관 확장이 가라앉는다", effects: [clearSelf("aggravation"), { op: "damage", amount: 8, target: "target" }] }],
    // v2.1: 기도 부종 예고(아나필락시스만의 의도)를 없앴다. 기도 부종은 "호흡 악화(심각)"로 보이고, 일어난 뒤 입술·혀 부종이 경과 소견으로 남는다
    moves: [
      { id: "throat", nameKo: "목 조임", pressure: "respiratory", effects: [atk(5)] },
      { id: "spasm", nameKo: "기관지 수축", pressure: "respiratory", effects: [atk(4, 2)] },
      { id: "urticaria", nameKo: "두드러기 확산", pressure: "respiratory", effects: [atk(7)], course: "crs_urticaria" },
      { id: "vasodilation", nameKo: "혈관 확장", pressure: "worsening", effects: [toSelf("aggravation", 2), toPatient("hypotension", 1), atk(3)] },
      { id: "airway_edema", nameKo: "기도 부종", pressure: "respiratory", effects: [atk(14)], course: "crs_lip_swelling" },
    ],
    ai: { weights: { spasm: 40, urticaria: 25, throat: 20, airway_edema: 15 } },
    art: { region: "body", lesion: [0.5, 0.16, 0.08] },
    passiveText: ["에피네프린이 들으면 악화가 풀리고 질병 부담 8이 더 줄어든다."],
    medical: { fidelity: "unverified", note: "v2.1 변경: 기도 부종 예고 제거, 혈관 확장(저혈압) 행동과 경과 소견(입술·혀 부종, 두드러기 확산) 추가. 1차 치료는 에피네프린 근육주사. 스테로이드는 보조" },
  },
  {
    id: "stemi",
    nameKo: "ST분절 상승 심근경색",
    nameEn: "ST-elevation myocardial infarction",
    textbook: { keyFeatures: "30분 넘는 쥐어짜는 흉통과 식은땀, 심전도 ST 분절 상승, 트로포닌 상승. 재관류(중재술)가 결정적." },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "acs", "arterial_thrombus", "thrombolysable"],
    tier: "elite",
    act: 1,
    severity: [66, 72],
    findings: {
      vitals: "vt_tachy_distress",
      hx_onset: "on_crushing",
      hx_assoc: "as_radiating_sweat",
      hx_risk: "rk_vascular",
      lab_chem: "chem_troponin_high",
      ecg: "ecg_st_elev",
      pocus: "us_wall_motion",
    },
    atypical: { hx_assoc: "as_gi_upset", hx_onset: "on_acute" },
    effectiveness: { revascularization: "key", antiplatelet: "weak", anticoagulant: "weak", thrombolytic: "weak", defib: "harmful" },
    definitive: [{ tags: ["revascularization", "thrombolytic"], text: "재관류: 허혈 진행이 멈췄다", effects: [clearSelf("aggravation"), cancel] }],
    moves: [
      { id: "ischemic_pain", nameKo: "허혈성 흉통", pressure: "pain", effects: [atk(10)] },
      { id: "ischemia", nameKo: "허혈 진행", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(5)] },
      { id: "stunning", nameKo: "심근 기절", pressure: "hemodynamic", effects: [toPatient("vulnerable", 1), atk(5)] },
      { id: "cardiogenic_shock", nameKo: "심인성 쇼크", pressure: "hemodynamic", effects: [atk(14)] },
      { id: "lv_failure", nameKo: "급성 좌심부전", pressure: "respiratory", effects: [atk(8), toPatient("hypoxia", 1)] },
      { id: "epigastric_discomfort", nameKo: "명치 불편감", pressure: "pain", effects: [atk(5)] },
      { id: "vf_warning", nameKo: "심실 부정맥 위험", pressure: "complication", effects: [warn("vf_onset", 4)] },
      { id: "vf_onset", nameKo: "심실세동 발생", pressure: "cardiac", effects: [phase(1), atk(6)] },
    ],
    ai: { weights: { ischemic_pain: 45, ischemia: 30, stunning: 25 }, noRepeat: ["stunning"] },
    phases: [
      {
        id: "vf",
        nameKo: "심실세동",
        enterAtSeverityPct: 50,
        traitsAdd: ["arrhythmia", "shockable"],
        traitsRemove: ["acs", "arterial_thrombus", "thrombolysable"],
        findings: { ecg: "ecg_vf" },
        effectivenessOverride: {
          defib: "key",
          antiarrhythmic: "weak",
          vasopressor: "normal",
          antiplatelet: "resistant",
          anticoagulant: "resistant",
          thrombolytic: "resistant",
          revascularization: "resistant",
          beta_blocker: "immune",
        },
        moves: [
          { id: "vf", nameKo: "심실세동", pressure: "cardiac", effects: [atk(4, 3)] },
          { id: "arrest_warning", nameKo: "심정지 임박", pressure: "complication", effects: [warn("arrest", 2), atk(4)] },
          { id: "arrest", nameKo: "심정지", effects: [atk(18)] },
        ],
        onEnter: [{ op: "remove_status", status: "aggravation", target: "self", stacks: "all" }],
        course: "crs_vf",
        ai: { rules: [{ when: { noCountdown: true }, move: "arrest_warning" }], weights: { vf: 100 } },
      },
    ],
    art: { region: "chest", lesion: [0.56, 0.52, 0.1] },
    passiveText: ["질병 부담이 절반 이하로 떨어지면 심실세동으로 넘어간다."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 1차 PCI가 재관류의 표준. 맥박이 있는 리듬에 비동기 충격은 심실세동을 유발할 수 있다" },
  },
  {
    id: "stroke",
    nameKo: "급성 뇌경색",
    nameEn: "Acute ischemic stroke",
    textbook: { keyFeatures: "갑자기 시작한 한쪽 마비와 언어 장애. 혈전용해는 CT로 출혈을 배제한 뒤, 골든타임 안에만." },
    category: "neuro",
    traits: ["arterial_thrombus", "thrombolysable"],
    tier: "elite",
    act: 1,
    severity: [62, 68],
    findings: {
      vitals: "vt_hypertensive",
      hx_onset: "on_sudden",
      hx_assoc: "as_speech",
      hx_risk: "rk_vascular",
      ex_neuro: "nr_hemiparesis",
      ct: "ct_no_bleed_ischemia",
    },
    effectiveness: { thrombolytic: "key", revascularization: "key", antiplatelet: "normal", anticoagulant: "immune" },
    definitive: [{ tags: ["thrombolytic", "revascularization"], text: "재관류: 신경 손상 진행이 멈췄다", effects: [cancel, clearSelf("aggravation")] }],
    passives: [
      { on: "combat_start", effects: [warn("golden_time_end", 3)] },
      {
        on: "drug_administered",
        condition: { all: [{ eventDrugTag: "thrombolytic" }, { not: { channelObserved: "ct" } }] },
        effects: [{ op: "add_card", cardId: "bleeding", count: 1, dest: "hand" }, { op: "lose_vitality", amount: 6 }],
      },
    ],
    moves: [
      { id: "deficit", nameKo: "신경학적 결손", pressure: "neuro", effects: [atk(10)] },
      { id: "edema", nameKo: "뇌부종", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "aspiration", nameKo: "흡인", pressure: "neuro", effects: [atk(5), toPatient("hypoxia", 1)] },
      { id: "golden_time_end", nameKo: "골든타임 종료", pressure: "worsening", effects: [phase(1)] },
    ],
    ai: { weights: { deficit: 45, edema: 30, aspiration: 25 }, noRepeat: ["edema"] },
    phases: [
      {
        id: "late",
        nameKo: "골든타임 경과",
        traitsRemove: ["thrombolysable"],
        effectivenessOverride: { thrombolytic: "harmful", revascularization: "weak" },
      },
    ],
    art: { region: "head", lesion: [0.62, 0.38, 0.12] },
    passiveText: ["골든타임(3턴)이 지나면 혈전용해가 금기가 된다.", "CT 없이 혈전용해제를 쓰면 출혈 합병증(활력 −6, 손에 출혈)."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 정맥 혈전용해는 발병 4.5시간 이내, 비조영 CT로 출혈을 배제한 뒤. 혈전 제거술은 선택된 환자에서 24시간까지" },
  },
  {
    id: "ich",
    nameKo: "뇌내출혈",
    nameEn: "Intracerebral hemorrhage",
    textbook: { keyFeatures: "갑자기 시작한 한쪽 마비에 두통·구토와 처지는 의식, 고혈압·항응고제. 비조영 CT로 뇌경색과 가른다. 혈전용해·항혈전제는 금기, 혈압 조절과 항응고 역전." },
    category: "neuro",
    traits: ["intracranial_bleed", "hemorrhage"],
    tier: "elite",
    act: 1,
    severity: [62, 68],
    findings: {
      vitals: "vt_hypertensive",
      hx_onset: "on_sudden",
      hx_assoc: "as_headache_vomit",
      hx_risk: "rk_anticoag",
      ex_neuro: "nr_hemiparesis_drowsy",
      lab_coag: "coag_inr_high",
      ct: "ct_ich",
    },
    atypical: { hx_assoc: "as_speech", hx_risk: "rk_vascular" },
    effectiveness: { beta_blocker: "weak", transfusion: "normal", thrombolytic: "harmful", anticoagulant: "harmful", antiplatelet: "harmful" },
    definitive: [{ tags: ["beta_blocker"], text: "혈압 조절: 혈종이 더 커지지 않는다", effects: [cancel] }],
    passives: [{ on: "combat_start", effects: [warn("golden_time_end", 3)] }],
    moves: [
      { id: "headache", nameKo: "두통과 구토", pressure: "neuro", effects: [atk(10)] },
      { id: "drowsy", nameKo: "의식 저하", pressure: "neuro", effects: [atk(5), toPatient("weak", 1)] },
      { id: "mass_effect", nameKo: "종괴 효과", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "golden_time_end", nameKo: "혈종 확장", pressure: "worsening", effects: [phase(1), raise(8)], course: "crs_neuro_decline" },
    ],
    ai: { weights: { headache: 45, drowsy: 30, mass_effect: 25 }, noRepeat: ["mass_effect"] },
    phases: [{ id: "late", nameKo: "골든타임 경과" }],
    art: { region: "head", lesion: [0.42, 0.4, 0.12] },
    passiveText: ["3턴 뒤 혈종이 커진다(질병 부담 최대치 +8). 혈압 조절이 들으면 예고가 사라진다.", "혈전용해제·항응고제·항혈소판제는 금기."],
    medical: {
      fidelity: "unverified",
      note: "v2.1 신규. 뇌경색의 감별 대상. 초기 혈종 확장은 첫 몇 시간에 흔하고 수축기 혈압 강하(실제로는 니카르디핀·라베탈롤, 카드는 β차단제로 통합)와 항응고 역전(실제로는 PCC·비타민 K, 카드는 수혈로 통합)이 기본. 혈전용해는 금기",
    },
  },
  {
    id: "dka",
    nameKo: "당뇨병성 케톤산증",
    nameEn: "Diabetic ketoacidosis",
    textbook: { keyFeatures: "인슐린 중단 후 다음·다뇨, 구토, 쿠스마울 호흡, 고혈당과 케톤. 수액 → 칼륨 확인 → 인슐린. 유발 요인(감염)을 찾는다." },
    category: "metabolic",
    traits: ["hyperglycemia", "hypovolemia"],
    tier: "boss",
    act: 1,
    severity: [96, 96],
    findings: {
      vitals: "vt_kussmaul",
      hx_onset: "on_polyuria",
      hx_assoc: "as_thirst_vomit",
      hx_risk: "rk_insulin_missed",
      ex_abd: "ab_diffuse_mild",
      ex_limb: "lb_dry",
      ex_neuro: "nr_drowsy",
      lab_cbc: "cbc_leukocytosis",
      lab_chem: "chem_dka",
      lab_ua: "ua_glucose_ketones",
      abga: "abga_metabolic_acidosis",
    },
    effectiveness: { insulin: "key", fluid: "weak", corticosteroid: "harmful" },
    definitive: [{ tags: ["insulin"], text: "인슐린: 케톤 생성이 멈추고 순환 허탈 예고가 사라진다", effects: [clearSelf("acidosis"), cancel] }],
    passives: [
      { on: "combat_start", effects: [toSelf("acidosis", 2)] },
      { on: "drug_administered", condition: { eventDrugTag: "fluid" }, effects: [{ op: "remove_status", status: "acidosis", target: "self", stacks: 2 }] },
    ],
    variants: [
      { id: "unknown", weight: 50, nameKo: "유발 요인 불명" },
      {
        id: "infection",
        weight: 50,
        nameKo: "유발 요인: 요로 감염",
        organism: "mixed_community",
        findings: { lab_ua: "ua_pyuria", cx_urine: "cx_urine_community" },
        passives: [{ on: "enemy_turn_end", condition: { not: { activeDrugTag: "abx" } }, effects: [{ op: "heal", amount: 3, target: "self" }] }],
      },
    ],
    moves: [
      { id: "ketogenesis", nameKo: "케톤 생성", pressure: "metabolic", effects: [toSelf("acidosis", 1), block(5), atk(3)] },
      { id: "kussmaul", nameKo: "쿠스마울 호흡", pressure: "metabolic", effects: [atk(7)] },
      { id: "osmotic_diuresis", nameKo: "삼투성 이뇨", effects: [atk(4), toPatient("dehydration", 1)] },
      { id: "collapse_warning", nameKo: "순환 허탈 예고", effects: [warn("collapse", 3)] },
      { id: "collapse", nameKo: "순환 허탈", effects: [atk(16, 1, fluidHalf)] },
    ],
    ai: {
      opening: ["ketogenesis"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 3 }] }, move: "collapse_warning" }],
      weights: { kussmaul: 45, osmotic_diuresis: 25, ketogenesis: 30 },
      noRepeat: ["ketogenesis", "osmotic_diuresis"],
    },
    art: { region: "body", lesion: [0.5, 0.55, 0.18] },
    passiveText: [
      "산증: 공격에 산증 스택만큼 더한다. 수액을 투여할 때마다 −2.",
      "순환 허탈은 수액이 투여 중이면 절반.",
      "유발 요인이 감염이면 항생제 없이 매 턴 질병 부담 3이 다시 쌓인다. 소변 배양으로 찾는다.",
    ],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 수액 → 칼륨 확인 후 인슐린 → 혈당이 떨어지면 포도당 추가. 스테로이드는 고혈당을 악화시킨다. 감염은 흔한 유발 요인" },
  },
] satisfies DiseaseDef[];
