// 1막 응급실. design.md §5.5
import { addCard, atk, block, phase, raise, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef } from "../../core/types";

const fluidHalf = [{ if: { activeDrugTag: "fluid" }, pct: 50 }];

export const ACT1_DISEASES = [
  {
    id: "appendicitis",
    nameKo: "급성 충수염",
    nameEn: "Acute appendicitis",
    presentation: { complaint: "복통", clues: ["우하복부 압통과 반발통", "명치 통증이 오른쪽 아래로 이동", "38.1℃"] },
    category: "abdominal",
    traits: ["source", "us_visible"],
    tier: "normal",
    act: 1,
    severity: [42, 46],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    organism: "intra_abdominal",
    effectiveness: { source_control: "weak" },
    moves: [
      { id: "perf_warning", nameKo: "천공 위험", effects: [warn("perforation", 3), atk(6)] },
      { id: "perforation", nameKo: "천공", effects: [raise(15), toSelf("aggravation", 3)] },
      { id: "ache", nameKo: "통증", effects: [atk(11)] },
      { id: "local_inflammation", nameKo: "국소 염증", effects: [toSelf("inflammation", 2), atk(7)] },
    ],
    ai: { opening: ["perf_warning"], weights: { ache: 60, local_inflammation: 40 }, maxInARow: 2 },
    art: { region: "abdomen", lesion: [0.36, 0.64, 0.09] },
    passiveText: [],
    medical: { fidelity: "accurate", note: "천공은 치료 지연의 대표 합병증. 단순 충수염은 항생제 단독 치료도 가능(CODA)" },
  },
  {
    id: "gastroenteritis",
    nameKo: "급성 위장관염",
    nameEn: "Acute gastroenteritis",
    presentation: { complaint: "복통", clues: ["하루 여섯 번 물설사와 구토", "함께 식사한 가족도 같은 증상", "국소 압통 없음"] },
    category: "infection",
    traits: ["hypovolemia"],
    tier: "normal",
    act: 1,
    severity: [30, 34],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    organism: "virus",
    effectiveness: { fluid: "weak" },
    moves: [
      { id: "vomit", nameKo: "구토", effects: [atk(9), toPatient("dehydration", 1)] },
      { id: "diarrhea", nameKo: "설사", effects: [atk(5, 2)] },
      { id: "dehydration", nameKo: "탈수 진행", effects: [toPatient("dehydration", 2), toSelf("aggravation", 1), atk(3)] },
    ],
    ai: { weights: { vomit: 45, diarrhea: 35, dehydration: 20 }, noRepeat: ["dehydration"] },
    art: { region: "abdomen", lesion: [0.5, 0.58, 0.16] },
    medical: { fidelity: "accurate", note: "바이러스성은 항생제 무효. 수분 보충이 핵심" },
  },
  {
    id: "cap",
    nameKo: "지역사회획득 폐렴",
    nameEn: "Community-acquired pneumonia",
    presentation: { complaint: "발열", clues: ["누런 가래를 동반한 기침", "오른쪽 아래 폐의 수포음", "호흡수 24회"] },
    category: "infection",
    traits: ["chest", "resp_failure"],
    tier: "normal",
    act: 1,
    severity: [44, 48],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: {},
    variants: [
      { id: "pneumococcus", weight: 70, nameKo: "폐렴알균", organism: "pneumococcus" },
      { id: "atypical", weight: 30, nameKo: "비정형균(마이코플라스마)", organism: "atypical" },
    ],
    acquiredResistance: { tags: ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"], gainPerHit: 1 },
    moves: [
      { id: "cough", nameKo: "기침", effects: [atk(12)] },
      { id: "fever", nameKo: "고열", effects: [atk(8), toPatient("weak", 1)] },
      { id: "inflame", nameKo: "염증 반응", effects: [toSelf("inflammation", 3), atk(4)] },
    ],
    ai: { weights: { cough: 45, fever: 30, inflame: 25 }, noRepeat: ["inflame"] },
    art: { region: "chest", lesion: [0.34, 0.66, 0.12] },
    medical: { fidelity: "simplified", note: "비정형균은 베타락탐 무효. 국내 폐렴알균은 마크롤라이드 내성률이 높다" },
  },
  {
    id: "pyelo",
    nameKo: "급성 신우신염",
    nameEn: "Acute pyelonephritis",
    presentation: { complaint: "발열", clues: ["오한과 오른쪽 옆구리 통증", "오른쪽 늑척추각 압통", "사흘째 배뇨통"] },
    category: "infection",
    traits: ["renal"],
    tier: "normal",
    act: 1,
    severity: [40, 44],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: {},
    variants: [
      { id: "ecoli", weight: 75, nameKo: "대장균", organism: "ecoli" },
      { id: "esbl", weight: 25, nameKo: "ESBL 생성 대장균", organism: "esbl" },
    ],
    acquiredResistance: { tags: ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"], gainPerHit: 1 },
    moves: [
      { id: "rigor", nameKo: "오한", effects: [atk(6, 2)] },
      { id: "high_fever", nameKo: "고열", effects: [atk(13)] },
      { id: "abscess", nameKo: "신장 농양 형성", effects: [block(8), toSelf("aggravation", 1), atk(3)] },
    ],
    ai: { weights: { rigor: 40, high_fever: 40, abscess: 20 }, noRepeat: ["abscess"] },
    art: { region: "pelvis", lesion: [0.36, 0.38, 0.1] },
    medical: { fidelity: "simplified", note: "ESBL은 3세대 세팔로스포린 무효, 카바페넴이 1차" },
  },
  {
    id: "asthma",
    nameKo: "천식 급성 악화",
    nameEn: "Acute asthma exacerbation",
    presentation: { complaint: "호흡곤란", clues: ["숨을 내쉴 때 쌕쌕거림", "흡입기를 하루 여섯 번 사용", "SpO₂ 91%"] },
    category: "respiratory",
    traits: ["chest", "bronchospasm", "resp_failure"],
    tier: "normal",
    act: 1,
    severity: [34, 38],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { beta2_agonist: "weak", corticosteroid: "weak", anaphylaxis_tx: "resistant", beta_blocker: "harmful" },
    moves: [
      { id: "bronchospasm", nameKo: "기관지 연축", effects: [atk(7, 2)] },
      { id: "mucus", nameKo: "점액 마개", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "fatigue", nameKo: "호흡근 피로", effects: [toSelf("aggravation", 2), atk(4)] },
    ],
    ai: { weights: { bronchospasm: 45, mucus: 30, fatigue: 25 }, noRepeat: ["mucus", "fatigue"] },
    art: { region: "chest", lesion: [0.5, 0.45, 0.22] },
    medical: { fidelity: "accurate", note: "β차단제는 기관지 연축을 악화시킨다" },
  },
  {
    id: "anaphylaxis",
    nameKo: "아나필락시스",
    nameEn: "Anaphylaxis",
    presentation: { complaint: "호흡곤란", clues: ["조영제 주사 직후 전신 두드러기", "입술과 혀의 부종", "혈압 82/50"] },
    category: "allergic",
    traits: ["allergic", "bronchospasm", "shock", "hypovolemia"],
    tier: "normal",
    act: 1,
    severity: [22, 26],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { anaphylaxis_tx: "key", corticosteroid: "resistant", beta_blocker: "harmful" },
    moves: [
      { id: "hives_onset", nameKo: "두드러기", effects: [atk(4), warn("airway_edema", 2)] },
      { id: "airway_edema", nameKo: "기도 부종", effects: [atk(22)] },
      { id: "angioedema", nameKo: "혈관 부종", effects: [atk(8)] },
      { id: "spasm", nameKo: "기관지 수축", effects: [atk(4, 2)] },
    ],
    ai: { opening: ["hives_onset"], weights: { angioedema: 50, spasm: 50 } },
    art: { region: "body", lesion: [0.5, 0.16, 0.08] },
    medical: { fidelity: "accurate", note: "1차 치료는 에피네프린 근육주사. 스테로이드는 보조. β차단제 복용자는 에피네프린 반응이 약하다" },
  },
  {
    id: "stemi",
    nameKo: "ST분절 상승 심근경색",
    nameEn: "ST-elevation myocardial infarction",
    presentation: { complaint: "흉통", clues: ["30분 넘게 쥐어짜는 가슴 통증과 식은땀", "심전도 II·III·aVF ST 분절 상승", "당뇨 20년"] },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "acs", "arterial_thrombus", "thrombolysable"],
    tier: "elite",
    act: 1,
    severity: [66, 72],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { revascularization: "key", antiplatelet: "weak", anticoagulant: "weak", thrombolytic: "weak", defib: "harmful" },
    moves: [
      { id: "ischemic_pain", nameKo: "허혈성 흉통", effects: [atk(12)] },
      { id: "ischemia", nameKo: "허혈 진행", effects: [toSelf("aggravation", 2), atk(6)] },
      { id: "stunning", nameKo: "심근 기절", effects: [toPatient("vulnerable", 1), atk(6)] },
    ],
    ai: { weights: { ischemic_pain: 45, ischemia: 30, stunning: 25 }, noRepeat: ["stunning"] },
    phases: [
      {
        id: "vf",
        nameKo: "심실세동",
        enterAtSeverityPct: 50,
        traitsAdd: ["arrhythmia", "shockable"],
        traitsRemove: ["acs", "arterial_thrombus", "thrombolysable"],
        effectivenessOverride: {
          defib: "key",
          antiarrhythmic: "weak",
          vasopressor: "normal",
          antiplatelet: "resistant",
          anticoagulant: "resistant",
          thrombolytic: "resistant",
          revascularization: "resistant",
          beta_blocker: "immune",
        },
        moves: [
          { id: "vf", nameKo: "심실세동", effects: [atk(4, 3)] },
          { id: "arrest_warning", nameKo: "심정지 임박", effects: [warn("arrest", 2), atk(4)] },
          { id: "arrest", nameKo: "심정지", effects: [atk(20)] },
        ],
        onEnter: [{ op: "remove_status", status: "aggravation", target: "self", stacks: "all" }],
        ai: { rules: [{ when: { noCountdown: true }, move: "arrest_warning" }], weights: { vf: 100 } },
      },
    ],
    art: { region: "chest", lesion: [0.56, 0.52, 0.1] },
    passiveText: ["중증도가 절반 이하로 떨어지면 심실세동으로 넘어간다."],
    medical: { fidelity: "accurate", note: "1차 PCI가 재관류의 표준. 맥박이 있는 리듬에 비동기 충격은 심실세동을 유발할 수 있다" },
  },
  {
    id: "stroke",
    nameKo: "급성 뇌경색",
    nameEn: "Acute ischemic stroke",
    presentation: { complaint: "편측 마비", clues: ["1시간 전 시작된 왼쪽 팔다리 마비", "말이 어눌하고 시선이 오른쪽으로 쏠림", "혈당 132"] },
    category: "neuro",
    traits: ["arterial_thrombus", "thrombolysable"],
    tier: "elite",
    act: 1,
    severity: [62, 68],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { thrombolytic: "key", revascularization: "key", antiplatelet: "normal", anticoagulant: "immune" },
    passives: [{ on: "combat_start", effects: [warn("golden_time_end", 3)] }],
    moves: [
      { id: "deficit", nameKo: "신경학적 결손", effects: [atk(12)] },
      { id: "edema", nameKo: "뇌부종", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "aspiration", nameKo: "흡인", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "golden_time_end", nameKo: "골든타임 종료", effects: [phase(1)] },
    ],
    ai: { weights: { deficit: 45, edema: 30, aspiration: 25 }, noRepeat: ["edema"] },
    phases: [
      {
        id: "late",
        nameKo: "골든타임 경과",
        traitsRemove: ["thrombolysable"],
        effectivenessOverride: { thrombolytic: "harmful", revascularization: "weak" },
      },
    ],
    art: { region: "head", lesion: [0.62, 0.38, 0.12] },
    passiveText: ["골든타임(3턴)이 지나면 혈전용해가 금기가 된다."],
    medical: { fidelity: "accurate", note: "정맥 혈전용해는 발병 4.5시간 이내. 이후에는 출혈 위험이 크다. 혈전 제거술은 선택된 환자에서 24시간까지" },
  },
  {
    id: "dka",
    nameKo: "당뇨병성 케톤산증",
    nameEn: "Diabetic ketoacidosis",
    presentation: { complaint: "복통", clues: ["구토와 깊고 빠른 호흡", "과일 냄새 나는 날숨", "혈당 486, 소변 케톤 3+"] },
    category: "metabolic",
    traits: ["hyperglycemia", "hypovolemia"],
    tier: "boss",
    act: 1,
    severity: [100, 100],
    diagnosis: { partialAt: 3, confirmAt: 5 },
    effectiveness: { insulin: "key", fluid: "weak", corticosteroid: "harmful" },
    passives: [
      { on: "combat_start", effects: [toSelf("acidosis", 2)] },
      { on: "drug_administered", condition: { eventDrugTag: "fluid" }, effects: [{ op: "remove_status", status: "acidosis", target: "self", stacks: 2 }] },
    ],
    variants: [
      { id: "unknown", weight: 50, nameKo: "유발 요인 불명" },
      {
        id: "infection",
        weight: 50,
        nameKo: "유발 요인: 감염",
        organism: "mixed_community",
        passives: [{ on: "enemy_turn_end", condition: { not: { activeDrugTag: "abx" } }, effects: [{ op: "heal", amount: 3, target: "self" }] }],
      },
    ],
    moves: [
      { id: "ketogenesis", nameKo: "케톤 생성", effects: [toSelf("acidosis", 1), block(5), atk(3)] },
      { id: "kussmaul", nameKo: "쿠스마울 호흡", effects: [atk(7)] },
      { id: "osmotic_diuresis", nameKo: "삼투성 이뇨", effects: [atk(4), toPatient("dehydration", 1)] },
      { id: "collapse_warning", nameKo: "순환 허탈 예고", effects: [warn("collapse", 3)] },
      { id: "collapse", nameKo: "순환 허탈", effects: [atk(16, 1, fluidHalf)] },
    ],
    ai: {
      opening: ["ketogenesis"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 3 }] }, move: "collapse_warning" }],
      weights: { kussmaul: 45, osmotic_diuresis: 25, ketogenesis: 30 },
      noRepeat: ["ketogenesis", "osmotic_diuresis"],
    },
    art: { region: "body", lesion: [0.5, 0.55, 0.18] },
    passiveText: ["산증: 공격에 산증 스택만큼 더한다. 수액을 투여할 때마다 −2.", "순환 허탈은 수액이 투여 중이면 절반.", "유발 요인이 감염이면 항생제 없이 매 턴 중증도 3을 회복한다."],
    medical: { fidelity: "accurate", note: "수액 → 칼륨 확인 후 인슐린 → 혈당이 떨어지면 포도당 추가. 스테로이드는 고혈당을 악화시킨다" },
  },
] satisfies DiseaseDef[];

void addCard;
