// 2막 병동. design.md §5.5
import { addCard, atk, block, raise, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef, EffectOp } from "../../core/types";

const ALL_ABX = ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"];
const anticoagHalf = [{ if: { activeDrugTag: "anticoagulant" }, pct: 50 }];
const cancel: EffectOp = { op: "cancel_countdowns", target: "target" };
const clearSelf = (status: string): EffectOp => ({ op: "remove_status", status, target: "target", stacks: "all" });

export const ACT2_DISEASES = [
  {
    id: "cellulitis",
    nameKo: "봉와직염",
    nameEn: "Cellulitis",
    textbook: { keyFeatures: "경계가 불분명하게 번지는 발적·열감, 발열. 주사 자리에서 시작하기도 한다. MRSA 위험이 있으면 반코마이신." },
    category: "infection",
    traits: ["source"],
    tier: "normal",
    act: 2,
    severity: [48, 54],
    findings: {
      vitals: "vt_lowgrade",
      hx_onset: "on_days",
      hx_assoc: "as_leg_hot",
      hx_risk: "rk_iv_site",
      ex_limb: "lb_spreading_erythema",
      lab_cbc: "cbc_leukocytosis",
      pocus: "us_cobblestone",
      ct: "ct_cellulitis",
      cx_wound: "cx_wound_mssa",
    },
    atypical: { hx_risk: "rk_none", hx_onset: "on_acute", ex_limb: "lb_unilateral_calf" },
    effectiveness: {},
    variants: [
      { id: "mssa", weight: 60, nameKo: "연쇄알균·MSSA", organism: "mssa_strep" },
      { id: "mrsa", weight: 40, nameKo: "MRSA", organism: "mrsa", findings: { hx_risk: "rk_recent_hosp_abx", cx_wound: "cx_wound_mrsa" } },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    definitive: [{ tags: ["abx"], text: "항생제가 들어 고름집이 생기지 않는다", effects: [cancel] }],
    moves: [
      { id: "spread", nameKo: "발적 확산", pressure: "infection", effects: [atk(10)] },
      { id: "chills", nameKo: "오한", pressure: "infection", effects: [atk(5)] },
      { id: "leg_pain", nameKo: "다리 통증", pressure: "pain", effects: [atk(9)] },
      { id: "inflame", nameKo: "염증", pressure: "worsening", effects: [toSelf("inflammation", 3), atk(5)] },
      { id: "lymphangitis", nameKo: "림프관염", pressure: "pain", effects: [atk(6), toPatient("vulnerable", 1)] },
      { id: "abscess_warning", nameKo: "고름집 형성 위험", pressure: "complication", effects: [warn("abscess", 3)] },
      { id: "abscess", nameKo: "고름집 형성", pressure: "worsening", effects: [raise(10), toSelf("aggravation", 2)] },
    ],
    ai: { weights: { spread: 45, inflame: 30, lymphangitis: 25 }, noRepeat: ["inflame"] },
    art: { region: "leg", lesion: [0.4, 0.56, 0.11] },
    passiveText: ["듣는 항생제가 들어가면 고름집 형성 예고가 사라진다."],
    medical: { fidelity: "unverified", note: "v2.1 변경: 고름집 형성 예고(항생제가 들으면 취소)와 다리 통증·오한 행동 추가. MRSA에는 베타락탐 무효(세프타롤린 예외 생략). 농양이 있으면 절개 배농" },
  },
  {
    id: "dvt",
    nameKo: "심부정맥 혈전증",
    nameEn: "Deep vein thrombosis",
    textbook: { keyFeatures: "침상 안정·수술 뒤 한쪽 종아리만 붓고 당김, 열 없음, D-dimer 상승. 초음파로 정맥이 눌리지 않는다. 항응고가 1차." },
    category: "thrombotic",
    traits: ["venous_thrombus", "us_visible"],
    tier: "normal",
    act: 2,
    severity: [50, 56],
    findings: {
      vitals: "vt_lowgrade",
      hx_onset: "on_days",
      hx_assoc: "as_leg_ache",
      hx_risk: "rk_immobile_postop",
      ex_limb: "lb_unilateral_calf",
      lab_coag: "coag_ddimer_high",
      pocus: "us_dvt",
      ct: "ct_venous_clot",
    },
    atypical: { hx_risk: "rk_none", hx_assoc: "as_leg_hot" },
    effectiveness: { anticoagulant: "weak", thrombolytic: "resistant", antiplatelet: "immune" },
    definitive: [{ tags: ["anticoagulant"], text: "항응고: 혈전이 떨어져 나갈 위험을 막았다", effects: [cancel] }],
    moves: [
      { id: "embolus_warning", nameKo: "혈전 이동 위험", pressure: "complication", effects: [warn("embolism", 3)] },
      { id: "embolism", nameKo: "색전", pressure: "hemodynamic", effects: [atk(22, 1, anticoagHalf)] },
      { id: "swelling", nameKo: "부종", pressure: "pain", effects: [atk(8)] },
      { id: "calf_ache", nameKo: "종아리 당김", pressure: "pain", effects: [atk(5)] },
      { id: "clot_growth", nameKo: "혈전 성장", pressure: "worsening", effects: [block(8), toSelf("aggravation", 1), atk(4)] },
    ],
    ai: { opening: ["embolus_warning"], weights: { swelling: 60, clot_growth: 40 }, noRepeat: ["clot_growth"] },
    art: { region: "leg", lesion: [0.6, 0.7, 0.08] },
    passiveText: ["색전은 항응고제가 투여 중이면 절반. 항응고가 들으면 예고가 사라진다."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 항응고가 1차. 단순 DVT에 혈전용해는 권고되지 않는다. 항혈소판제는 치료가 아니다" },
  },
  {
    id: "chf",
    nameKo: "급성 심부전 악화",
    nameEn: "Acute decompensated heart failure",
    textbook: { keyFeatures: "누우면 숨참(기좌호흡), 양쪽 수포음·목정맥 팽창, 다리 부종, BNP 상승. 이뇨제. 수액과 β차단제 신규 시작은 해롭다." },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "volume_overload", "resp_failure", "us_visible"],
    tier: "normal",
    act: 2,
    severity: [50, 56],
    findings: {
      vitals: "vt_hypertensive_hypox",
      hx_onset: "on_orthopnea",
      hx_assoc: "as_edema_weight",
      hx_risk: "rk_heart_failure",
      ex_cardio: "cd_bibasal_jvd",
      ex_limb: "lb_bilateral_pitting",
      lab_chem: "chem_bnp_high",
      abga: "abga_hypoxemia",
      ecg: "ecg_sinus_tachy",
      xray: "xr_pulm_edema",
      pocus: "us_blines_plump_ivc",
      ct: "ct_pulm_edema",
    },
    atypical: { hx_risk: "rk_none", hx_onset: "on_days", ex_cardio: "cd_wheeze" },
    effectiveness: { loop_diuretic: "weak", fluid: "harmful", beta_blocker: "harmful", vasopressor: "resistant" },
    definitive: [{ tags: ["loop_diuretic"], text: "이뇨: 폐부종이 빠진다", effects: [clearSelf("aggravation")] }],
    moves: [
      { id: "pulmonary_edema", nameKo: "폐부종", pressure: "respiratory", effects: [atk(12)] },
      { id: "congestion", nameKo: "울혈 악화", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(5)] },
      { id: "dyspnea", nameKo: "호흡곤란", pressure: "respiratory", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "low_flow", nameKo: "신혈류 감소", pressure: "renal", effects: [atk(9)] },
      { id: "oliguria", nameKo: "소변 감소", pressure: "renal", effects: [atk(5), toPatient("weak", 1)] },
    ],
    ai: { weights: { pulmonary_edema: 40, congestion: 30, dyspnea: 30 }, noRepeat: ["congestion"] },
    art: { region: "chest", lesion: [0.5, 0.62, 0.22] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 급성 악화기의 수액과 β차단제 신규 시작은 해롭다" },
  },
  {
    id: "he",
    nameKo: "간성뇌증",
    nameEn: "Hepatic encephalopathy",
    textbook: { keyFeatures: "간경변 환자가 며칠에 걸쳐 졸리고 엉뚱해짐, 퍼덕떨림, 변비, 암모니아 상승. 락툴로오스. 진정제는 악화." },
    category: "neuro",
    traits: ["hyperammonemia"],
    tier: "normal",
    act: 2,
    severity: [42, 48],
    findings: {
      vitals: "vt_calm_confused",
      hx_onset: "on_somnolence",
      hx_assoc: "as_constipation",
      hx_risk: "rk_cirrhosis",
      ex_neuro: "nr_asterixis",
      ex_abd: "ab_ascites",
      ex_limb: "lb_jaundice",
      lab_cbc: "cbc_low_platelet",
      lab_chem: "chem_ammonia_high",
      lab_coag: "coag_prolonged_pt",
    },
    atypical: { hx_assoc: "as_none", ex_abd: "ab_soft", ex_neuro: "nr_inattention" },
    effectiveness: { ammonia_lowering: "weak", cns_depressant: "harmful" },
    definitive: [{ tags: ["ammonia_lowering"], text: "암모니아가 떨어지며 의식이 맑아진다", effects: [{ op: "exhaust_cards", from: ["hand", "draw", "discard"], filter: { ids: ["confusion"] }, amount: "all" }] }],
    moves: [
      { id: "obtundation", nameKo: "의식 저하", pressure: "neuro", effects: [addCard("confusion", 1, "draw_random"), atk(5)] },
      { id: "asterixis", nameKo: "퍼덕떨림", pressure: "neuro", effects: [atk(9)] },
      { id: "ammonia", nameKo: "암모니아 축적", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
    ],
    ai: { weights: { obtundation: 35, asterixis: 45, ammonia: 20 }, noRepeat: ["obtundation", "ammonia"] },
    art: { region: "head", lesion: [0.5, 0.42, 0.22] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 벤조디아제핀·오피오이드는 간성뇌증을 유발·악화시킨다" },
  },
  {
    id: "delirium",
    nameKo: "섬망",
    nameEn: "Delirium",
    textbook: { keyFeatures: "고령 입원 환자의 주의력 저하, 밤에 심해지는 초조, 오락가락하는 의식. 검사는 대개 정상. 벤조디아제핀은 악화." },
    category: "neuro",
    traits: ["agitation"],
    tier: "normal",
    act: 2,
    severity: [38, 42],
    findings: {
      vitals: "vt_calm_confused",
      hx_onset: "on_nocturnal",
      hx_assoc: "as_agitation",
      hx_risk: "rk_elderly_sedative",
      ex_neuro: "nr_inattention",
    },
    atypical: { hx_onset: "on_somnolence", hx_assoc: "as_none" },
    effectiveness: { antipsychotic: "weak", benzodiazepine: "harmful" },
    moves: [
      { id: "night_agitation", nameKo: "야간 초조", pressure: "neuro", effects: [atk(6), addCard("confusion", 1, "discard")] },
      { id: "inattention", nameKo: "주의력 저하", pressure: "worsening", effects: [toPatient("weak", 1), toSelf("aggravation", 1), atk(4)] },
      { id: "wandering", nameKo: "배회", pressure: "neuro", effects: [atk(4, 2)] },
    ],
    ai: { weights: { night_agitation: 40, inattention: 25, wandering: 35 }, noRepeat: ["inattention"] },
    art: { region: "head", lesion: [0.5, 0.36, 0.18] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). 항정신병제는 초조 조절용이며 섬망 기간 단축 근거는 약하다. 벤조디아제핀은 알코올 금단 외에는 악화 요인" },
  },
  {
    id: "cdi",
    nameKo: "C. difficile 감염",
    nameEn: "Clostridioides difficile infection",
    textbook: { keyFeatures: "항생제 치료 중 시작한 잦은 물설사, 아랫배 통증, 백혈구 크게 상승. 대변 독소 검사로 확인. 원인 항생제·PPI는 악화 요인." },
    category: "infection",
    traits: ["hypovolemia"],
    tier: "normal",
    act: 2,
    severity: [46, 52],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_days",
      hx_assoc: "as_watery_cramp",
      hx_risk: "rk_abx_course",
      ex_abd: "ab_lower_cramping",
      ex_limb: "lb_dry",
      lab_cbc: "cbc_marked_leuko",
      lab_chem: "chem_prerenal",
      stool: "stool_cdiff_toxin",
      ct: "ct_colitis",
    },
    organism: "cdiff",
    atypical: { hx_risk: "rk_recent_hosp_abx", lab_cbc: "cbc_leukocytosis", hx_assoc: "as_vomit_diarrhea" },
    effectiveness: { cdi_risk: "harmful" },
    passives: [{ on: "drug_administered", condition: { eventDrugTag: "cdi_risk" }, effects: [toSelf("aggravation", 2)] }],
    moves: [
      { id: "watery", nameKo: "수양성 설사", pressure: "hemodynamic", effects: [atk(5, 2)] },
      { id: "toxin", nameKo: "독소", pressure: "hemodynamic", effects: [atk(5), toPatient("dehydration", 1)] },
      { id: "colitis", nameKo: "대장염 악화", pressure: "worsening", effects: [toSelf("inflammation", 2), toSelf("aggravation", 1), atk(4)] },
      { id: "toxemia", nameKo: "독소혈증", pressure: "infection", effects: [atk(10)] },
      { id: "fever", nameKo: "발열", pressure: "infection", effects: [atk(5)] },
    ],
    ai: { weights: { watery: 40, toxin: 35, colitis: 25 }, noRepeat: ["colitis"] },
    art: { region: "abdomen", lesion: [0.5, 0.68, 0.18] },
    passiveText: ["C. diff 위험 약물(광범위 항생제, 세프트리악손, 퀴놀론, PPI)이 투여될 때마다 악화 +2."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). 현재 1차는 피닥소마이신 또는 경구 반코마이신(정맥 투여는 대장에 도달하지 않음, 카드는 경로 구분 생략). 원인 항생제·PPI 지속은 악화 요인" },
  },
  {
    id: "af",
    nameKo: "심방세동 빠른 심실 반응",
    nameEn: "Atrial fibrillation with rapid ventricular response",
    textbook: { keyFeatures: "불규칙하게 불규칙한 빠른 맥박, 두근거림, 수술 뒤 흔함. 박동수 조절, 불안정하면 심율동 전환, 색전 예방에 항응고." },
    category: "cardiovascular",
    traits: ["cardiac", "arrhythmia", "shockable"],
    tier: "normal",
    act: 2,
    severity: [42, 46],
    findings: {
      vitals: "vt_irregular_tachy",
      hx_onset: "on_acute",
      hx_assoc: "as_palpitations",
      hx_risk: "rk_cardiac_surgery",
      ex_cardio: "cd_irregular",
      ecg: "ecg_af_rvr",
    },
    effectiveness: { antiarrhythmic: "weak", beta_blocker: "weak", defib: "normal", anticoagulant: "resistant" },
    definitive: [
      { tags: ["antiarrhythmic", "beta_blocker"], text: "박동수 조절: 심장 부담이 줄었다", effects: [clearSelf("aggravation")] },
      { tags: ["anticoagulant"], text: "항응고: 좌심방 혈전의 색전을 막았다", effects: [cancel] },
    ],
    moves: [
      { id: "rvr", nameKo: "빠른 심실 반응", pressure: "cardiac", hitsRange: [2, 3], effects: [atk(4, 3)] },
      { id: "low_output", nameKo: "심박출 저하", pressure: "hemodynamic", effects: [atk(6), toPatient("vulnerable", 1)] },
      { id: "strain", nameKo: "심근 부담", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "thrombus_warning", nameKo: "좌심방 혈전", pressure: "complication", effects: [warn("embolic_stroke", 4)] },
      { id: "embolic_stroke", nameKo: "색전성 뇌졸중", pressure: "neuro", effects: [atk(18, 1, anticoagHalf)] },
    ],
    ai: {
      opening: ["rvr"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "thrombus_warning", once: true }],
      weights: { rvr: 60, low_output: 40 },
      noRepeat: ["low_output"],
    },
    art: { region: "chest", lesion: [0.58, 0.46, 0.09] },
    passiveText: ["색전성 뇌졸중은 항응고제가 투여 중이면 절반."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). 박동수 조절이 1차, 불안정하면 전기적 심율동 전환(카드는 제세동으로 통합). 항응고는 뇌졸중 예방" },
  },
  {
    id: "pe",
    nameKo: "폐색전증",
    nameEn: "Pulmonary embolism",
    textbook: { keyFeatures: "갑자기 시작한 숨참과 흉막성 흉통, 폐는 깨끗한데 저산소, 수술·침상 안정 뒤. CT 폐동맥 조영으로 확인. 항응고, 쇼크면 혈전용해." },
    category: "thrombotic",
    traits: ["chest", "venous_thrombus", "thrombolysable", "shock"],
    tier: "elite",
    act: 2,
    severity: [78, 84],
    findings: {
      vitals: "vt_tachy_distress",
      hx_onset: "on_sudden",
      hx_assoc: "as_pleuritic",
      hx_risk: "rk_immobile_postop",
      ex_cardio: "cd_tachy_clear",
      ex_limb: "lb_unilateral_calf",
      lab_chem: "chem_troponin_mild",
      lab_coag: "coag_ddimer_high",
      ecg: "ecg_s1q3t3",
      abga: "abga_hypoxemia",
      pocus: "us_rv_dilation",
      ct: "ct_pe",
    },
    atypical: { hx_assoc: "as_none", ex_limb: "lb_normal", ex_cardio: "cd_crackles_focal" },
    effectiveness: { anticoagulant: "weak", thrombolytic: "weak", fluid: "resistant", antiplatelet: "immune" },
    definitive: [
      { tags: ["thrombolytic"], text: "혈전용해: 우심실 부담이 풀렸다", effects: [clearSelf("aggravation"), { op: "damage", amount: 10, target: "target" }] },
      { tags: ["anticoagulant"], text: "항응고: 혈전이 더 자라지 않고 재발 위험이 줄었다", effects: [clearSelf("aggravation"), cancel] },
    ],
    moves: [
      { id: "rv_strain", nameKo: "급성 우심부전", pressure: "hemodynamic", effects: [atk(13)] },
      { id: "obstruction", nameKo: "폐혈류 차단", pressure: "hemodynamic", effects: [atk(10)] },
      { id: "hypoxemia", nameKo: "저산소혈증", pressure: "respiratory", effects: [atk(7), toPatient("hypoxia", 1)] },
      { id: "tachypnea", nameKo: "빠른 호흡", pressure: "respiratory", effects: [atk(5)] },
      { id: "pleuritic_pain", nameKo: "흉막성 흉통", pressure: "pain", effects: [atk(9)] },
      { id: "tachycardia", nameKo: "빈맥", pressure: "cardiac", effects: [atk(9)] },
      { id: "presyncope", nameKo: "실신할 듯함", pressure: "hemodynamic", effects: [atk(5), toPatient("vulnerable", 1)] },
      { id: "recurrent_warning", nameKo: "색전 재발 위험", pressure: "complication", effects: [warn("recurrent_embolus", 4)] },
      { id: "recurrent_embolus", nameKo: "색전 재발", pressure: "hemodynamic", effects: [atk(18, 1, anticoagHalf)], course: "crs_recurrent_embolus" },
      { id: "clot_burden", nameKo: "혈전 추가", pressure: "worsening", effects: [toSelf("aggravation", 2), block(8), atk(4)] },
    ],
    ai: { weights: { rv_strain: 40, hypoxemia: 35, clot_burden: 25 }, noRepeat: ["clot_burden"] },
    art: { region: "chest", lesion: [0.4, 0.46, 0.13] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 고위험 폐색전증은 혈전용해. 우심실 과부하에서 대량 수액은 해롭다" },
  },
  {
    id: "pancreatitis",
    nameKo: "중증 급성 췌장염",
    nameEn: "Severe acute pancreatitis",
    textbook: { keyFeatures: "과음 뒤 등으로 뻗치는 명치 통증과 구토, 리파아제 크게 상승. 초기 수액이 핵심. 예방적 항생제는 쓰지 않는다." },
    category: "abdominal",
    traits: ["hypovolemia"],
    tier: "elite",
    act: 2,
    severity: [80, 86],
    findings: {
      vitals: "vt_fever_tachy",
      hx_onset: "on_acute",
      hx_assoc: "as_vomit_back",
      hx_risk: "rk_alcohol",
      ex_abd: "ab_epigastric_guarding",
      lab_cbc: "cbc_leukocytosis",
      lab_chem: "chem_lipase_high",
      pocus: "us_flat_ivc",
      ct: "ct_pancreatitis",
    },
    atypical: { hx_risk: "rk_none", hx_assoc: "as_gi_upset" },
    effectiveness: { fluid: "weak" },
    definitive: [{ tags: ["fluid"], text: "조기 수액: 괴사 진행을 막았다", effects: [cancel] }],
    moves: [
      { id: "epigastric", nameKo: "상복부 통증", pressure: "pain", effects: [atk(11)] },
      { id: "sirs", nameKo: "전신 염증 반응", pressure: "worsening", effects: [toSelf("inflammation", 3), atk(4)] },
      { id: "back_pain", nameKo: "등으로 뻗치는 통증", pressure: "pain", effects: [atk(5)] },
      { id: "vomiting", nameKo: "반복 구토", pressure: "hemodynamic", effects: [atk(7), toPatient("dehydration", 1)] },
      { id: "ileus", nameKo: "장마비", effects: [atk(5), addCard("nausea", 2, "discard")] },
      { id: "necrosis_warning", nameKo: "괴사 진행", effects: [warn("necrosis", 4)] },
      { id: "necrosis", nameKo: "췌장 괴사", effects: [raise(10), toSelf("aggravation", 2)] },
    ],
    ai: {
      opening: ["epigastric"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "necrosis_warning", once: true }],
      weights: { epigastric: 40, sirs: 30, ileus: 30 },
      noRepeat: ["sirs", "ileus"],
    },
    art: { region: "abdomen", lesion: [0.54, 0.44, 0.1] },
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: simplified). 초기 수액이 핵심이나 과도한 수액은 해롭다. 예방적 항생제는 권고되지 않는다(원인균 없음 → 항생제 무효)" },
  },
  {
    id: "ugib",
    nameKo: "대량 상부위장관 출혈",
    nameEn: "Massive upper gastrointestinal bleeding",
    textbook: { keyFeatures: "토혈·흑색변, NSAID 복용, 혈색소 급감. 수혈·PPI로 버티고 내시경으로 지혈한다. 항혈전제는 금기." },
    category: "bleeding",
    traits: ["gi_bleed", "hemorrhage", "hypovolemia"],
    tier: "gate",
    act: 2,
    severity: [136, 136],
    findings: {
      vitals: "vt_hematemesis",
      hx_onset: "on_acute",
      hx_assoc: "as_melena",
      hx_risk: "rk_nsaid",
      ex_abd: "ab_epigastric_mild",
      lab_cbc: "cbc_anemia_acute",
      lab_chem: "chem_bun_high",
      pocus: "us_flat_ivc",
    },
    effectiveness: {
      endoscopy: "key",
      transfusion: "weak",
      ppi: "weak",
      vasopressor: "resistant",
      anticoagulant: "harmful",
      antiplatelet: "harmful",
      thrombolytic: "harmful",
      beta_blocker: "harmful",
    },
    definitive: [{ tags: ["endoscopy"], text: "내시경 지혈: 출혈이 멎고 재출혈 예고가 사라졌다", effects: [cancel, clearSelf("active_bleeding")] }],
    passives: [
      { on: "combat_start", effects: [toSelf("active_bleeding", 1)] },
      { on: "turn_start", condition: { hasStatus: { target: "self", status: "active_bleeding" } }, effects: [{ op: "lose_vitality", amount: 1 }] },
    ],
    moves: [
      { id: "hematemesis", nameKo: "토혈", pressure: "bleeding", effects: [atk(12)] },
      { id: "hypovolemic", nameKo: "저혈량 쇼크", effects: [toPatient("hypotension", 1), atk(5)] },
      { id: "rebleed_warning", nameKo: "재출혈 예고", effects: [warn("rebleed", 3)] },
      { id: "rebleed", nameKo: "재출혈", effects: [atk(20), addCard("bleeding", 2, "discard")] },
      { id: "coagulopathy", nameKo: "응고 장애", pressure: "worsening", effects: [toSelf("aggravation", 2), block(10)] },
      { id: "melena", nameKo: "흑색변", pressure: "bleeding", effects: [atk(5)] },
    ],
    ai: {
      opening: ["hematemesis"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "rebleed_warning" }],
      weights: { hematemesis: 40, hypovolemic: 30, coagulopathy: 30 },
      noRepeat: ["hypovolemic", "coagulopathy"],
    },
    art: { region: "abdomen", lesion: [0.46, 0.36, 0.1] },
    passiveText: ["활동성 출혈: 턴이 시작될 때마다 활력 −1. 내시경 지혈로 멈춘다."],
    medical: { fidelity: "unverified", note: "v2.0에서 소견·감별·결정적 치료·압박이 새로 붙음(v1.1 표시: accurate). 소화성 궤양 출혈은 내시경 지혈 + PPI, 제한적 수혈. 항혈전제는 금기" },
  },
] satisfies DiseaseDef[];
