// 2막 병동. design.md §5.5
import { addCard, atk, block, raise, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef } from "../../core/types";

const ALL_ABX = ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"];
const anticoagHalf = [{ if: { activeDrugTag: "anticoagulant" }, pct: 50 }];

export const ACT2_DISEASES = [
  {
    id: "cellulitis",
    nameKo: "봉와직염",
    nameEn: "Cellulitis",
    presentation: { complaint: "다리 부종", clues: ["정맥주사 자리 주변으로 번지는 붉은 부기", "경계가 불분명한 발적과 열감", "38.4℃"] },
    category: "infection",
    traits: ["source"],
    tier: "normal",
    act: 2,
    severity: [48, 54],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: {},
    variants: [
      { id: "mssa", weight: 60, nameKo: "연쇄알균·MSSA", organism: "mssa_strep" },
      { id: "mrsa", weight: 40, nameKo: "MRSA", organism: "mrsa" },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    moves: [
      { id: "spread", nameKo: "발적 확산", effects: [atk(9)] },
      { id: "inflame", nameKo: "염증", effects: [toSelf("inflammation", 3)] },
      { id: "lymphangitis", nameKo: "림프관염", effects: [atk(5), toPatient("vulnerable", 1)] },
    ],
    ai: { weights: { spread: 45, inflame: 30, lymphangitis: 25 }, noRepeat: ["inflame"] },
    art: { region: "leg", lesion: [0.4, 0.56, 0.11] },
    medical: { fidelity: "simplified", note: "MRSA에는 베타락탐 무효(세프타롤린 예외 생략). 농양이 있으면 절개 배농" },
  },
  {
    id: "dvt",
    nameKo: "심부정맥 혈전증",
    nameEn: "Deep vein thrombosis",
    presentation: { complaint: "다리 부종", clues: ["왼쪽 종아리만 붓고 당김", "종아리 둘레 3cm 차이, 발열 없음", "닷새째 침상 안정"] },
    category: "thrombotic",
    traits: ["venous_thrombus", "us_visible"],
    tier: "normal",
    act: 2,
    severity: [44, 50],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { anticoagulant: "weak", thrombolytic: "resistant", antiplatelet: "immune" },
    moves: [
      { id: "embolus_warning", nameKo: "혈전 이동 위험", effects: [warn("embolism", 4)] },
      { id: "embolism", nameKo: "색전", effects: [atk(22, 1, anticoagHalf)] },
      { id: "swelling", nameKo: "부종", effects: [atk(6)] },
      { id: "clot_growth", nameKo: "혈전 성장", effects: [block(8), toSelf("aggravation", 1)] },
    ],
    ai: { opening: ["embolus_warning"], weights: { swelling: 60, clot_growth: 40 }, noRepeat: ["clot_growth"] },
    art: { region: "leg", lesion: [0.6, 0.7, 0.08] },
    passiveText: ["색전은 항응고제가 투여 중이면 절반."],
    medical: { fidelity: "accurate", note: "항응고가 1차. 단순 DVT에 혈전용해는 권고되지 않는다. 항혈소판제는 치료가 아니다" },
  },
  {
    id: "chf",
    nameKo: "급성 심부전 악화",
    nameEn: "Acute decompensated heart failure",
    presentation: { complaint: "호흡곤란", clues: ["누우면 숨이 차 앉아서 잠", "양쪽 다리 함요부종과 경정맥 팽창", "어제 수액 2L 투여"] },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "volume_overload", "resp_failure", "us_visible"],
    tier: "normal",
    act: 2,
    severity: [50, 56],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { loop_diuretic: "weak", fluid: "harmful", beta_blocker: "harmful", vasopressor: "resistant" },
    moves: [
      { id: "pulmonary_edema", nameKo: "폐부종", effects: [atk(11)] },
      { id: "congestion", nameKo: "울혈 악화", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "dyspnea", nameKo: "호흡곤란", effects: [atk(6), toPatient("hypoxia", 1)] },
    ],
    ai: { weights: { pulmonary_edema: 40, congestion: 30, dyspnea: 30 }, noRepeat: ["congestion"] },
    art: { region: "chest", lesion: [0.5, 0.62, 0.22] },
    medical: { fidelity: "accurate", note: "급성 악화기의 수액과 β차단제 신규 시작은 해롭다" },
  },
  {
    id: "he",
    nameKo: "간성뇌증",
    nameEn: "Hepatic encephalopathy",
    presentation: { complaint: "의식 변화", clues: ["낮에도 졸고 엉뚱한 대답을 함", "간경변 병력, 손의 퍼덕떨림", "사흘째 변을 보지 못함"] },
    category: "neuro",
    traits: ["hyperammonemia"],
    tier: "normal",
    act: 2,
    severity: [42, 48],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { ammonia_lowering: "weak", cns_depressant: "harmful" },
    moves: [
      { id: "obtundation", nameKo: "의식 저하", effects: [addCard("confusion", 1, "draw_random")] },
      { id: "asterixis", nameKo: "퍼덕떨림", effects: [atk(7)] },
      { id: "ammonia", nameKo: "암모니아 축적", effects: [toSelf("aggravation", 2)] },
    ],
    ai: { weights: { obtundation: 35, asterixis: 45, ammonia: 20 }, noRepeat: ["obtundation", "ammonia"] },
    art: { region: "head", lesion: [0.5, 0.42, 0.22] },
    medical: { fidelity: "accurate", note: "벤조디아제핀·오피오이드는 간성뇌증을 유발·악화시킨다" },
  },
  {
    id: "delirium",
    nameKo: "섬망",
    nameEn: "Delirium",
    presentation: { complaint: "의식 변화", clues: ["밤이 되면 수액줄을 뽑으려 함", "주의력 저하, 낮에는 비교적 명료", "82세, 입원 사흘째"] },
    category: "neuro",
    traits: ["agitation"],
    tier: "normal",
    act: 2,
    severity: [38, 42],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { antipsychotic: "weak", benzodiazepine: "harmful" },
    moves: [
      { id: "night_agitation", nameKo: "야간 초조", effects: [atk(5), addCard("confusion", 1, "discard")] },
      { id: "inattention", nameKo: "주의력 저하", effects: [toPatient("weak", 1)] },
      { id: "wandering", nameKo: "배회", effects: [atk(4, 2)] },
    ],
    ai: { weights: { night_agitation: 40, inattention: 25, wandering: 35 }, noRepeat: ["inattention"] },
    art: { region: "head", lesion: [0.5, 0.36, 0.18] },
    medical: { fidelity: "simplified", note: "항정신병제는 초조 조절용이며 섬망 기간 단축 근거는 약하다. 벤조디아제핀은 알코올 금단 외에는 악화 요인" },
  },
  {
    id: "cdi",
    nameKo: "C. difficile 감염",
    nameEn: "Clostridioides difficile infection",
    presentation: { complaint: "설사", clues: ["항생제 7일째, 하루 여덟 번 물설사", "백혈구 18,000", "아랫배를 쥐어짜는 통증"] },
    category: "infection",
    traits: ["hypovolemia"],
    tier: "normal",
    act: 2,
    severity: [46, 52],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    organism: "cdiff",
    effectiveness: { cdi_risk: "harmful" },
    passives: [{ on: "drug_administered", condition: { eventDrugTag: "cdi_risk" }, effects: [toSelf("aggravation", 2)] }],
    moves: [
      { id: "watery", nameKo: "수양성 설사", effects: [atk(5, 2)] },
      { id: "toxin", nameKo: "독소", effects: [atk(8), toPatient("dehydration", 1)] },
      { id: "colitis", nameKo: "대장염 악화", effects: [toSelf("inflammation", 2), toSelf("aggravation", 1)] },
    ],
    ai: { weights: { watery: 40, toxin: 35, colitis: 25 }, noRepeat: ["colitis"] },
    art: { region: "abdomen", lesion: [0.5, 0.68, 0.18] },
    passiveText: ["C. diff 위험 약물(광범위 항생제, 세프트리악손, 퀴놀론, PPI)이 투여될 때마다 악화 +2."],
    medical: { fidelity: "simplified", note: "현재 1차는 피닥소마이신 또는 경구 반코마이신(정맥 투여는 대장에 도달하지 않음, 카드는 경로 구분 생략). 원인 항생제·PPI 지속은 악화 요인" },
  },
  {
    id: "af",
    nameKo: "심방세동 빠른 심실 반응",
    nameEn: "Atrial fibrillation with rapid ventricular response",
    presentation: { complaint: "두근거림", clues: ["불규칙하게 불규칙한 맥박 140회", "수술 후 이틀째", "혈압 108/70"] },
    category: "cardiovascular",
    traits: ["cardiac", "arrhythmia", "shockable"],
    tier: "normal",
    act: 2,
    severity: [42, 46],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { antiarrhythmic: "weak", beta_blocker: "weak", defib: "normal", anticoagulant: "resistant" },
    moves: [
      { id: "rvr", nameKo: "빠른 심실 반응", hitsRange: [2, 4], effects: [atk(3, 3)] },
      { id: "low_output", nameKo: "심박출 저하", effects: [atk(4), toPatient("vulnerable", 1)] },
      { id: "thrombus_warning", nameKo: "좌심방 혈전", effects: [warn("embolic_stroke", 4)] },
      { id: "embolic_stroke", nameKo: "색전성 뇌졸중", effects: [atk(18, 1, anticoagHalf)] },
    ],
    ai: {
      opening: ["rvr"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "thrombus_warning", once: true }],
      weights: { rvr: 60, low_output: 40 },
      noRepeat: ["low_output"],
    },
    art: { region: "chest", lesion: [0.58, 0.46, 0.09] },
    passiveText: ["색전성 뇌졸중은 항응고제가 투여 중이면 절반."],
    medical: { fidelity: "simplified", note: "박동수 조절이 1차, 불안정하면 전기적 심율동 전환(카드는 제세동으로 통합). 항응고는 뇌졸중 예방" },
  },
  {
    id: "pe",
    nameKo: "폐색전증",
    nameEn: "Pulmonary embolism",
    presentation: { complaint: "호흡곤란", clues: ["갑자기 시작된 숨참과 숨 쉴 때 찌르는 가슴 통증", "맥박 118, SpO₂ 88%", "수술 후 닷새째"] },
    category: "thrombotic",
    traits: ["chest", "venous_thrombus", "thrombolysable", "shock"],
    tier: "elite",
    act: 2,
    severity: [86, 92],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { anticoagulant: "weak", thrombolytic: "weak", fluid: "resistant", antiplatelet: "immune" },
    moves: [
      { id: "rv_strain", nameKo: "급성 우심부전", effects: [atk(14)] },
      { id: "hypoxemia", nameKo: "저산소혈증", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "clot_burden", nameKo: "혈전 추가", effects: [toSelf("aggravation", 2), block(8)] },
    ],
    ai: { weights: { rv_strain: 40, hypoxemia: 35, clot_burden: 25 }, noRepeat: ["clot_burden"] },
    art: { region: "chest", lesion: [0.4, 0.46, 0.13] },
    medical: { fidelity: "accurate", note: "고위험 폐색전증은 혈전용해. 우심실 과부하에서 대량 수액은 해롭다" },
  },
  {
    id: "pancreatitis",
    nameKo: "중증 급성 췌장염",
    nameEn: "Severe acute pancreatitis",
    presentation: { complaint: "복통", clues: ["등으로 뻗치는 명치 통증과 구토", "리파아제가 정상 상한의 6배", "과음 다음 날 발생"] },
    category: "abdominal",
    traits: ["hypovolemia"],
    tier: "elite",
    act: 2,
    severity: [92, 98],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { fluid: "weak" },
    moves: [
      { id: "epigastric", nameKo: "상복부 통증", effects: [atk(10)] },
      { id: "sirs", nameKo: "전신 염증 반응", effects: [toSelf("inflammation", 4)] },
      { id: "ileus", nameKo: "장마비", effects: [atk(4), addCard("nausea", 2, "discard")] },
      { id: "necrosis_warning", nameKo: "괴사 진행", effects: [warn("necrosis", 4)] },
      { id: "necrosis", nameKo: "췌장 괴사", effects: [raise(15), toSelf("aggravation", 2)] },
    ],
    ai: {
      opening: ["epigastric"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "necrosis_warning", once: true }],
      weights: { epigastric: 40, sirs: 30, ileus: 30 },
      noRepeat: ["sirs", "ileus"],
    },
    art: { region: "abdomen", lesion: [0.54, 0.44, 0.1] },
    medical: { fidelity: "simplified", note: "초기 수액이 핵심이나 과도한 수액은 해롭다. 예방적 항생제는 권고되지 않는다(원인균 없음 → 항생제 무효)" },
  },
  {
    id: "ugib",
    nameKo: "대량 상부위장관 출혈",
    nameEn: "Massive upper gastrointestinal bleeding",
    presentation: { complaint: "토혈", clues: ["선홍색 피를 한 사발 토함", "흑색변, 맥박 124, 혈압 86/54", "한 달째 진통제(NSAID) 복용"] },
    category: "bleeding",
    traits: ["gi_bleed", "hemorrhage", "hypovolemia"],
    tier: "gate",
    act: 2,
    severity: [170, 170],
    diagnosis: { partialAt: 3, confirmAt: 5 },
    effectiveness: {
      endoscopy: "key",
      transfusion: "weak",
      ppi: "weak",
      vasopressor: "resistant",
      anticoagulant: "harmful",
      antiplatelet: "harmful",
      thrombolytic: "harmful",
      beta_blocker: "harmful",
    },
    passives: [{ on: "turn_start", effects: [{ op: "lose_vitality", amount: 2 }] }],
    moves: [
      { id: "hematemesis", nameKo: "토혈", effects: [atk(12)] },
      { id: "hypovolemic", nameKo: "저혈량 쇼크", effects: [toPatient("hypotension", 1)] },
      { id: "rebleed_warning", nameKo: "재출혈 예고", effects: [warn("rebleed", 3)] },
      { id: "rebleed", nameKo: "재출혈", effects: [atk(24), addCard("bleeding", 2, "discard")] },
      { id: "coagulopathy", nameKo: "응고 장애", effects: [toSelf("aggravation", 2), block(10)] },
    ],
    ai: {
      opening: ["hematemesis"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "rebleed_warning" }],
      weights: { hematemesis: 40, hypovolemic: 30, coagulopathy: 30 },
      noRepeat: ["hypovolemic", "coagulopathy"],
    },
    art: { region: "abdomen", lesion: [0.46, 0.36, 0.1] },
    passiveText: ["지속 출혈: 턴이 시작될 때마다 활력 −2."],
    medical: { fidelity: "accurate", note: "소화성 궤양 출혈은 내시경 지혈 + PPI, 제한적 수혈. 항혈전제는 금기" },
  },
] satisfies DiseaseDef[];
