// 3막 중환자실. design.md §5.5
import { addCard, atk, block, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef } from "../../core/types";

const ALL_ABX = ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"];

export const ACT3_DISEASES = [
  {
    id: "vap",
    nameKo: "인공호흡기 관련 폐렴",
    nameEn: "Ventilator-associated pneumonia",
    presentation: { complaint: "발열", clues: ["기관 내 튜브로 누런 가래가 늘어남", "인공호흡기 엿새째, 새 폐 침윤", "산소 요구량 증가"] },
    category: "infection",
    traits: ["chest", "resp_failure"],
    tier: "normal",
    act: 3,
    severity: [60, 66],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: {},
    variants: [
      { id: "pseudomonas", weight: 60, nameKo: "녹농균", organism: "pseudomonas" },
      { id: "mrsa", weight: 40, nameKo: "MRSA", organism: "mrsa" },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 2, start: { beta_lactam: 1, fluoroquinolone: 1 } },
    moves: [
      { id: "sputum", nameKo: "가래 증가", effects: [atk(10)] },
      { id: "hypoxia", nameKo: "저산소", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "inflame", nameKo: "염증", effects: [toSelf("inflammation", 3)] },
    ],
    ai: { weights: { sputum: 45, hypoxia: 30, inflame: 25 }, noRepeat: ["inflame"] },
    art: { region: "chest", lesion: [0.64, 0.62, 0.12] },
    passiveText: ["병원 획득 균: 획득 내성이 2씩 쌓이고, 베타락탐·퀴놀론 내성 1을 안고 시작한다."],
    medical: { fidelity: "simplified", note: "병원 획득 균의 다제내성" },
  },
  {
    id: "aki",
    nameKo: "급성 신손상",
    nameEn: "Acute kidney injury",
    presentation: { complaint: "소변 감소", clues: ["여섯 시간 동안 소변 40mL", "크레아티닌 0.9 → 2.8", "반코마이신과 조영제 노출"] },
    category: "renal",
    traits: ["renal", "renal_failure", "us_visible"],
    tier: "normal",
    act: 3,
    severity: [56, 62],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { dialysis: "key", fluid: "normal", nephrotoxic: "harmful", k_raising: "harmful", loop_diuretic: "immune" },
    moves: [
      { id: "uremia", nameKo: "요독", effects: [atk(9)] },
      { id: "hyperkalemia", nameKo: "칼륨 상승", effects: [addCard("hyperkalemia", 1, "draw_random")] },
      { id: "overload", nameKo: "체액 과다", effects: [atk(4), toPatient("weak", 1)] },
    ],
    ai: { weights: { uremia: 45, hyperkalemia: 30, overload: 25 }, noRepeat: ["hyperkalemia"] },
    art: { region: "pelvis", lesion: [0.5, 0.4, 0.15] },
    medical: { fidelity: "simplified", note: "투석은 고칼륨혈증·산증·체액 과다·요독에 시행. 이뇨제는 신기능 회복을 돕지 않는다. 수액은 혈액량이 부족할 때만" },
  },
  {
    id: "ards",
    nameKo: "급성 호흡곤란 증후군",
    nameEn: "Acute respiratory distress syndrome",
    presentation: { complaint: "호흡곤란", clues: ["산소를 올려도 SpO₂ 85%", "양쪽 폐 침윤, 심부전 소견 없음", "P/F 비 110"] },
    category: "respiratory",
    traits: ["chest", "resp_failure", "volume_overload"],
    tier: "normal",
    act: 3,
    severity: [64, 70],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { airway: "weak", fluid: "harmful", loop_diuretic: "normal", corticosteroid: "normal" },
    moves: [
      { id: "alveolar", nameKo: "폐포 손상", effects: [atk(11)] },
      { id: "refractory", nameKo: "난치성 저산소혈증", effects: [atk(5), toPatient("hypoxia", 1)] },
      { id: "fibrosis", nameKo: "섬유화", effects: [toSelf("aggravation", 2)] },
    ],
    ai: { weights: { alveolar: 45, refractory: 35, fibrosis: 20 }, noRepeat: ["fibrosis"] },
    art: { region: "chest", lesion: [0.5, 0.56, 0.28] },
    medical: { fidelity: "simplified", note: "폐 보호 환기와 보수적 수액 전략. 수액 금기는 과장이나 방향은 맞다" },
  },
  {
    id: "dic",
    nameKo: "파종성 혈관내 응고",
    nameEn: "Disseminated intravascular coagulation",
    presentation: { complaint: "출혈", clues: ["주사 자리마다 멎지 않는 출혈과 점상출혈", "혈소판 32,000, PT 연장", "D-dimer 상승, 피브리노겐 저하"] },
    category: "bleeding",
    traits: ["hemorrhage"],
    tier: "normal",
    act: 3,
    severity: [58, 64],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { transfusion: "weak", anticoagulant: "resistant", thrombolytic: "harmful", antiplatelet: "harmful" },
    moves: [
      { id: "petechiae", nameKo: "점상출혈", effects: [atk(5), addCard("bleeding", 1, "discard")] },
      { id: "consumption", nameKo: "응고인자 소모", effects: [toPatient("vulnerable", 2)] },
      { id: "microthrombi", nameKo: "미세혈전", effects: [atk(7, 2)] },
    ],
    ai: { weights: { petechiae: 35, consumption: 25, microthrombi: 40 }, noRepeat: ["consumption"] },
    art: { region: "body", lesion: [0.5, 0.5, 0.32] },
    medical: { fidelity: "simplified", note: "원인 치료와 혈액제제 보충. 헤파린은 혈전 우세형에서 제한적으로 쓴다" },
  },
  {
    id: "clabsi",
    nameKo: "중심정맥관 관련 혈류감염",
    nameEn: "Central line-associated bloodstream infection",
    presentation: { complaint: "발열", clues: ["중심정맥관 여드레째, 삽입부 발적", "혈액배양 2세트에서 그람 양성 알균", "다른 감염원 없음"] },
    category: "infection",
    traits: ["source"],
    tier: "normal",
    act: 3,
    severity: [58, 64],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { source_control: "key" },
    variants: [
      { id: "mssa", weight: 50, nameKo: "MSSA", organism: "mssa_strep" },
      { id: "mrsa", weight: 50, nameKo: "MRSA", organism: "mrsa" },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    moves: [
      { id: "bacteremia", nameKo: "균혈증", effects: [atk(9)] },
      { id: "rigors", nameKo: "오한", effects: [atk(4, 3)] },
      { id: "biofilm", nameKo: "생물막", effects: [block(12)] },
    ],
    ai: { weights: { bacteremia: 40, rigors: 35, biofilm: 25 }, noRepeat: ["biofilm"] },
    art: { region: "chest", lesion: [0.3, 0.24, 0.08] },
    medical: { fidelity: "accurate", note: "황색포도알균 균혈증은 카테터 제거가 필수. MSSA는 베타락탐이 반코마이신보다 낫다" },
  },
  {
    id: "tamponade",
    nameKo: "심장 눌림증",
    nameEn: "Cardiac tamponade",
    presentation: { complaint: "저혈압", clues: ["혈압 78/60, 경정맥 팽창", "심음이 작고 들숨 때 수축기압이 15 떨어짐", "심장 수술 후 사흘째"] },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "pericardial", "shock", "hypovolemia", "us_visible"],
    tier: "elite",
    act: 3,
    severity: [94, 100],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { pericardiocentesis: "key", vasopressor: "resistant", beta_blocker: "harmful", airway: "harmful", defib: "immune" },
    moves: [
      { id: "low_output", nameKo: "심박출 감소", effects: [atk(12)] },
      { id: "jvd", nameKo: "경정맥 팽창", effects: [block(12), toSelf("aggravation", 1)] },
      { id: "pea_warning", nameKo: "무맥성 전기활동 예고", effects: [warn("pea", 3)] },
      { id: "pea", nameKo: "무맥성 전기활동", effects: [atk(30)] },
    ],
    ai: {
      opening: ["low_output"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "pea_warning" }],
      weights: { low_output: 55, jvd: 45 },
      noRepeat: ["jvd"],
    },
    art: { region: "chest", lesion: [0.53, 0.52, 0.17] },
    medical: { fidelity: "accurate", note: "Beck 삼징. 양압 환기는 정맥 환류를 줄여 허탈을 부른다. 수액은 일시적으로 돕는다" },
  },
  {
    id: "tension_ptx",
    nameKo: "긴장성 기흉",
    nameEn: "Tension pneumothorax",
    presentation: { complaint: "호흡곤란", clues: ["인공호흡기 기도압이 갑자기 치솟음", "왼쪽 호흡음 소실, 기관이 오른쪽으로 밀림", "혈압 80/50"] },
    category: "respiratory",
    traits: ["chest", "pleural", "shock", "us_visible"],
    tier: "elite",
    act: 3,
    severity: [88, 94],
    diagnosis: { partialAt: 2, confirmAt: 4 },
    effectiveness: { chest_tube: "key", airway: "harmful", fluid: "resistant", vasopressor: "resistant" },
    moves: [
      { id: "pressure", nameKo: "흉강 내압 상승", effects: [toSelf("aggravation", 3)] },
      { id: "shift", nameKo: "종격동 편위", effects: [atk(14)] },
      { id: "failure", nameKo: "호흡 부전", effects: [atk(7), toPatient("hypoxia", 1)] },
    ],
    ai: { weights: { pressure: 30, shift: 40, failure: 30 }, noRepeat: ["pressure"] },
    art: { region: "chest", lesion: [0.66, 0.42, 0.2] },
    medical: { fidelity: "accurate", note: "임상 진단 후 즉시 감압한다. 영상을 기다리지 않는다. 양압 환기는 악화시킨다" },
  },
  {
    id: "septic_shock",
    nameKo: "패혈성 쇼크",
    nameEn: "Septic shock",
    presentation: { complaint: "발열", clues: ["39.6℃, 맥박 128, 혈압 88/52", "젖산 4.1", "소변량 감소와 의식 혼미"] },
    category: "infection",
    traits: ["source", "hypovolemia"],
    tier: "boss",
    act: 3,
    severity: [240, 240],
    diagnosis: { partialAt: 3, confirmAt: 5 },
    effectiveness: {},
    variants: [
      { id: "gram_neg", weight: 60, nameKo: "그람 음성 막대균", organism: "gram_neg" },
      { id: "mrsa", weight: 40, nameKo: "MRSA 균혈증", organism: "mrsa" },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    moves: [
      { id: "fever", nameKo: "고열", effects: [atk(10)] },
      { id: "bacteremia", nameKo: "균혈증", effects: [atk(5, 2)] },
      { id: "inflame", nameKo: "염증 반응", effects: [toSelf("inflammation", 2), block(8)] },
    ],
    ai: { weights: { fever: 40, bacteremia: 35, inflame: 25 }, noRepeat: ["inflame"] },
    phases: [
      {
        id: "shock",
        nameKo: "패혈성 쇼크",
        enterAtSeverityPct: 50,
        traitsAdd: ["shock"],
        effectivenessOverride: { fluid: "weak", vasopressor: "weak", corticosteroid: "normal", beta_blocker: "harmful" },
        onEnter: [toPatient("hypotension", 3)],
        moves: [
          { id: "hypoperfusion", nameKo: "조직 저관류", effects: [atk(14)] },
          { id: "cytokine", nameKo: "사이토카인 폭풍", effects: [toSelf("inflammation", 3)] },
          { id: "mof_warning", nameKo: "다장기 부전 예고", effects: [warn("mof", 4)] },
          { id: "mof", nameKo: "다장기 부전", effects: [atk(30)] },
          { id: "bacteremia2", nameKo: "균혈증", effects: [atk(6, 2)] },
        ],
        ai: {
          opening: ["mof_warning"],
          rules: [{ when: { noCountdown: true }, move: "mof_warning" }],
          weights: { hypoperfusion: 40, cytokine: 25, bacteremia2: 35 },
          noRepeat: ["cytokine"],
        },
      },
    ],
    art: { region: "body", lesion: [0.5, 0.45, 0.36] },
    passiveText: ["중증도가 절반 이하로 떨어지면 패혈성 쇼크로 넘어가고, 환자에게 저혈압 3을 건다."],
    medical: { fidelity: "accurate", note: "배양 후 경험적 광범위 항생제, 원인균 확인 후 범위 축소. 노르에피네프린이 1차 승압제. 불응성 쇼크에 스테로이드" },
  },
] satisfies DiseaseDef[];

void addCard;
