// 3막 중환자실. design.md §5.5
import { addCard, atk, block, toPatient, toSelf, warn } from "../ops";
import type { DiseaseDef, EffectOp } from "../../core/types";

const ALL_ABX = ["beta_lactam", "carbapenem", "glycopeptide", "aminoglycoside", "fluoroquinolone", "macrolide", "nitroimidazole"];
const cancel: EffectOp = { op: "cancel_countdowns", target: "target" };
const clearSelf = (status: string): EffectOp => ({ op: "remove_status", status, target: "target", stacks: "all" });
const extra = (n: number): EffectOp => ({ op: "damage", amount: n, target: "target" });

export const ACT3_DISEASES = [
  {
    id: "vap",
    nameKo: "인공호흡기 관련 폐렴",
    nameEn: "Ventilator-associated pneumonia",
    textbook: { keyFeatures: "인공호흡기 며칠째, 누런 가래 증가, 새 폐 침윤, 산소 요구량 증가. 병원균(녹농균·MRSA)을 덮고, 객담 배양으로 좁힌다." },
    category: "infection",
    traits: ["chest", "resp_failure"],
    tier: "normal",
    act: 3,
    severity: [60, 66],
    findings: {
      vitals: "vt_icu_fever",
      hx_onset: "on_days",
      hx_assoc: "as_sputum_purulent",
      hx_risk: "rk_icu_devices",
      ex_cardio: "cd_crackles_focal",
      lab_cbc: "cbc_leukocytosis",
      abga: "abga_hypoxemia",
      xray: "xr_new_infiltrate",
      pocus: "us_blines_focal",
      ct: "ct_consolidation",
      cx_sputum: "cx_sputum_pseudo",
    },
    atypical: { hx_assoc: "as_none", xray: "xr_normal" },
    effectiveness: {},
    variants: [
      { id: "pseudomonas", weight: 60, nameKo: "녹농균", organism: "pseudomonas" },
      { id: "mrsa", weight: 40, nameKo: "MRSA", organism: "mrsa", findings: { cx_sputum: "cx_sputum_mrsa" } },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 2, start: { beta_lactam: 1, fluoroquinolone: 1 } },
    moves: [
      { id: "sputum", nameKo: "가래 증가", pressure: "respiratory", effects: [atk(11)] },
      { id: "hypoxia", nameKo: "저산소", pressure: "respiratory", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "fever_spike", nameKo: "고열", pressure: "infection", effects: [atk(10)] },
      { id: "rigor", nameKo: "오한", pressure: "infection", effects: [atk(6)] },
      { id: "inflame", nameKo: "염증", pressure: "worsening", effects: [toSelf("inflammation", 3), atk(5)] },
    ],
    ai: { weights: { sputum: 45, hypoxia: 30, inflame: 25 }, noRepeat: ["inflame"] },
    art: { region: "chest", lesion: [0.64, 0.62, 0.12] },
    passiveText: ["병원 획득 균: 획득 내성이 2씩 쌓이고, 베타락탐·퀴놀론 내성 1을 안고 시작한다."],
    medical: { fidelity: "simplified", note: "병원 획득 균의 다제내성" },
  },
  {
    id: "aki",
    nameKo: "급성 신손상",
    nameEn: "Acute kidney injury",
    textbook: { keyFeatures: "소변 감소, 크레아티닌·칼륨 상승, 신독성 약물·조영제 노출. 원인 약물을 끊고, 고칼륨·체액 과다가 심하면 투석. 조영제와 칼륨은 악화." },
    category: "renal",
    traits: ["renal", "renal_failure", "us_visible"],
    tier: "normal",
    act: 3,
    severity: [56, 62],
    findings: {
      vitals: "vt_oliguric",
      hx_onset: "on_oliguria",
      hx_assoc: "as_edema_weight",
      hx_risk: "rk_nephrotoxins",
      ex_limb: "lb_bilateral_pitting",
      lab_chem: "chem_aki",
      lab_ua: "ua_muddy_casts",
      ecg: "ecg_peaked_t",
      pocus: "us_no_obstruction",
    },
    atypical: { hx_risk: "rk_none", lab_ua: "ua_normal" },
    effectiveness: { dialysis: "key", fluid: "normal", nephrotoxic: "harmful", k_raising: "harmful", loop_diuretic: "immune" },
    definitive: [{ tags: ["dialysis"], text: "투석: 요독과 칼륨이 교정되었다", effects: [clearSelf("aggravation"), { op: "exhaust_cards", from: ["hand", "draw", "discard"], filter: { ids: ["hyperkalemia"] }, amount: "all" }] }],
    moves: [
      { id: "uremia", nameKo: "요독", pressure: "renal", effects: [atk(10)] },
      { id: "hyperkalemia", nameKo: "칼륨 상승", pressure: "renal", effects: [addCard("hyperkalemia", 1, "draw_random"), atk(5)] },
      { id: "acidosis_rise", nameKo: "대사성 산증 진행", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(4)] },
      { id: "overload", nameKo: "체액 과다", pressure: "respiratory", effects: [atk(6), toPatient("weak", 1)] },
    ],
    ai: { weights: { uremia: 45, hyperkalemia: 30, overload: 25 }, noRepeat: ["hyperkalemia"] },
    art: { region: "pelvis", lesion: [0.5, 0.4, 0.15] },
    medical: { fidelity: "simplified", note: "투석은 고칼륨혈증·산증·체액 과다·요독에 시행. 이뇨제는 신기능 회복을 돕지 않는다. 수액은 혈액량이 부족할 때만" },
  },
  {
    id: "ards",
    nameKo: "급성 호흡곤란 증후군",
    nameEn: "Acute respiratory distress syndrome",
    textbook: { keyFeatures: "패혈증·폐렴 뒤 하루 사이 급격한 저산소, 양쪽 침윤인데 심장은 정상(BNP·목정맥 정상). 폐 보호 환기, 보수적 수액." },
    category: "respiratory",
    traits: ["chest", "resp_failure", "volume_overload"],
    tier: "normal",
    act: 3,
    severity: [64, 70],
    findings: {
      vitals: "vt_icu_hypox",
      hx_onset: "on_acute",
      hx_risk: "rk_sepsis_source",
      ex_cardio: "cd_diffuse_crackles",
      lab_cbc: "cbc_leukocytosis",
      abga: "abga_severe_hypox",
      xray: "xr_bilateral",
      pocus: "us_blines_normal_heart",
      ct: "ct_bilateral_consol",
    },
    atypical: { hx_risk: "rk_none" },
    effectiveness: { airway: "weak", fluid: "harmful", loop_diuretic: "normal", corticosteroid: "normal" },
    definitive: [{ tags: ["airway"], text: "폐 보호 환기: 산소화가 안정되었다", effects: [clearSelf("aggravation")] }],
    moves: [
      { id: "alveolar", nameKo: "폐포 손상", pressure: "respiratory", effects: [atk(11)] },
      { id: "refractory", nameKo: "난치성 저산소혈증", pressure: "respiratory", effects: [atk(6), toPatient("hypoxia", 1)] },
      { id: "fibrosis", nameKo: "섬유화", pressure: "worsening", effects: [toSelf("aggravation", 2), atk(5)] },
    ],
    ai: { weights: { alveolar: 45, refractory: 35, fibrosis: 20 }, noRepeat: ["fibrosis"] },
    art: { region: "chest", lesion: [0.5, 0.56, 0.28] },
    medical: { fidelity: "simplified", note: "폐 보호 환기와 보수적 수액 전략. 수액 금기는 과장이나 방향은 맞다" },
  },
  {
    id: "dic",
    nameKo: "파종성 혈관내 응고",
    nameEn: "Disseminated intravascular coagulation",
    textbook: { keyFeatures: "패혈증 환자의 온몸 출혈과 점상출혈, 혈소판 감소, PT 연장·피브리노겐 저하. 원인 치료와 혈액제제. 항혈소판·혈전용해는 금기." },
    category: "bleeding",
    traits: ["hemorrhage"],
    tier: "normal",
    act: 3,
    severity: [58, 64],
    findings: {
      vitals: "vt_bleeding",
      hx_onset: "on_days",
      hx_assoc: "as_bleeding_sites",
      hx_risk: "rk_sepsis_source",
      ex_limb: "lb_petechiae",
      lab_cbc: "cbc_thrombocytopenia",
      lab_coag: "coag_dic",
    },
    effectiveness: { transfusion: "weak", anticoagulant: "resistant", thrombolytic: "harmful", antiplatelet: "harmful" },
    definitive: [{ tags: ["transfusion"], text: "혈액제제 보충: 출혈이 잦아든다", effects: [{ op: "exhaust_cards", from: ["hand", "draw", "discard"], filter: { ids: ["bleeding"] }, amount: "all" }] }],
    moves: [
      { id: "petechiae", nameKo: "점상출혈", effects: [atk(6), addCard("bleeding", 1, "discard")] },
      { id: "consumption", nameKo: "응고인자 소모", effects: [toPatient("vulnerable", 2), atk(4)] },
      { id: "microthrombi", nameKo: "미세혈전", pressure: "worsening", effects: [atk(6, 2)] },
    ],
    ai: { weights: { petechiae: 35, consumption: 25, microthrombi: 40 }, noRepeat: ["consumption"] },
    art: { region: "body", lesion: [0.5, 0.5, 0.32] },
    medical: { fidelity: "simplified", note: "원인 치료와 혈액제제 보충. 헤파린은 혈전 우세형에서 제한적으로 쓴다" },
  },
  {
    id: "clabsi",
    nameKo: "중심정맥관 관련 혈류감염",
    nameEn: "Central line-associated bloodstream infection",
    textbook: { keyFeatures: "중심정맥관 며칠째 고열·오한, 삽입부 발적, 다른 감염원 없음. 혈액 배양으로 확인하고 카테터를 뽑는다(감염원 제거)." },
    category: "infection",
    traits: ["source"],
    tier: "normal",
    act: 3,
    severity: [58, 64],
    findings: {
      vitals: "vt_icu_fever",
      hx_onset: "on_acute",
      hx_assoc: "as_chills_line",
      hx_risk: "rk_icu_devices",
      ex_limb: "lb_line_erythema",
      lab_cbc: "cbc_leukocytosis",
      cx_blood: "cx_blood_mssa",
      cx_wound: "cx_wound_mssa",
    },
    atypical: { ex_limb: "lb_normal", hx_assoc: "as_none" },
    effectiveness: { source_control: "key" },
    variants: [
      { id: "mssa", weight: 50, nameKo: "MSSA", organism: "mssa_strep" },
      { id: "mrsa", weight: 50, nameKo: "MRSA", organism: "mrsa", findings: { cx_blood: "cx_blood_mrsa", cx_wound: "cx_wound_mrsa" } },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    definitive: [{ tags: ["source_control"], text: "카테터 제거: 생물막이 사라져 항생제가 잘 듣는다", effects: [cancel, { op: "plan_bonus", pct: 30, target: "target" }] }],
    moves: [
      { id: "bacteremia", nameKo: "균혈증", pressure: "infection", effects: [atk(10)] },
      { id: "rigors", nameKo: "오한", pressure: "infection", effects: [atk(3, 2)] },
      { id: "biofilm", nameKo: "생물막", pressure: "worsening", effects: [block(12), atk(4)] },
    ],
    ai: { weights: { bacteremia: 40, rigors: 35, biofilm: 25 }, noRepeat: ["biofilm"] },
    art: { region: "chest", lesion: [0.3, 0.24, 0.08] },
    medical: { fidelity: "accurate", note: "황색포도알균 균혈증은 카테터 제거가 필수. MSSA는 베타락탐이 반코마이신보다 낫다" },
  },
  {
    id: "tamponade",
    nameKo: "심장 눌림증",
    nameEn: "Cardiac tamponade",
    textbook: { keyFeatures: "심장 수술 뒤 저혈압·목정맥 팽창·작은 심음(Beck 삼징). 초음파로 심낭 삼출. 심낭 천자. 양압 환기는 허탈을 부른다." },
    category: "cardiovascular",
    traits: ["chest", "cardiac", "pericardial", "shock", "hypovolemia", "us_visible"],
    tier: "elite",
    act: 3,
    severity: [84, 90],
    findings: {
      vitals: "vt_obstructive",
      hx_onset: "on_hours",
      hx_risk: "rk_cardiac_surgery",
      ex_cardio: "cd_muffled_jvd",
      ex_limb: "lb_cold_clammy",
      abga: "abga_lactic",
      ecg: "ecg_low_voltage",
      xray: "xr_globular_heart",
      pocus: "us_tamponade",
      ct: "ct_pericardial",
    },
    atypical: { ex_cardio: "cd_tachy_clear", ecg: "ecg_sinus_tachy" },
    effectiveness: { pericardiocentesis: "key", vasopressor: "resistant", beta_blocker: "harmful", airway: "harmful", defib: "immune" },
    definitive: [{ tags: ["pericardiocentesis"], text: "심낭 배액: 심장이 다시 찬다", effects: [cancel, clearSelf("aggravation"), extra(10)] }],
    moves: [
      { id: "low_output", nameKo: "심박출 감소", pressure: "hemodynamic", effects: [atk(12)] },
      { id: "jvd", nameKo: "경정맥 팽창", pressure: "worsening", effects: [block(10), toSelf("aggravation", 1)] },
      { id: "pea_warning", nameKo: "무맥성 전기활동 예고", pressure: "complication", effects: [warn("pea", 3)], course: "crs_pulsus" },
      { id: "pea", nameKo: "무맥성 전기활동", effects: [atk(24)] },
    ],
    ai: {
      opening: ["low_output"],
      rules: [{ when: { all: [{ noCountdown: true }, { turnAtLeast: 2 }] }, move: "pea_warning" }],
      weights: { low_output: 55, jvd: 45 },
      noRepeat: ["jvd"],
    },
    art: { region: "chest", lesion: [0.53, 0.52, 0.17] },
    medical: { fidelity: "accurate", note: "Beck 삼징. 양압 환기는 정맥 환류를 줄여 허탈을 부른다. 수액은 일시적으로 돕는다" },
  },
  {
    id: "tension_ptx",
    nameKo: "긴장성 기흉",
    nameEn: "Tension pneumothorax",
    textbook: { keyFeatures: "인공호흡 중 갑작스런 저산소·저혈압, 한쪽 호흡음 소실, 기관 편위. 임상 진단 후 즉시 감압(흉관). 영상을 기다리지 않는다." },
    category: "respiratory",
    traits: ["chest", "pleural", "shock", "us_visible"],
    tier: "elite",
    act: 3,
    severity: [80, 86],
    findings: {
      vitals: "vt_obstructive",
      hx_onset: "on_sudden",
      hx_risk: "rk_icu_devices",
      ex_cardio: "cd_absent_breath",
      ex_limb: "lb_subcut_emphysema",
      abga: "abga_hypoxemia",
      ecg: "ecg_sinus_tachy",
      xray: "xr_ptx",
      pocus: "us_no_sliding",
      ct: "ct_ptx",
    },
    atypical: { ex_limb: "lb_normal", hx_onset: "on_acute" },
    effectiveness: { chest_tube: "key", airway: "harmful", fluid: "resistant", vasopressor: "resistant" },
    definitive: [{ tags: ["chest_tube"], text: "감압 성공: 흉강 내압이 빠졌다", effects: [cancel, clearSelf("aggravation"), extra(10)] }],
    moves: [
      { id: "pressure", nameKo: "흉강 내압 상승", pressure: "worsening", effects: [toSelf("aggravation", 3), atk(5)] },
      { id: "shift", nameKo: "종격동 편위", pressure: "hemodynamic", effects: [atk(12)] },
      { id: "failure", nameKo: "호흡 부전", pressure: "respiratory", effects: [atk(8), toPatient("hypoxia", 1)] },
      { id: "arrest_warning", nameKo: "심정지 예고", pressure: "complication", effects: [warn("arrest", 3)], course: "crs_airway_pressure" },
      { id: "arrest", nameKo: "폐쇄성 심정지", pressure: "hemodynamic", effects: [atk(24)] },
    ],
    ai: { weights: { pressure: 30, shift: 40, failure: 30 }, noRepeat: ["pressure"] },
    art: { region: "chest", lesion: [0.66, 0.42, 0.2] },
    medical: { fidelity: "accurate", note: "임상 진단 후 즉시 감압한다. 영상을 기다리지 않는다. 양압 환기는 악화시킨다" },
  },
  {
    id: "septic_shock",
    nameKo: "패혈성 쇼크",
    nameEn: "Septic shock",
    textbook: { keyFeatures: "고열·저혈압·젖산 상승. 배양을 받고 한 시간 안에 경험적 광범위 항생제, 원인균이 나오면 범위 축소. 수액 후 노르에피네프린." },
    category: "infection",
    traits: ["source", "hypovolemia"],
    tier: "boss",
    act: 3,
    severity: [200, 200],
    findings: {
      vitals: "vt_septic",
      hx_onset: "on_days",
      hx_risk: "rk_sepsis_source",
      ex_limb: "lb_mottled",
      ex_neuro: "nr_drowsy",
      lab_cbc: "cbc_sepsis",
      lab_chem: "chem_lactate_aki",
      abga: "abga_lactic",
      cx_blood: "cx_blood_gnr",
      cx_urine: "cx_urine_gnr",
    },
    effectiveness: {},
    variants: [
      { id: "gram_neg", weight: 60, nameKo: "그람 음성 막대균(요로 기원)", organism: "gram_neg" },
      { id: "mrsa", weight: 40, nameKo: "MRSA 균혈증(피부 기원)", organism: "mrsa", findings: { cx_blood: "cx_blood_mrsa", cx_urine: "cx_neg", cx_wound: "cx_wound_mrsa" } },
    ],
    acquiredResistance: { tags: ALL_ABX, gainPerHit: 1 },
    definitive: [{ tags: ["source_control"], text: "감염원 조절: 염증의 불씨를 뺐다", effects: [clearSelf("inflammation")] }],
    moves: [
      { id: "fever", nameKo: "고열", pressure: "infection", effects: [atk(11)] },
      { id: "bacteremia", nameKo: "균혈증", pressure: "infection", effects: [atk(5, 2)] },
      { id: "inflame", nameKo: "염증 반응", effects: [toSelf("inflammation", 2), block(8), atk(4)] },
    ],
    ai: { weights: { fever: 40, bacteremia: 35, inflame: 25 }, noRepeat: ["inflame"] },
    phases: [
      {
        id: "shock",
        nameKo: "패혈성 쇼크",
        enterAtSeverityPct: 50,
        traitsAdd: ["shock"],
        effectivenessOverride: { fluid: "weak", vasopressor: "weak", corticosteroid: "normal", beta_blocker: "harmful" },
        onEnter: [toPatient("hypotension", 2)],
        moves: [
          { id: "hypoperfusion", nameKo: "조직 저관류", pressure: "hemodynamic", effects: [atk(14)] },
          { id: "cytokine", nameKo: "사이토카인 폭풍", effects: [toSelf("inflammation", 3), atk(5)] },
          { id: "mof_warning", nameKo: "다장기 부전 예고", effects: [warn("mof", 4)] },
          { id: "mof", nameKo: "다장기 부전", effects: [atk(24)] },
          { id: "bacteremia2", nameKo: "균혈증", pressure: "infection", effects: [atk(6, 2)] },
        ],
        ai: {
          opening: ["mof_warning"],
          rules: [{ when: { noCountdown: true }, move: "mof_warning" }],
          weights: { hypoperfusion: 40, cytokine: 25, bacteremia2: 35 },
          noRepeat: ["cytokine"],
        },
      },
    ],
    art: { region: "body", lesion: [0.5, 0.45, 0.36] },
    passiveText: ["질병 부담이 절반 이하로 떨어지면 패혈성 쇼크로 넘어가고, 환자에게 저혈압 2를 건다."],
    medical: { fidelity: "accurate", note: "배양 후 경험적 광범위 항생제, 원인균 확인 후 범위 축소. 노르에피네프린이 1차 승압제. 불응성 쇼크에 스테로이드" },
  },
] satisfies DiseaseDef[];
